### ISSUE TITLE
Getting HttpInterceptingHandler is not a constructor error while universal rendering

### ISSUE THREAD

**Issue by rohitkhatri** [angular/universal#1018]
I'm trying to setup the server side rendering of my angular app, I have followed the instruction from here:

https://github.com/angular/angular-cli/wiki/stories-universal-rendering

Every command runs successfully, but after starting node server, when I try to visit the url, It throws the following error:

```
TypeError: _angular_common_http__WEBPACK_IMPORTED_MODULE_5__.ɵHttpInterceptingHandler is not a constructor
    at zoneWrappedInterceptingHandler (/Stuff/Development/Angular/angular-tuts/universal/dist/server.js:4040:23)
    at _callFactory (/Stuff/Development/Angular/angular-tuts/universal/dist/server.js:14256:20)
    at _createProviderInstance$1 (/Stuff/Development/Angular/angular-tuts/universal/dist/server.js:14210:26)
    at initNgModule (/Stuff/Development/Angular/angular-tuts/universal/dist/server.js:14143:32)
    at new NgModuleRef_ (/Stuff/Development/Angular/angular-tuts/universal/dist/server.js:14872:9)
    at Object.createNgModuleRef (/Stuff/Development/Angular/angular-tuts/universal/dist/server.js:14861:12)
    at NgModuleFactory_.create (/Stuff/Development/Angular/angular-tuts/universal/dist/server.js:17394:25)
    at /Stuff/Development/Angular/angular-tuts/universal/dist/server.js:9693:43
    at ZoneDelegate.invoke (/Stuff/Development/Angular/angular-tuts/universal/dist/server.js:515:26)
    at Object.onInvoke (/Stuff/Development/Angular/angular-tuts/universal/dist/server.js:9035:33)
```

Can anybody please help me with this?

Stackoverflow question reference: 
https://stackoverflow.com/questions/50781778/httpinterceptinghandler-is-not-a-constructor-while-universal-rendering-angularjs

**Comment by twoheaded** [comment]
The same error. And the warning after universal server build:

```
WARNING in ./node_modules/@angular/platform-server/fesm5/platform-server.js
410:26-50 "export 'ɵHttpInterceptingHandler' was not found in '@angular/common/http'
 @ ./node_modules/@angular/platform-server/fesm5/platform-server.js
 @ ./dist/server/main.js
 @ ./server.ts
```

My app: 
```
Angular CLI: 6.0.5
Node: 8.9.3
OS: win32 x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.1
@angular-devkit/build-angular     0.6.1
@angular-devkit/build-optimizer   0.6.1
@angular-devkit/core              0.6.1
@angular-devkit/schematics        0.6.5
@angular/cdk                      6.1.0
@angular/cli                      6.0.5
@angular/flex-layout              6.0.0-beta.15
@angular/material                 6.1.0
@angular/platform-server          6.0.4
@ngtools/webpack                  6.0.1
@schematics/angular               0.6.5
@schematics/update                0.6.5
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.6.0

```

**Comment by kushwahashiv** [comment]
I am also getting the same error.
```
TypeError: _angular_common_http__WEBPACK_IMPORTED_MODULE_5__.ɵHttpInterceptingHandler is not a constructor
    at zoneWrappedInterceptingHandler (E:\projects\seetickets-client\dist\server.js:114288:23)
    at _callFactory (E:\projects\seetickets-client\dist\server.js:13150:20)
    at _createProviderInstance$1 (E:\projects\seetickets-client\dist\server.js:13104:26)
    at resolveNgModuleDep (E:\projects\seetickets-client\dist\server.js:13067:21)
    at _createClass (E:\projects\seetickets-client\dist\server.js:13129:29)
    at _createProviderInstance$1 (E:\projects\seetickets-client\dist\server.js:13101:26)
    at resolveNgModuleDep (E:\projects\seetickets-client\dist\server.js:13067:21)
    at _createClass (E:\projects\seetickets-client\dist\server.js:13137:32)
    at _createProviderInstance$1 (E:\projects\seetickets-client\dist\server.js:13101:26)
    at resolveNgModuleDep (E:\projects\seetickets-client\dist\server.js:13067:21)
```

**Comment by twoheaded** [comment]
Looks like it's a conflict between `platform-server@6.0.4` and `angular/common@6.0.3`. Was fixed in https://github.com/angular/angular/commit/60aa943e2dd4654600c0e53e51b8d7a1ac3730da.

Update your angular dependencies:
```
ng update @angular/core
```
It helped me

**Comment by rohitkhatri** [comment]
@twoheaded Thank you so much, this worked for me. It would be great If you can you also post it as an answer on [stackoverflow question](https://stackoverflow.com/questions/50781778/httpinterceptinghandler-is-not-a-constructor-while-universal-rendering-angularjs), will help others.

Thanks again.

**Comment by kushwahashiv** [comment]
@twoheaded Thanks for the help. 
Eventually, it got fixed by adjusting the module call order i.e. `FlexLayoutServerModule` at last. 
After above fix, I run into completely a different problem. I knew this is appearing because of `authService` I'm calling in `AppComponent` constructor. Although I need to further zero down the the cause of it. 
/shiv

**Comment by Features12** [comment]
@twoheaded, Thank you guy!
