### ISSUE TITLE
Multiple Reference Errors KeyboardEvent, HTMLTextAreaElement, etc...

### ISSUE THREAD

**Issue by webmutation** [angular/universal#1033]
# Bug Report

#### What is the expected behavior?
Ability to do ssr and serve the server.js file
npm run build:ssr && npm run serve:ssr

#### What is the current behavior?
There are multiple ReferenceError being thrown in directives.

```
ReferenceError: KeyboardEvent is not defined
    at C:\universal-starter\dist\server.js:137307:631201
    at Object.h5O6 (C:\universal-starter\dist\server.js:137307:632004)
    at t (C:\universal-starter\dist\server.js:137307:149)
    at Object.xXtw (C:\universal-starter\dist\server.js:137307:788731)
    at t (C:\universal-starter\dist\server.js:137307:149)
    at Object.248f (C:\universal-starter\dist\server.js:137307:66877)
    at t (C:\universal-starter\dist\server.js:137307:149)
    at Object.egsK (C:\universal-starter\dist\server.js:137307:596392)
    at t (C:\universal-starter\dist\server.js:137307:149)
    at Object.wQAS (C:\universal-starter\dist\server.js:137307:767667)
```

```
ReferenceError: HTMLTextAreaElement is not defined
    at C:\universal-starter\dist\server.js:137307:561144
    at Object.bpzl (C:\universal-starter\dist\server.js:137307:561283)
    at t (C:\universal-starter\dist\server.js:137307:149)
    at Object.xXtw (C:\universal-starter\dist\server.js:137307:788198)
    at t (C:\universal-starter\dist\server.js:137307:149)
    at Object.248f (C:\universal-starter\dist\server.js:137307:66877)
    at t (C:\universal-starter\dist\server.js:137307:149)
    at Object.egsK (C:\universal-starter\dist\server.js:137307:596457)
    at t (C:\universal-starter\dist\server.js:137307:149)
    at Object.wQAS (C:\universal-starter\dist\server.js:137307:767732)

```

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
Use any kind of Event like KeyboardEvent, or HTMLTextAreaElement or @HostListener and the server.js will not be able to run.

#### What is the use-case or motivation for changing an existing behavior?
Ability to do SSR render of an angular 5.2 application.

#### Environment:
**@nguniversal versions**
    "@angular/platform-server": "5.2.11",
    "@nguniversal/express-engine": "5.0.0",
    "@nguniversal/module-map-ngfactory-loader": "5.0.0"
    "@angular/cli": "^1.5.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/node": "^8.0.30",
    "cpy-cli": "^1.0.1",
    "express": "^4.15.2",
    "http-server": "^0.10.0",
    "reflect-metadata": "^0.1.10",
    "ts-loader": "^2.3.7",
    "typescript": "~2.4.2"
```
Angular CLI: 1.5.0
Node: 8.9.1
OS: win32 x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

@angular/cdk: 5.2.5
@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.31
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.34
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1

```

#### Is there anything else we should know?

**Comment by webmutation** [comment]
I have added domino, still lots of errors all over the place but now I am able to render

**Comment by ayyash** [comment]
The lastest version of angular bundles (7.2.8) and universal (7.1.1) introduced new code that wasn't generating, in which HTMLElement and the like are being used in the compiled version, cannot tell which of the packages does that, so now it breaks on server
