### ISSUE TITLE
'indexOf' of undefined - Universal + localize-router + ngx-translate Angular5

### ISSUE THREAD

**Issue by albertsanchez** [angular/universal#1034]
Error with Angular Universal and angular 5.2.11.
When I run "run serve: ssr" and I go to the browser this error appears

## Current behavior
ERROR { Error: Uncaught (in promise): TypeError: Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
    at TranslateService.getBrowserLang (project/dist/server.js:37892:25)
    at ManualParserLoader.LocalizeParser._getBrowserLang (/project/dist/server.js:53678:55)
    at ManualParserLoader.LocalizeParser.init (/project/dist/server.js:53502:32)
    at /project/dist/server.js:53825:19

## Environment
<pre>
<code>
//package.json scripts
"scripts": {
    "ng": "ng",
    "build": "ng build --prod",
    "start": "ng serve",
    "test": "ng test",
    "lint": "tslint ./src/**/*.ts -t verbose",
    "e2e": "ng e2e",
    "extract": "ng xi18n --outputPath=src/locale",
    "build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server",
    "serve:ssr": "node dist/server.js",
    "build:client-and-server-bundles": "ng build --prod && ng build --prod --app 1 --output-hashing=false",
    "webpack:server": "webpack --config webpack.config.js --progress --colors"
}
</code></pre>
<pre><code>
ngx-translate version: 8.0.0
Angular version: 5.2.11

 
For Tooling issues:
- Node version: 8.11.3
- Platform:  Mac

</code></pre>

**Comment by Gorniv** [comment]
it is not a problem of SSR. 
ngx-translate work good: https://github.com/Angular-RU/angular-universal-starter/tree/master/src/app/shared/translates
