### ISSUE TITLE
Sub router-outlet content not rendered

### ISSUE THREAD

**Issue by Twois** [angular/universal#1047]
# Bug Report

#### What is the expected behavior?
It should render the content of the sub router-outlet. (main component's routes).

#### What is the current behavior?
In the source view, there is no content in the main.component's router-outlet, so it's empty.

After the browser load the page, i can see the the component, but still, the cawlers cant.

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [X] common
- [X] express-engine
- [ ] hapi-engine
- [X] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
app-routing.module.ts:
```
import { NgModule }             from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

import { MainPage }   from '../pages/main/main.page';
import { MAIN_ROUTES }   from '../pages/main/main.routing';

const routes: Routes = [
  { path: '', component: MainPage, children: MAIN_ROUTES},
  /* { path: '404', redirectTo: ''},
  { path: '**', redirectTo: ''}, */
];

@NgModule({
  imports: [ RouterModule.forRoot(routes, { initialNavigation: 'enabled' }) ],
  exports: [ RouterModule ]
})
export class AppRoutingModule {}
```

main.routing.ts:
```
import { Routes } from '@angular/router';

import { HomePage } from './../home/home.page';
import { ContactPage } from './../contact/contact.page';

export const MAIN_ROUTES: Routes = [
  { path: '', component: HomePage },
  { path: 'contact', component: ContactPage},
];
```
#### What is the use-case or motivation for changing an existing behavior?
Cawlers should see the content of the page

#### Environment:
**@nguniversal versions**
  - express-engine:
```
<!--
Output from: `ng --version`.Angular CLI: 6.1.1
Node: 10.1.0
OS: win32 x64
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.7
@angular-devkit/build-angular      0.6.7
@angular-devkit/build-ng-packagr   0.6.7
@angular-devkit/build-optimizer    0.6.7
@angular-devkit/core               0.6.7
@angular-devkit/schematics         0.7.1
@angular/cdk                       6.2.0
@angular/cli                       6.1.1
@angular/flex-layout               6.0.0-beta.17
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.7
@schematics/angular                0.7.1
@schematics/update                 0.7.1
ng-packagr                         3.0.0
rxjs                               6.2.2
typescript                         2.9.2
webpack                            4.8.3
-->
```

#### Is there anything else we should know?
On the server side I got the following error, but I think this is not the main problem because, in this case it should be problem with the first router-outlet too.

```
ReferenceError: window is not defined
    at new SystemService (C:\webnode\prima-papirtaska\public\dist\server.js:57745:35)
    at SystemService_Factory (C:\webnode\prima-papirtaska\public\dist\server.js:57858:133)
    at _callFactory (C:\webnode\prima-papirtaska\public\dist\server.js:12325:20)
    at _createProviderInstance (C:\webnode\prima-papirtaska\public\dist\server.js:12283:26)
    at resolveNgModuleDep (C:\webnode\prima-papirtaska\public\dist\server.js:12258:17)
    at NgModuleRef_.get (C:\webnode\prima-papirtaska\public\dist\server.js:12951:16)
    at resolveDep (C:\webnode\prima-papirtaska\public\dist\server.js:13316:45)
    at createClass (C:\webnode\prima-papirtaska\public\dist\server.js:13196:32)
    at createDirectiveInstance (C:\webnode\prima-papirtaska\public\dist\server.js:13073:20)
    at createViewNodes (C:\webnode\prima-papirtaska\public\dist\server.js:14293:36)
    at resolvePromise (C:\webnode\prima-papirtaska\public\dist\server.js:937:31)
    at resolvePromise (C:\webnode\prima-papirtaska\public\dist\server.js:894:17)
    at C:\webnode\prima-papirtaska\public\dist\server.js:996:17
    at ZoneDelegate.invokeTask (C:\webnode\prima-papirtaska\public\dist\server.js:544:31)
    at Object.onInvokeTask (C:\webnode\prima-papirtaska\public\dist\server.js:7702:33)
    at ZoneDelegate.invokeTask (C:\webnode\prima-papirtaska\public\dist\server.js:543:36)
    at Zone.runTask (C:\webnode\prima-papirtaska\public\dist\server.js:311:47)
    at drainMicroTaskQueue (C:\webnode\prima-papirtaska\public\dist\server.js:718:35)
    at ZoneTask.invokeTask (C:\webnode\prima-papirtaska\public\dist\server.js:623:21)
    at Server.ZoneTask.invoke (C:\webnode\prima-papirtaska\public\dist\server.js:608:48)
  rejection: ReferenceError: window is not defined
    at new SystemService (C:\webnode\prima-papirtaska\public\dist\server.js:57745:35)
    at SystemService_Factory (C:\webnode\prima-papirtaska\public\dist\server.js:57858:133)
    at _callFactory (C:\webnode\prima-papirtaska\public\dist\server.js:12325:20)
    at _createProviderInstance (C:\webnode\prima-papirtaska\public\dist\server.js:12283:26)
    at resolveNgModuleDep (C:\webnode\prima-papirtaska\public\dist\server.js:12258:17)
    at NgModuleRef_.get (C:\webnode\prima-papirtaska\public\dist\server.js:12951:16)
    at resolveDep (C:\webnode\prima-papirtaska\public\dist\server.js:13316:45)
    at createClass (C:\webnode\prima-papirtaska\public\dist\server.js:13196:32)
    at createDirectiveInstance (C:\webnode\prima-papirtaska\public\dist\server.js:13073:20)
    at createViewNodes (C:\webnode\prima-papirtaska\public\dist\server.js:14293:36),
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value: ReferenceError: window is not defined
    at new SystemService (C:\webnode\prima-papirtaska\public\dist\server.js:57745:35)
    at SystemService_Factory (C:\webnode\prima-papirtaska\public\dist\server.js:57858:133)
    at _callFactory (C:\webnode\prima-papirtaska\public\dist\server.js:12325:20)
    at _createProviderInstance (C:\webnode\prima-papirtaska\public\dist\server.js:12283:26)
    at resolveNgModuleDep (C:\webnode\prima-papirtaska\public\dist\server.js:12258:17)
    at NgModuleRef_.get (C:\webnode\prima-papirtaska\public\dist\server.js:12951:16)
    at resolveDep (C:\webnode\prima-papirtaska\public\dist\server.js:13316:45)
    at createClass (C:\webnode\prima-papirtaska\public\dist\server.js:13196:32)
    at createDirectiveInstance (C:\webnode\prima-papirtaska\public\dist\server.js:13073:20)
    at createViewNodes (C:\webnode\prima-papirtaska\public\dist\server.js:14293:36) },
  zone:
   Zone {
     _properties: { isAngularZone: true },
     _parent:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [ZoneDelegate] },
     _name: 'angular',
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [ZoneDelegate],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Zone],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Zone],
        _invokeZS: [Object],
        _invokeDlgt: [ZoneDelegate],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [ZoneDelegate],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [ZoneDelegate],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [ZoneDelegate],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [ZoneDelegate],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [ZoneDelegate],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _properties: [Object],
        _parent: [Zone],
        _name: 'angular',
        _zoneDelegate: [ZoneDelegate] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data:
      ZoneAwarePromise {
        __zone_symbol__state: 0,
        __zone_symbol__value: ReferenceError: window is not defined
    at new SystemService (C:\webnode\prima-papirtaska\public\dist\server.js:57745:35)
    at SystemService_Factory (C:\webnode\prima-papirtaska\public\dist\server.js:57858:133)
    at _callFactory (C:\webnode\prima-papirtaska\public\dist\server.js:12325:20)
    at _createProviderInstance (C:\webnode\prima-papirtaska\public\dist\server.js:12283:26)
    at resolveNgModuleDep (C:\webnode\prima-papirtaska\public\dist\server.js:12258:17)
    at NgModuleRef_.get (C:\webnode\prima-papirtaska\public\dist\server.js:12951:16)
    at resolveDep (C:\webnode\prima-papirtaska\public\dist\server.js:13316:45)
    at createClass (C:\webnode\prima-papirtaska\public\dist\server.js:13196:32)
    at createDirectiveInstance (C:\webnode\prima-papirtaska\public\dist\server.js:13073:20)
    at createViewNodes (C:\webnode\prima-papirtaska\public\dist\server.js:14293:36) },
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
%c[$RequestService/onConnect] color:blue connected
%c[$RequestService/Emit] color:blue pre response null
%c[$RequestService/messageQueue] color:blue message sent later { key: 'public/auth/get-user',
  data: undefined,
  cb: [Function: cb] }
public/auth/get-user { success: false, errorMsg: 'permission denied' }
%c[$RequestService/Emit] color:blue message response:  { msgId: '8a6111d0-9580-11e8-8132-118d81d4814b',
  data: { success: false, errorMsg: 'permission denied' } }
%c[$RequestService/onDisconnect] color:blue disconnected!
%c[$RequestService/Emit] color:blue waiting for messages:  []
Running on the server with appId=prima-papirtaska
set platform to false
hblid=fco1tCuTxaKzC94C3m39N0N67TEjZkH6; olfsk=olfsk3980861347834932; _ga=GA1.1.410656184.1533059237; _gid=GA1.1.731766222.1533059237; io=fKYB_Oj1l5P9CbsIAAAF
cookies { hblid: 'fco1tCuTxaKzC94C3m39N0N67TEjZkH6',
  olfsk: 'olfsk3980861347834932',
  _ga: 'GA1.1.410656184.1533059237',
  _gid: 'GA1.1.731766222.1533059237',
  io: 'fKYB_Oj1l5P9CbsIAAAF' }
isBrowser null
%c[$RequestService/connect] color:blue site=public&loginHash=null&%24connectionId=
%c[$RequestService/listen] color:blue listener added { nsp: 'AuthService/8ccfeef0-9580-11e8-8132-118d81d4814b',
  key: '$auth/set-user',
  cb: [Function] }
ERROR { Error: Uncaught (in promise): ReferenceError: window is not defined
ReferenceError: window is not defined
    at new SystemService (C:\webnode\prima-papirtaska\public\dist\server.js:57745:35)
    at SystemService_Factory (C:\webnode\prima-papirtaska\public\dist\server.js:57858:133)
    at _callFactory (C:\webnode\prima-papirtaska\public\dist\server.js:12325:20)
    at _createProviderInstance (C:\webnode\prima-papirtaska\public\dist\server.js:12283:26)
    at resolveNgModuleDep (C:\webnode\prima-papirtaska\public\dist\server.js:12258:17)
    at NgModuleRef_.get (C:\webnode\prima-papirtaska\public\dist\server.js:12951:16)
    at resolveDep (C:\webnode\prima-papirtaska\public\dist\server.js:13316:45)
    at createClass (C:\webnode\prima-papirtaska\public\dist\server.js:13196:32)
    at createDirectiveInstance (C:\webnode\prima-papirtaska\public\dist\server.js:13073:20)
    at createViewNodes (C:\webnode\prima-papirtaska\public\dist\server.js:14293:36)
    at resolvePromise (C:\webnode\prima-papirtaska\public\dist\server.js:937:31)
    at resolvePromise (C:\webnode\prima-papirtaska\public\dist\server.js:894:17)
    at C:\webnode\prima-papirtaska\public\dist\server.js:996:17
    at ZoneDelegate.invokeTask (C:\webnode\prima-papirtaska\public\dist\server.js:544:31)
    at Object.onInvokeTask (C:\webnode\prima-papirtaska\public\dist\server.js:7702:33)
    at ZoneDelegate.invokeTask (C:\webnode\prima-papirtaska\public\dist\server.js:543:36)
    at Zone.runTask (C:\webnode\prima-papirtaska\public\dist\server.js:311:47)
    at drainMicroTaskQueue (C:\webnode\prima-papirtaska\public\dist\server.js:718:35)
    at ZoneTask.invokeTask (C:\webnode\prima-papirtaska\public\dist\server.js:623:21)
    at ZoneTask.invoke (C:\webnode\prima-papirtaska\public\dist\server.js:608:48)
  rejection: ReferenceError: window is not defined
    at new SystemService (C:\webnode\prima-papirtaska\public\dist\server.js:57745:35)
    at SystemService_Factory (C:\webnode\prima-papirtaska\public\dist\server.js:57858:133)
    at _callFactory (C:\webnode\prima-papirtaska\public\dist\server.js:12325:20)
    at _createProviderInstance (C:\webnode\prima-papirtaska\public\dist\server.js:12283:26)
    at resolveNgModuleDep (C:\webnode\prima-papirtaska\public\dist\server.js:12258:17)
    at NgModuleRef_.get (C:\webnode\prima-papirtaska\public\dist\server.js:12951:16)
    at resolveDep (C:\webnode\prima-papirtaska\public\dist\server.js:13316:45)
    at createClass (C:\webnode\prima-papirtaska\public\dist\server.js:13196:32)
    at createDirectiveInstance (C:\webnode\prima-papirtaska\public\dist\server.js:13073:20)
    at createViewNodes (C:\webnode\prima-papirtaska\public\dist\server.js:14293:36),
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value: ReferenceError: window is not defined
    at new SystemService (C:\webnode\prima-papirtaska\public\dist\server.js:57745:35)
    at SystemService_Factory (C:\webnode\prima-papirtaska\public\dist\server.js:57858:133)
    at _callFactory (C:\webnode\prima-papirtaska\public\dist\server.js:12325:20)
    at _createProviderInstance (C:\webnode\prima-papirtaska\public\dist\server.js:12283:26)
    at resolveNgModuleDep (C:\webnode\prima-papirtaska\public\dist\server.js:12258:17)
    at NgModuleRef_.get (C:\webnode\prima-papirtaska\public\dist\server.js:12951:16)
    at resolveDep (C:\webnode\prima-papirtaska\public\dist\server.js:13316:45)
    at createClass (C:\webnode\prima-papirtaska\public\dist\server.js:13196:32)
    at createDirectiveInstance (C:\webnode\prima-papirtaska\public\dist\server.js:13073:20)
    at createViewNodes (C:\webnode\prima-papirtaska\public\dist\server.js:14293:36) },
  zone:
   Zone {
     _properties: { isAngularZone: true },
     _parent:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [ZoneDelegate] },
     _name: 'angular',
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [ZoneDelegate],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Zone],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Zone],
        _invokeZS: [Object],
        _invokeDlgt: [ZoneDelegate],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [ZoneDelegate],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [ZoneDelegate],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [ZoneDelegate],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [ZoneDelegate],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [ZoneDelegate],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _properties: [Object],
        _parent: [Zone],
        _name: 'angular',
        _zoneDelegate: [ZoneDelegate] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data:
      ZoneAwarePromise {
        __zone_symbol__state: 0,
        __zone_symbol__value: ReferenceError: window is not defined
    at new SystemService (C:\webnode\prima-papirtaska\public\dist\server.js:57745:35)
    at SystemService_Factory (C:\webnode\prima-papirtaska\public\dist\server.js:57858:133)
    at _callFactory (C:\webnode\prima-papirtaska\public\dist\server.js:12325:20)
    at _createProviderInstance (C:\webnode\prima-papirtaska\public\dist\server.js:12283:26)
    at resolveNgModuleDep (C:\webnode\prima-papirtaska\public\dist\server.js:12258:17)
    at NgModuleRef_.get (C:\webnode\prima-papirtaska\public\dist\server.js:12951:16)
    at resolveDep (C:\webnode\prima-papirtaska\public\dist\server.js:13316:45)
    at createClass (C:\webnode\prima-papirtaska\public\dist\server.js:13196:32)
    at createDirectiveInstance (C:\webnode\prima-papirtaska\public\dist\server.js:13073:20)
    at createViewNodes (C:\webnode\prima-papirtaska\public\dist\server.js:14293:36) },
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
```

**Comment by Twois** [comment]
yet it was the fault, there was a package, what tried to use window. I take it into a wrapper, and now it works as expected.
