### ISSUE TITLE
Server side requests using HttpClient don't support GZIP encoding

### ISSUE THREAD

**Issue by destructive-dragon** [angular/universal#1055]
I'm trying to request some API using the `HttpClient` on my `app.server.module.ts`.

```
this.http.get(`https://apis.justwatch.com/content/translations/en_US?prefix=WEBAPP_&translatable_type=ui_string`)
```

if I use `responseType: 'text'` then it works although the data is still gzipped and I can't parse it as json. Otherwise I get this error:

```
PS C:\dev\projects\angular\ssr-test> yarn serve:ssr
yarn run v1.9.4
$ node dist/server
Node server listening on http://localhost:4000
ERROR HttpErrorResponse {
  headers:
   HttpHeaders {
     normalizedNames: Map {},
     lazyUpdate: null,
     lazyInit: [Function] },
  status: 200,
  statusText: 'OK',
  url: 'https://apis.justwatch.com/content/translations/en_US?prefix=WEBAPP_&translatable_type=ui_string',
  ok: false,
  name: 'HttpErrorResponse',
  message: 'Http failure during parsing for https://apis.justwatch.com/content/translations/en_US?prefix=WEBAPP_&translatable_type=ui_string',
  error:
   { error: SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.onLoad (C:\dev\projects\angular\ssr-test\dist\server.js:71535:51)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\dev\projects\angular\ssr-test\dist\server.js:127163:20)
    at XMLHttpRequest._dispatchProgress (C:\dev\projects\angular\ssr-test\dist\server.js:127658:12)
    at XMLHttpRequest._onHttpResponseEnd (C:\dev\projects\angular\ssr-test\dist\server.js:127613:12)
    at IncomingMessage.<anonymous> (C:\dev\projects\angular\ssr-test\dist\server.js:127572:24)
    at ZoneDelegate.invokeTask (C:\dev\projects\angular\ssr-test\dist\server.js:553:31)
    at Object.onInvokeTask (C:\dev\projects\angular\ssr-test\dist\server.js:7710:33)
    at ZoneDelegate.invokeTask (C:\dev\projects\angular\ssr-test\dist\server.js:552:36)
    at Zone.runTask (C:\dev\projects\angular\ssr-test\dist\server.js:320:47),
     text: '\u001f�\b\u0000\u0000\u0000\u0000\u0000\ ... and so on
```

The same code works flawlessly on the browser.

Angular version: **6.1.3**
Node.js version: **9.2.0**

**Motivation:** I want to request translation files from our API and render them for SEO purposes.

**Comment by destructive-dragon** [comment]
Part of the issue is that our Web API for some reason occasionally ignored the Accept-Encoding header and just delivered gzipped content (with proper Content-Type) anyway. So, to XHRHttpRequests like they do in the browser, I think we need to support the GZIP and I think in general it would be a good thing to support it really.

**Comment by destructive-dragon** [comment]
Related: https://github.com/pwnall/node-xhr2/issues/17

**Comment by CaerusKaru** [comment]
Issue will be tracked exclusively in node-xhr2. We can upgrade to the newer version when it's published; when this happens, please open an issue on angular/angular since that's where the dependency lives.

**Comment by ssatz** [comment]
I am facing the same issue here. How to solve this?
