### ISSUE TITLE
info angular2-universal@0.0.1 Failed to exec preinstall script

### ISSUE THREAD

**Issue by danicomas** [angular/universal#106]
I receive the npm log after run npm install.

```txt
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose readDependencies loading dependencies from C:\Users\daniel.comas\Desktop\universal-master\package.json
5 verbose install where, deps [ 'C:\\Users\\daniel.comas\\Desktop\\universal-master',
5 verbose install   [ 'angular2',
5 verbose install     'browserify',
5 verbose install     'css',
5 verbose install     'event-stream',
5 verbose install     'gulp',
5 verbose install     'gulp-insert',
5 verbose install     'gulp-rename',
5 verbose install     'gulp-uglify',
5 verbose install     'lodash',
5 verbose install     'parse5',
5 verbose install     'q',
5 verbose install     'reflect-metadata',
5 verbose install     'require-dir',
5 verbose install     'run-sequence',
5 verbose install     'vinyl-buffer',
5 verbose install     'vinyl-source-stream',
5 verbose install     'xhr2',
5 verbose install     'bower',
5 verbose install     'brfs',
5 verbose install     'browser-sync',
5 verbose install     'connect-history-api-fallback',
5 verbose install     'connect-livereload',
5 verbose install     'conventional-changelog',
5 verbose install     'del',
5 verbose install     'express',
5 verbose install     'gulp-eslint',
5 verbose install     'gulp-jasmine',
5 verbose install     'gulp-livereload',
5 verbose install     'gulp-load-plugins',
5 verbose install     'gulp-node-inspector',
5 verbose install     'gulp-nodemon',
5 verbose install     'gulp-notify',
5 verbose install     'gulp-protractor',
5 verbose install     'gulp-size',
5 verbose install     'gulp-tslint',
5 verbose install     'gulp-typescript',
5 verbose install     'jasmine',
5 verbose install     'jasmine-reporters',
5 verbose install     'jasmine-spec-reporter',
5 verbose install     'karma',
5 verbose install     'karma-browserify',
5 verbose install     'karma-chrome-launcher',
5 verbose install     'karma-jasmine',
5 verbose install     'karma-phantomjs-launcher',
5 verbose install     'morgan',
5 verbose install     'nodemon',
5 verbose install     'open',
5 verbose install     'phantomjs',
5 verbose install     'opn',
5 verbose install     'protractor',
5 verbose install     'rx',
5 verbose install     'selenium-webdriver',
5 verbose install     'serve-index',
5 verbose install     'serve-static',
5 verbose install     'tsd',
5 verbose install     'typescript',
5 verbose install     'yargs',
5 verbose install     'zone.js' ] ]
6 verbose install where, peers [ 'C:\\Users\\daniel.comas\\Desktop\\universal-master', [] ]
7 verbose installManyTop reading for lifecycle C:\Users\daniel.comas\Desktop\universal-master\package.json
8 info preinstall angular2-universal@0.0.1
9 verbose unsafe-perm in lifecycle true
10 info angular2-universal@0.0.1 Failed to exec preinstall script
11 verbose stack Error: angular2-universal@0.0.1 preinstall: `npm run tsd # && npm run angular-submodule`
11 verbose stack Exit status 1
11 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
11 verbose stack     at EventEmitter.emit (events.js:110:17)
11 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
11 verbose stack     at ChildProcess.emit (events.js:110:17)
11 verbose stack     at maybeClose (child_process.js:1015:16)
11 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
12 verbose pkgid angular2-universal@0.0.1
13 verbose cwd C:\Users\daniel.comas\Desktop\universal-master
14 error Windows_NT 6.3.9600
15 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
16 error node v0.12.4
17 error npm  v2.10.1
18 error code ELIFECYCLE
19 error angular2-universal@0.0.1 preinstall: `npm run tsd # && npm run angular-submodule`
19 error Exit status 1
20 error Failed at the angular2-universal@0.0.1 preinstall script 'npm run tsd # && npm run angular-submodule'.
20 error This is most likely a problem with the angular2-universal package,
20 error not with npm itself.
20 error Tell the author that this fails on your system:
20 error     npm run tsd # && npm run angular-submodule
20 error You can get their info via:
20 error     npm owner ls angular2-universal
20 error There is likely additional logging output above.
21 verbose exit [ 1, true ]

**Comment by gdi2290** [comment]
@danicomas  yeah sorry I haven't tested the reoo in windows yet. can you delete everything after `# &&` in this line https://github.com/angular/universal/blob/master/package.json#L42 and I can give you the npm package we're using for the preview

**Comment by dbabaioff** [comment]
The preinstall script was removed here: https://github.com/angular/universal/commit/10f0c9059be507e4e30ec271455c4806285f4b6c

**Comment by manekinekko** [comment]
@gdi2290 `npm install` works fine on Windows. 

However when trying to `tsc`, things blow up but this is not related to the OS. I have the same on Mac. It has to do again with some missing modules. I thought Jeff had fixed this issue? is this a regression?

![image](https://cloud.githubusercontent.com/assets/1699357/12451149/f4da91ac-bf87-11e5-9b04-a9ad7eec4bf3.png)

**Comment by gdi2290** [comment]
The problem might be ` || true` for windows

**Comment by gdi2290** [comment]
fixed via https://github.com/angular/universal/commit/b5b8d95b224691ed1f10869c8d4f4d0bb2296d8d
