### ISSUE TITLE
Cannot find module "./website/website.module.ngfactory".

### ISSUE THREAD

**Issue by nimatullah** [angular/universal#1076]
# Bug Report
I have implemented angular universal on my existing project. it builds successfully when I the server it gives me an error.
#### What is the expected behavior?
To run perfectly when `node web/server.js`

#### What is the current behavior?
```
ERROR { Error: Uncaught (in promise): Error: Cannot find module "./website/website.module.ngfactory".
Error: Cannot find module "./website/website.module.ngfactory".
    at /home/razmjo/workstation/jobsaf-website/web/server.js:43796:11
    at ZoneDelegate.invoke (/home/razmjo/workstation/jobsaf-website/web/server.js:535:26)
    at Object.onInvoke (/home/razmjo/workstation/jobsaf-website/web/server.js:17463:33)
    at ZoneDelegate.invoke (/home/razmjo/workstation/jobsaf-website/web/server.js:534:32)
    at Zone.run (/home/razmjo/workstation/jobsaf-website/web/server.js:285:43)
    at /home/razmjo/workstation/jobsaf-website/web/server.js:1019:34
    at ZoneDelegate.invokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:568:31)
    at Object.onInvokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:17454:33)
    at ZoneDelegate.invokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:567:36)
    at Zone.runTask (/home/razmjo/workstation/jobsaf-website/web/server.js:335:47)
    at drainMicroTaskQueue (/home/razmjo/workstation/jobsaf-website/web/server.js:742:35)
    at ZoneTask.invokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:647:21)
    at Server.ZoneTask.invoke (/home/razmjo/workstation/jobsaf-website/web/server.js:632:48)
    at Server.emit (events.js:182:13)
    at parserOnIncoming (_http_server.js:658:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at resolvePromise (/home/razmjo/workstation/jobsaf-website/web/server.js:961:31)
    at resolvePromise (/home/razmjo/workstation/jobsaf-website/web/server.js:918:17)
    at /home/razmjo/workstation/jobsaf-website/web/server.js:1020:17
    at ZoneDelegate.invokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:568:31)
    at Object.onInvokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:17454:33)
    at ZoneDelegate.invokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:567:36)
    at Zone.runTask (/home/razmjo/workstation/jobsaf-website/web/server.js:335:47)
    at drainMicroTaskQueue (/home/razmjo/workstation/jobsaf-website/web/server.js:742:35)
    at ZoneTask.invokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:647:21)
    at Server.ZoneTask.invoke (/home/razmjo/workstation/jobsaf-website/web/server.js:632:48)
    at Server.emit (events.js:182:13)
    at parserOnIncoming (_http_server.js:658:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
  rejection:
   { Error: Cannot find module "./website/website.module.ngfactory".
       at /home/razmjo/workstation/jobsaf-website/web/server.js:43796:11
       at ZoneDelegate.invoke (/home/razmjo/workstation/jobsaf-website/web/server.js:535:26)
       at Object.onInvoke (/home/razmjo/workstation/jobsaf-website/web/server.js:17463:33)
       at ZoneDelegate.invoke (/home/razmjo/workstation/jobsaf-website/web/server.js:534:32)
       at Zone.run (/home/razmjo/workstation/jobsaf-website/web/server.js:285:43)
       at /home/razmjo/workstation/jobsaf-website/web/server.js:1019:34
       at ZoneDelegate.invokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:568:31)
       at Object.onInvokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:17454:33)
       at ZoneDelegate.invokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:567:36)
       at Zone.runTask (/home/razmjo/workstation/jobsaf-website/web/server.js:335:47)
       at drainMicroTaskQueue (/home/razmjo/workstation/jobsaf-website/web/server.js:742:35)
       at ZoneTask.invokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:647:21)
       at Server.ZoneTask.invoke (/home/razmjo/workstation/jobsaf-website/web/server.js:632:48)
       at Server.emit (events.js:182:13)
       at parserOnIncoming (_http_server.js:658:12)
       at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17) code: 'MODULE_NOT_FOUND' },
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value:
      { Error: Cannot find module "./website/website.module.ngfactory".
          at /home/razmjo/workstation/jobsaf-website/web/server.js:43796:11
          at ZoneDelegate.invoke (/home/razmjo/workstation/jobsaf-website/web/server.js:535:26)
          at Object.onInvoke (/home/razmjo/workstation/jobsaf-website/web/server.js:17463:33)
          at ZoneDelegate.invoke (/home/razmjo/workstation/jobsaf-website/web/server.js:534:32)
          at Zone.run (/home/razmjo/workstation/jobsaf-website/web/server.js:285:43)
          at /home/razmjo/workstation/jobsaf-website/web/server.js:1019:34
          at ZoneDelegate.invokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:568:31)
          at Object.onInvokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:17454:33)
          at ZoneDelegate.invokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:567:36)
          at Zone.runTask (/home/razmjo/workstation/jobsaf-website/web/server.js:335:47)
          at drainMicroTaskQueue (/home/razmjo/workstation/jobsaf-website/web/server.js:742:35)
          at ZoneTask.invokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:647:21)
          at Server.ZoneTask.invoke (/home/razmjo/workstation/jobsaf-website/web/server.js:632:48)
          at Server.emit (events.js:182:13)
          at parserOnIncoming (_http_server.js:658:12)
          at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17) code: 'MODULE_NOT_FOUND' } },
  zone:
   Zone {
     _properties: { isAngularZone: true },
     _parent:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [ZoneDelegate] },
     _name: 'angular',
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [ZoneDelegate],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Zone],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Zone],
        _invokeZS: [Object],
        _invokeDlgt: [ZoneDelegate],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [ZoneDelegate],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [ZoneDelegate],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [ZoneDelegate],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [ZoneDelegate],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [ZoneDelegate],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _properties: [Object],
        _parent: [Zone],
        _name: 'angular',
        _zoneDelegate: [ZoneDelegate] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data:
      ZoneAwarePromise { __zone_symbol__state: 0, __zone_symbol__value: [Error] },
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
ERROR TypeError: this.request(...).pipe is not a function
    at AuthInterceptor.processIntercept (/home/razmjo/workstation/jobsaf-website/web/server.js:362357:14)
    at AuthInterceptor.intercept (/home/razmjo/workstation/jobsaf-website/web/server.js:362351:21)
    at HttpInterceptorHandler.handle (/home/razmjo/workstation/jobsaf-website/web/server.js:46887:33)
    at HttpXsrfInterceptor.intercept (/home/razmjo/workstation/jobsaf-website/web/server.js:47478:25)
    at HttpInterceptorHandler.handle (/home/razmjo/workstation/jobsaf-website/web/server.js:46887:33)
    at HttpInterceptingHandler.handle (/home/razmjo/workstation/jobsaf-website/web/server.js:47522:27)
    at ZoneClientBackend.delegate (/home/razmjo/workstation/jobsaf-website/web/server.js:4049:29)
    at scheduleTask (/home/razmjo/workstation/jobsaf-website/web/server.js:3954:38)
    at Observable._subscribe (/home/razmjo/workstation/jobsaf-website/web/server.js:3993:13)
    at Observable._trySubscribe (/home/razmjo/workstation/jobsaf-website/web/server.js:32656:25)
    at Observable.subscribe (/home/razmjo/workstation/jobsaf-website/web/server.js:32642:22)
    at /home/razmjo/workstation/jobsaf-website/web/server.js:36010:31
    at subscribeToResult (/home/razmjo/workstation/jobsaf-website/web/server.js:35929:84)
    at MergeMapSubscriber._innerSub (/home/razmjo/workstation/jobsaf-website/web/server.js:36549:90)
    at MergeMapSubscriber._tryNext (/home/razmjo/workstation/jobsaf-website/web/server.js:36544:14)
    at MergeMapSubscriber._next (/home/razmjo/workstation/jobsaf-website/web/server.js:36527:18)
    at MergeMapSubscriber.Subscriber.next (/home/razmjo/workstation/jobsaf-website/web/server.js:32827:18)
    at Observable._subscribe (/home/razmjo/workstation/jobsaf-website/web/server.js:34901:20)
    at Observable._trySubscribe (/home/razmjo/workstation/jobsaf-website/web/server.js:32656:25)
    at Observable.subscribe (/home/razmjo/workstation/jobsaf-website/web/server.js:32642:22)
    at MergeMapOperator.call (/home/razmjo/workstation/jobsaf-website/web/server.js:36505:23)
    at Observable.subscribe (/home/razmjo/workstation/jobsaf-website/web/server.js:32637:22)
    at FilterOperator.call (/home/razmjo/workstation/jobsaf-website/web/server.js:39692:23)
    at Observable.subscribe (/home/razmjo/workstation/jobsaf-website/web/server.js:32637:22)
    at MapOperator.call (/home/razmjo/workstation/jobsaf-website/web/server.js:35609:23)
    at Observable.subscribe (/home/razmjo/workstation/jobsaf-website/web/server.js:32637:22)
    at Observable.ConnectableObservable.connect (/home/razmjo/workstation/jobsaf-website/web/server.js:33464:18)
    at RefCountOperator.call (/home/razmjo/workstation/jobsaf-website/web/server.js:33841:49)
    at Observable.subscribe (/home/razmjo/workstation/jobsaf-website/web/server.js:32637:22)
    at TakeOperator.call (/home/razmjo/workstation/jobsaf-website/web/server.js:39877:23)
    at Observable.subscribe (/home/razmjo/workstation/jobsaf-website/web/server.js:32637:22)
    at TranslateService.setDefaultLang (/home/razmjo/workstation/jobsaf-website/web/server.js:300945:18)
    at new AppComponent (/home/razmjo/workstation/jobsaf-website/web/server.js:179762:19)
    at createClass (/home/razmjo/workstation/jobsaf-website/web/server.js:22947:20)
    at createDirectiveInstance (/home/razmjo/workstation/jobsaf-website/web/server.js:22822:20)
    at createViewNodes (/home/razmjo/workstation/jobsaf-website/web/server.js:24042:36)
    at createRootView (/home/razmjo/workstation/jobsaf-website/web/server.js:23956:5)
    at Object.createProdRootView [as createRootView] (/home/razmjo/workstation/jobsaf-website/web/server.js:24468:12)
    at ComponentFactory_.create (/home/razmjo/workstation/jobsaf-website/web/server.js:22302:29)
    at ComponentFactoryBoundToModule.create (/home/razmjo/workstation/jobsaf-website/web/server.js:16954:29)
    at ApplicationRef.bootstrap (/home/razmjo/workstation/jobsaf-website/web/server.js:18183:40)
    at /home/razmjo/workstation/jobsaf-website/web/server.js:17993:81
    at Array.forEach (<anonymous>)
    at PlatformRef._moduleDoBootstrap (/home/razmjo/workstation/jobsaf-website/web/server.js:17993:44)
    at /home/razmjo/workstation/jobsaf-website/web/server.js:17959:27
    at ZoneDelegate.invoke (/home/razmjo/workstation/jobsaf-website/web/server.js:535:26)
    at Object.onInvoke (/home/razmjo/workstation/jobsaf-website/web/server.js:17463:33)
    at ZoneDelegate.invoke (/home/razmjo/workstation/jobsaf-website/web/server.js:534:32)
    at Zone.run (/home/razmjo/workstation/jobsaf-website/web/server.js:285:43)
    at /home/razmjo/workstation/jobsaf-website/web/server.js:1019:34
    at ZoneDelegate.invokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:568:31)
    at Object.onInvokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:17454:33)
    at ZoneDelegate.invokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:567:36)
    at Zone.runTask (/home/razmjo/workstation/jobsaf-website/web/server.js:335:47)
    at drainMicroTaskQueue (/home/razmjo/workstation/jobsaf-website/web/server.js:742:35)
    at ZoneTask.invokeTask (/home/razmjo/workstation/jobsaf-website/web/server.js:647:21)
    at Server.ZoneTask.invoke (/home/razmjo/workstation/jobsaf-website/web/server.js:632:48)
    at Server.emit (events.js:182:13)
    at parserOnIncoming (_http_server.js:658:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)

```
#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - express-engine:
  - hapi-engine:
  - module-map-ngfactory-loader:
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

```
razmjo@ubuntu:~/workstation/jobsaf-website$ ng -v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.2.3
Node: 10.6.0
OS: linux x64
Angular: 6.1.8
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.8.3 (cli-only)
@angular-devkit/schematics        0.8.3 (cli-only)
@angular/cdk                      6.4.7
@angular/cli                      6.2.3
@angular/material                 6.4.7
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.8.3
rxjs                              6.3.2
typescript                        2.9.2
webpack                           4.8.3
    

```

#### Is there anything else we should know?

**Comment by nimatullah** [comment]
Fixed by adding `ModuleMapLoaderModule`
