### ISSUE TITLE
fs.js:143 throw err Error: ENOENT: no such file or directory, open '/dist/index.html'

### ISSUE THREAD

**Issue by Cibbi83** [angular/universal#1084]
# Bug Report

#### What is the current behavior?
After fixing the window is not defined Error by following solution in server.ts:

`const domino = require('domino');
const fs = require('fs');
const path = require('path');
const template = fs.readFileSync(path.join(__dirname, '.', 'dist', 'index.html')).toString();
const win = domino.createWindow(template);
global['window'] = win;
global['document'] = win.document;`

I am getting a new Error after starting the server (npm run server)

`fs.js:143
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/dist/index.html'
    at Object.fs.openSync (fs.js:577:3)
    at Object.fs.readFileSync (fs.js:483:33)
    at Object.<anonymous> (/MYPATH/dist/server.js:168982:19)
    at Object.<anonymous> (/MYPATH/dist/server.js:169028:30)
    at __webpack_require__ (/MYPATH/dist/server.js:21:30)
    at module.exports.extendStatics (/MYPATH/dist/server.js:70:18)
    at Object.<anonymous> (/MYPATH/dist/server.js:73:10)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)`

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:

1. ng add @ng-toolkit/universal
2. npm run build:prod
3. npm run server

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - express-engine:
  - hapi-engine:
  - module-map-ngfactory-loader:
```
<!--
Output from: `ng --version`.
Angular CLI: 6.0.8
Node: 10.3.0
OS: darwin x64
Angular: 6.1.10

**Comment by Gorniv** [comment]
you need fix path at:
```ts
 res.render(
    '../dist/index',
    {
```

**Comment by CaerusKaru** [comment]
It looks like @Gorniv's solution is correct. If you are still having issues, please provide a minimal reproduction repository so we can investigate.
