### ISSUE TITLE
Unable to run angular universal app with firebase hosting due to zone error

### ISSUE THREAD

**Issue by itsmeneartou** [angular/universal#1095]
# Bug Report

#### What is the expected behavior?
The app should run and not give

#### What is the current behavior?
The below error is coming up

```
 '   Unhandled Promise rejection: factory is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: factory is not a function     at _callFactory (/user_code/node_modules/@angular/core/bundles/core.umd.js:19854:24)     at _createProviderInstance (/user_code/node_modules/@angular/core/bundles/core.umd.js:19810:30)     at resolveNgModuleDep (/user_code/node_modules/@angular/core/bundles/core.umd.js:19771:25)     at NgModuleRef_.get (/user_code/node_modules/@angular/core/bundles/core.umd.js:20479:20)     at resolveDep (/user_code/node_modules/@angular/core/bundles/core.umd.js:20850:49)     at createClass (/user_code/node_modules/@angular/core/bundles/core.umd.js:20730:36)     at createDirectiveInstance (/user_code/node_modules/@angular/core/bundles/core.umd.js:20601:24)     at createViewNodes (/user_code/node_modules/@angular/core/bundles/core.umd.js:21827:40)     at callViewAction (/user_code/node_modules/@angular/core/bundles/core.umd.js:22143:17)     at execComponentViewsAction (/user_code/node_modules/@angular/core/bundles/core.umd.js:22062:17)     at createViewNodes (/user_code/node_modules/@angular/core/bundles/core.umd.js:21855:9)     at callViewAction (/user_code/node_modules/@angular/core/bundles/core.umd.js:22143:17)     at execComponentViewsAction (/user_code/node_modules/@angular/core/bundles/core.umd.js:22062:17)     at createViewNodes (/user_code/node_modules/@angular/core/bundles/core.umd.js:21855:9)     at createRootView (/user_code/node_modules/@angular/core/bundles/core.umd.js:21741:9)     at Object.createProdRootView [as createRootView] (/user_code/node_modules/@angular/core/bundles/core.umd.js:22253:16)     at ComponentFactory_.create (/user_code/node_modules/@angular/core/bundles/core.umd.js:20080:33)     at ComponentFactoryBoundToModule.create (/user_code/node_modules/@angular/core/bundles/core.umd.js:9762:33)     at ApplicationRef.bootstrap (/user_code/node_modules/@angular/core/bundles/core.umd.js:16887:44)     at /user_code/node_modules/@angular/core/bundles/core.umd.js:16695:85     at Array.forEach (native)     at PlatformRef._moduleDoBootstrap (/user_code/node_modules/@angular/core/bundles/core.umd.js:16695:48) TypeError: factory is not a function     at _callFactory (/user_code/node_modules/@angular/core/bundles/core.umd.js:19854:24)     at _createProviderInstance (/user_code/node_modules/@angular/core/bundles/core.umd.js:19810:30)     at resolveNgModuleDep (/user_code/node_modules/@angular/core/bundles/core.umd.js:19771:25)     at NgModuleRef_.get (/user_code/node_modules/@angular/core/bundles/core.umd.js:20479:20)     at resolveDep (/user_code/node_modules/@angular/core/bundles/core.umd.js:20850:49)     at createClass (/user_code/node_modules/@angular/core/bundles/core.umd.js:20730:36)     at createDirectiveInstance (/user_code/node_modules/@angular/core/bundles/core.umd.js:20601:24)     at createViewNodes (/user_code/node_modules/@angular/core/bundles/core.umd.js:21827:40)     at callViewAction (/user_code/node_modules/@angular/core/bundles/core.umd.js:22143:17)     at execComponentViewsAction (/user_code/node_modules/@angular/core/bundles/core.umd.js:22062:17)     at createViewNodes (/user_code/node_modules/@angular/core/bundles/core.umd.js:21855:9)     at callViewAction (/user_code/node_modules/@angular/core/bundles/core.umd.js:22143:17)     at execComponentViewsAction (/user_code/node_modules/@angular/core/bundles/core.umd.js:22062:17)     at createViewNodes (/user_code/node_modules/@angular/core/bundles/core.umd.js:21855:9)     at createRootView (/user_code/node_modules/@angular/core/bundles/core.umd.js:21741:9)     at Object.createProdRootView [as createRootView] (/user_code/node_modules/@angular/core/bundles/core.umd.js:22253:16)     at ComponentFactory_.create (/user_code/node_modules/@angular/core/bundles/core.umd.js:20080:33)     at ComponentFactoryBoundToModule.create (/user_code/node_modules/@angular/core/bundles/core.umd.js:9762:33)     at ApplicationRef.bootstrap (/user_code/node_modules/@angular/core/bundles/core.umd.js:16887:44)     at /user_code/node_modules/@angular/core/bundles/core.umd.js:16695:85     at Array.forEach (native)     at PlatformRef._moduleDoBootstrap (/user_code/node_modules/@angular/core/bundles/core.umd.js:16695:48) | more_vert  '  + 
 '  -- | --  ' ; 

```

#### What modules are related to this issue?
Not much idea about it but from logs it looks like Zone or @angular/core

#### Minimal reproduction with instructions:
I am running this code on firebase cloud functions 
```
import 'zone.js/dist/zone-node';
import 'reflect-metadata';


const express = require('express');
const path = require('path');
const { enableProdMode } = require('@angular/core');
const { renderModuleFactory } = require('@angular/platform-server');

const { AppServerModuleNgFactory, LAZY_MODULE_MAP } = require('../dist/server/main');
const { provideModuleMap } = require('@nguniversal/module-map-ngfactory-loader');
enableProdMode();

const index = require('fs')
  .readFileSync(path.resolve(__dirname, '../dist/browser/index.html'), 'utf8')
  .toString();

let app = express();

app.get('**', function(req, res) {
  renderModuleFactory(AppServerModuleNgFactory, {
    url: req.path,
    document: index,
    extraProviders: [
      provideModuleMap(LAZY_MODULE_MAP)
    ]
  }).then(html => res.status(200).send(html));
});

exports.workernApp = functions.https.onRequest(app);
```

#### What is the use-case or motivation for changing an existing behavior?
Successful running website

**Comment by davidstellini** [comment]
I have the same issue. Did you manage to solve this?

**Comment by kartik2206** [comment]
No I moved on(Didn't used universal app) and didn't tried much after that to solve the issue. Do let me know if you solve the issue.

**Comment by davidstellini** [comment]
I solved it. Sorry I'm on my phone but you can follow the tutorial for
angular firebase 2. I uploaded an example to my github.

**Comment by kartik2206** [comment]
I was doing the same way that was shown in the video back then. I will have a look at your example. Thanks :)

**Comment by CaerusKaru** [comment]
@itsmeneartou Can this be closed? Also please try upgrading zone.js, they've recently patched a lot of issues with Node interactions.

**Comment by maxisam** [comment]
I have this issue as well. I am not even use firebase.

Unhandled Promise rejection: not ready ; Zone: <root> ; Task: Server.addListener:request ; Value: Error: not ready
at /web/dist/server/main.js:1:2131786
at check (/web/dist/server/main.js:1:4033630)
at Server.<anonymous> (/web/dist/server/main.js:1:4034264)
at ZoneDelegate.invokeTask (/web/dist/server/main.js:1:4368987)
at Zone.runTask (/web/dist/server/main.js:1:4361552)
at ZoneTask.invokeTask (/web/dist/server/main.js:1:4370572)
at Server.ZoneTask.options.useG.invoke (/web/dist/server/main.js:1:4370401)


I feel like somewhere there is a promise not being handled.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
