### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by gentios** [angular/universal#1196]
# Bug Report

I am running Angular 7.3.9 with Angular Universa. The project gets build successfully but when I do ```node dist/server/``` I get the following error:

```
/Users/gentios/Downloads/Backup/Documents/Notario/notario-frontend/dist/server.js:282509
        base = base.split('/');
                    ^

TypeError: Cannot read property 'split' of undefined
    at URI.toAbsPath (/Users/gentios/Downloads/Backup/Documents/Notario/notario-frontend/dist/server.js:282509:21)
    at new URI (/Users/gentios/Downloads/Backup/Documents/Notario/notario-frontend/dist/server.js:282390:80)
    at URI.toAbsolute (/Users/gentios/Downloads/Backup/Documents/Notario/notario-frontend/dist/server.js:282455:15)
    at Object.setup (/Users/gentios/Downloads/Backup/Documents/Notario/notario-frontend/dist/server.js:283502:49)
    at /Users/gentios/Downloads/Backup/Documents/Notario/notario-frontend/dist/server.js:283796:19
    at /Users/gentios/Downloads/Backup/Documents/Notario/notario-frontend/dist/server.js:284513:2
    at Object.<anonymous> (/Users/gentios/Downloads/Backup/Documents/Notario/notario-frontend/dist/server.js:284514:3)
    at __webpack_require__ (/Users/gentios/Downloads/Backup/Documents/Notario/notario-frontend/dist/server.js:20:30)
    at Object.tinymce (/Users/gentios/Downloads/Backup/Documents/Notario/notario-frontend/dist/server.js:145747:18)
    at __webpack_require__ (/Users/gentios/Downloads/Backup/Documents/Notario/notario-frontend/dist/server.js:129649:30)
```

If I try to navigate to the ```server.js``` file and the error is in the following function:

```
 toAbsPath: function (base, path) {
        var i, nb = 0, o = [], tr, outPath;
        tr = /\/$/.test(path) ? '/' : '';
        base = base.split('/');
        path = path.split('/');
        each$k(base, function (k) {
          if (k) {
            o.push(k);
          }
        });
        base = o;
        for (i = path.length - 1, o = []; i >= 0; i--) {
          if (path[i].length === 0 || path[i] === '.') {
            continue;
          }
          if (path[i] === '..') {
            nb++;
            continue;
          }
          if (nb > 0) {
            nb--;
            continue;
          }
          o.push(path[i]);
        }
        i = base.length - nb;
        if (i <= 0) {
          outPath = o.reverse().join('/');
        } else {
          outPath = base.slice(0, i).join('/') + '/' + o.reverse().join('/');
        }
        if (outPath.indexOf('/') !== 0) {
          outPath = '/' + outPath;
        }
        if (tr && outPath.lastIndexOf('/') !== outPath.length - 1) {
          outPath += tr;
        }
        return outPath;
      },
```

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [ x ] express-engine
- [ ] hapi-engine
- [ x ] module-map-ngfactory-loader
```

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - **express-engine:  "^7.1.1",**
  - hapi-engine:
  - **module-map-ngfactory-loader: "0.0.0",**

```
Angular CLI: 7.3.9
Node: 8.16.0
OS: darwin x64
Angular: 7.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/pwa                      0.11.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.1.6
webpack                           4.23.1
```

**Comment by gentios** [comment]
Closing issue due to reason that it was not from Angular Universal it self. While I was checking the logs I saw that it was coming from the WYSWIG TinyMce ```at Object.tinymce (/Users/gentios/Downloads/Backup/Documents/Notario/notario-frontend/dist/server.js:145747:18)```
