### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined in main.js

### ISSUE THREAD

**Issue by MontiniCristian** [angular/universal#1216]
# Bug Report

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [X] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
Following the steps described in the [official guide](https://angular.io/guide/universal) I setted up my project from a [template](https://startangular.com/product/sb-admin-bootstrap-4-angular-8/) with angular universal. I ran the command ```npm run build:ssr``` and that's all right but, when it comes to request the bundle from the browse (served with ```npm run serve:ssr```), the following error comes out:
```
TypeError: Cannot read property 'match' of undefined
    at new LanguageTranslationModule (/Users/cristianmontini/s4win/wedding/dist/server/main.js:89053:40)
    at _createClass (/Users/cristianmontini/s4win/wedding/dist/server/main.js:32893:20)
    at _createProviderInstance (/Users/cristianmontini/s4win/wedding/dist/server/main.js:32858:26)
    at initNgModule (/Users/cristianmontini/s4win/wedding/dist/server/main.js:32764:32)
    at new NgModuleRef_ (/Users/cristianmontini/s4win/wedding/dist/server/main.js:33896:9)
    at Object.createNgModuleRef (/Users/cristianmontini/s4win/wedding/dist/server/main.js:33879:12)
    at NgModuleFactory_.create (/Users/cristianmontini/s4win/wedding/dist/server/main.js:46541:25)
    at ngZone.run (/Users/cristianmontini/s4win/wedding/dist/server/main.js:41306:64)
    at ZoneDelegate.invoke (/Users/cristianmontini/s4win/wedding/dist/server.js:542:26)
    at Object.onInvoke (/Users/cristianmontini/s4win/wedding/dist/server/main.js:40613:33)
```

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - express-engine: 8.1.1
  - hapi-engine:
  - module-map-ngfactory-loader:
```

Angular CLI: 8.0.2
Node: 11.10.0
OS: darwin x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.800.6
@angular-devkit/build-angular              0.800.6
@angular-devkit/build-optimizer            0.800.6
@angular-devkit/build-webpack              0.800.6
@angular-devkit/core                       8.0.6
@angular-devkit/schematics                 8.0.2
@angular/cli                               8.0.2
@angular/tsc-wrapped                       0.5.2
@ngtools/json-schema                       1.1.0
@ngtools/webpack                           8.0.6
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.0.2
@schematics/update                         0.800.2
rxjs                                       6.5.2
typescript                                 3.4.5
webpack                                    4.30.0
```

#### Is there anything else we should know?

**Comment by CaerusKaru** [comment]
It's likely that whatever translation library you're using is referencing a browser global, which is unavailable on the server. Your choices are to polyfill that global to restore functionality, or remove the offending module from your server build.

Regardless, this is not an issue with Angular Universal. Better avenues for support are StackOverflow or Gitter.
