### ISSUE TITLE
unable to install hapi-engine through NG CLI

### ISSUE THREAD

**Issue by EMCP** [angular/universal#1217]
# Bug Report

#### What is the expected behavior?

Be able to follow the tutorial command found at https://angular.io/guide/universal

#### What is the current behavior?

see output pasted below

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [ ] express-engine
- [X] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:

```
(master)$ ng add @nguniversal/hapi-engine --clientProject MyProject
Installing packages for tooling via npm.
Cannot find module '@schematics/angular/utility/project-targets'
Error: Cannot find module '@schematics/angular/utility/project-targets'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /PATHTOMYPROJECT/node_modules/@nguniversal/hapi-engine/schematics/install/index.js:25:31
    at Object.defineProperty.value (/PATHTOMYPROJECT/node_modules/@nguniversal/hapi-engine/schematics/install/index.js:3:17)
    at Object.<anonymous> (/PATHTOMYPROJECT/node_modules/@nguniversal/hapi-engine/schematics/install/index.js:9:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

#### What is the use-case or motivation for changing an existing behavior?

Was hoping to use the ng scripting to install everything to get started with HapiJS

eg https://angular.io/guide/universal

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - express-engine:
  - hapi-engine: 
  - module-map-ngfactory-loader:
```
$ ng --version
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.1.5
Node: 8.11.3
OS: darwin x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cli                      6.1.5
@angular/platform-server          8.2.1
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.3.3
typescript                        2.7.2
webpack                           4.9.2
```

#### Is there anything else we should know?

**Comment by khex** [comment]
Try to update your **Angular CLI** to **8.x** and remember it requires Node 12.x

**Comment by EMCP** [comment]
@khex lmk how to update that and I'll give it a try

**Comment by khex** [comment]
For starters download and install from [nodejs.org](https://nodejs.org/en/download/current/) latest current version `12.8` for your **macOS**.

**Comment by alan-agius4** [comment]
Hi @EMCP, you need to use Angular CLI 8+

**Comment by EMCP** [comment]
thank you @khex for pointing out I was a little behind on NodeJS version.. I use https://github.com/nvm-sh/nvm and quickly grabbed the latest
