### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by jlmagee** [angular/universal#122]
I'm sure I ought t be able to figure this out but cannot. Please advise.

[jlmagee@mnetjlm4 universal]$ gulp build
[14:22:09] Using gulpfile ~/webdev/universal/gulpfile.js
[14:22:09] Starting 'build.typescript.all'...
[14:22:09] Starting 'build.typescript.project'...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: File not found with singular glob
    at Glob.<anonymous> (/home/jlmagee/webdev/universal/node_modules/gulp-typescript/node_modules/vinyl-fs/node_modules/glob-stream/index.js:34:30)
    at Glob.emit (events.js:95:17)
    at Glob._finish (/home/jlmagee/webdev/universal/node_modules/gulp-typescript/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:172:8)
    at done (/home/jlmagee/webdev/universal/node_modules/gulp-typescript/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:159:12)
    at Glob._processSimple2 (/home/jlmagee/webdev/universal/node_modules/gulp-typescript/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:652:12)
    at /home/jlmagee/webdev/universal/node_modules/gulp-typescript/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:640:10
    at Glob._stat2 (/home/jlmagee/webdev/universal/node_modules/gulp-typescript/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:736:12)
    at lstatcb_ (/home/jlmagee/webdev/universal/node_modules/gulp-typescript/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:728:12)
    at RES (/home/jlmagee/webdev/universal/node_modules/gulp-typescript/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/node_modules/inflight/inflight.js:23:14)
    at f (/home/jlmagee/webdev/universal/node_modules/gulp-typescript/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/node_modules/once/once.js:17:25)
[jlmagee@mnetjlm4 universal]$

**Comment by jeffbcross** [comment]
I can also reproduce this when running gulp build.

**Comment by jeffbcross** [comment]
Found the issue, a source in the tsconfig.json didn't exist. Sending a PR
