### ISSUE TITLE
Getting error with plugins for Angular Universal

### ISSUE THREAD

**Issue by SushmaThalapaneni** [angular/universal#1220]
When running the universal build command **npm run build:ssr && npm run serve:ssr**, its throwing the following error for all the plugins(@ngu-carousel@1.4.8, ng-pick-datetime@7.0.0,  @ng-bootstrap modals)

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.@ngu/carousel/src/ngu-carousel.service (E:\Givkind_Universal\universal-starter-master\dist\server\main.js:17214:18)
    at __webpack_require__ (E:\Givkind_Universal\universal-starter-master\dist\server\main.js:20:30)
    at Object../src/app/app.server.module.ngfactory.js (E:\Givkind_Universal\universal-starter-master\dist\server\main.js:5516:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng-universal-demo@0.0.0 serve:ssr: `node dist/server`

But I observe the code ending brace is correct in the code, there were no issues in the plugin, but still its throwing the above error.

Am using the below versions:
"Angular" : 7.1.4,
"@ng-bootstrap/ng-bootstrap": "^4.0.2",
 "@nguniversal/common": "^6.0.0",
 "@nguniversal/express-engine": "^6.0.0",
 "@nguniversal/module-map-ngfactory-loader": "^6.0.0",
   "@ngu/carousel": "^1.4.8",
"ng-pick-datetime": "^7.0.0",

Below is the tsconfig.json file:

{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es5",
    "module": "commonjs",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}

https://github.com/angular/universal-starter - am using this boiler plate for my project 
Can you please help with this issue.

**Comment by CaerusKaru** [comment]
You'll need to use Webpack to resolve this issue. My suggestion is to not use the universal-starter, it's unofficially archived. Instead generate a new package using `ng add @nguniversal/express-engine --clientProject <name>` and then try again with that. I apologize for the confusion.
