### ISSUE TITLE
window, document undefined, but not used

### ISSUE THREAD

**Issue by GlauberF** [angular/universal#1245]
# Bug Report

everywhere I need to manipulate the DOM, I put a check, like:
```javascript
hasToken(): boolean {
        return (typeof window !== "undefined") && window.localStorage.getItem('vimbo_token') !== null;
    }
```

so I don't know why he's injecting this into the server (window, document, 'Hammer')

#### What is the current behavior?
```
/var/www/html/pwa-vimbo/dist/server/main.js:319167
})(window, document, 'Hammer');
   ^

ReferenceError: window is not defined
    at Object.yLV6 (/var/www/html/pwa-vimbo/dist/server/main.js:319167:4)
    at __webpack_require__ (/var/www/html/pwa-vimbo/dist/server/main.js:20:30)
    at Object.ZAI4 (/var/www/html/pwa-vimbo/dist/server/main.js:218408:1)
    at __webpack_require__ (/var/www/html/pwa-vimbo/dist/server/main.js:20:30)
    at Object.V7fC (/var/www/html/pwa-vimbo/dist/server/main.js:202591:12)
    at __webpack_require__ (/var/www/html/pwa-vimbo/dist/server/main.js:20:30)
    at Object.K011 (/var/www/html/pwa-vimbo/dist/server/main.js:142202:37)
    at __webpack_require__ (/var/www/html/pwa-vimbo/dist/server/main.js:20:30)
    at Object.0 (/var/www/html/pwa-vimbo/dist/server/main.js:6119:18)
    at __webpack_require__ (/var/www/html/pwa-vimbo/dist/server/main.js:20:30)
```

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [ x ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### version:
```
Angular CLI: 8.3.3
Node: 10.15.3
OS: linux x64
Angular: 9.0.0-next.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.3
@angular-devkit/build-angular              0.803.3
@angular-devkit/build-optimizer            0.803.3
@angular-devkit/build-webpack              0.803.3
@angular-devkit/core                       8.3.3
@angular-devkit/schematics                 8.3.3
@angular/cdk                               8.2.0
@angular/cli                               8.3.3
@angular/flex-layout                       8.0.0-beta.26
@angular/material                          8.2.0
@angular/material-moment-adapter           8.2.0
@ngtools/webpack                           8.3.3
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.3.3
@schematics/update                         0.803.3
rxjs                                       6.5.3
typescript                                 3.5.3
webpack                                    4.39.2
```

**Comment by kovaletsyurii** [comment]
Just put 'window' value into globals object in server ts:
```
const domino = require('domino');
const fs = require('fs');
const template = fs.readFileSync('dist/index.html').toString();
const win = domino.createWindow(template);

global['window'] = win;
global['document'] = win.document;

```

**Comment by GlauberF** [comment]
This approach is not recommended.
In fact my question is why he is creating that injection (window, document ...) at the end of the server file, and where I use document or window, I put it inside a
```javascript
(typeof window !== "undefined")
```
the server would not enter this validation.

**Comment by CaerusKaru** [comment]
Please see https://stackoverflow.com/questions/49335441/how-to-use-hammer-in-angular-universal
