### ISSUE TITLE
Error: This method is not implemented in DominoAdapter: getCookie

### ISSUE THREAD

**Issue by sathishvikkas** [angular/universal#1261]
I tried to implement universal with my existing angular 8 app. Got a below error in the browser .Tried so many ways to resolve it .Nothing is working

**Error: This method is not implemented in DominoAdapter: getCookie**
    at _notImplemented (E:\myapp\src\main\kiosk\dist\server\main.js:251176:16)
    at DominoAdapter.getCookie (E:\myapp\src\main\kiosk\dist\server\main.js:251367:69)
    at CookieXSRFStrategy.configureRequest (E:\myapp\src\main\kiosk\dist\server\main.js:232244:55)
    at XHRBackend.createConnection (E:\myapp\src\main\kiosk\dist\server\main.js:232286:32)
    at httpRequest (E:\myapp\src\main\kiosk\dist\server\main.js:232656:24)
    at Http.request (E:\myapp\src\main\kiosk\dist\server\main.js:232755:38)
    at Http.get (E:\myapp\src\main\kiosk\dist\server\main.js:232766:25)
    at TranslateStaticLoader.getTranslation (E:\myapp\src\main\kiosk\dist\server\main.js:234614:26)
    at TranslateService.TYKV.TranslateService.getTranslation (E:\myapp\src\main\kiosk\dist\server\main.js:184506:43)
    at TranslateService.TYKV.TranslateService.retrieveTranslations (E:\myapp\src\main\kiosk\dist\server\main.js:184495:28)

In a browser console getting this one 
Refused to load the image 'http://localhost:8888/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by alan-agius4** [comment]
This seems to be an isolated issue which not much interest from the community. As such this does not warrant to be included in the docs.
