### ISSUE TITLE
ERROR { Error: Uncaught (in promise): Error at resolvePromise

### ISSUE THREAD

**Issue by darshitmaniar** [angular/universal#1318]
I have implemented angular universal on my existing project. it builds successfully but when run the build it gives me an error.

What is the current behaviour?
```
ERROR [Error]
ERROR { Error: Uncaught (in promise): Error
    at resolvePromise (\dist\server.js:992:31)
    at resolvePromise (\dist\server.js:949:17)
    at \dist\server.js:1053:17
    at ZoneDelegate.invokeTask (\dist\server.js:563:31)
    at Object.onInvokeTask (\node_modules\@angular\core\bundles\core.umd.js:26361:37)
    at ZoneDelegate.invokeTask (\dist\server.js:562:60)
    at Zone.runTask (\dist\server.js:335:47)
    at drainMicroTaskQueue (\dist\server.js:741:35)
    at ZoneTask.invokeTask (\dist\server.js:642:21)
    at Server.ZoneTask.invoke (\dist\server.js:627:48)
  rejection: Error,
  promise:
   ZoneAwarePromise [Promise] { __zone_symbol__state: 0, __zone_symbol__value: Error },
  zone:
   Zone {
     _parent:
      Zone {
        _parent: null,
        _name: '<root>',
        _properties: {},
        _zoneDelegate: [ZoneDelegate] },
     _name: 'angular',
     _properties: { isAngularZone: true },
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [ZoneDelegate],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Zone],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Zone],
        _invokeZS: [Object],
        _invokeDlgt: [ZoneDelegate],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [ZoneDelegate],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [ZoneDelegate],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [ZoneDelegate],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [ZoneDelegate],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [ZoneDelegate],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _parent: [Zone],
        _name: 'angular',
        _properties: [Object],
        _zoneDelegate: [ZoneDelegate] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data:
      ZoneAwarePromise [Promise] { __zone_symbol__state: 0, __zone_symbol__value: Error },
     scheduleFn: undefined,
     cancelFn: undefined,
     callback: [Function],
     invoke: [Function] } }
Error
```

package.json
```
"dependencies": {
    "@agm/core": "^1.0.0",
    "@angular-devkit/architect": "^0.803.12",
    "@angular/animations": "^8.0.0",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/flex-layout": "^8.0.0-beta.27",
    "@angular/forms": "^8.0.0",
    "@angular/http": "^7.2.15",
    "@angular/material": "^8.0.0",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/router": "^8.0.0",
    "@angular/upgrade": "^8.0.0",
    "@ng-bootstrap/ng-bootstrap": "^5.1.1",
    "@ngrx/effects": "^8.0.0",
    "@ngrx/entity": "^8.0.0",
    "@ngrx/router-store": "^8.0.0",
    "@ngrx/store": "^8.0.0",
    "@ngrx/store-devtools": "^8.0.0",
    "@nguniversal/express-engine": "^8.1.1",
    "@nguniversal/module-map-ngfactory-loader": "^8.1.1",
    "angular-in-memory-web-api": "^0.9.0",
    "bootstrap": "^4.3.1",
    "classify": "^0.10.0",
    "core-js": "^2.5.4",
    "express": "^4.17.1",
    "flag-icon-css": "^3.4.2",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jquery": "^3.4.1",
    "jw-bootstrap-switch-ng2": "^2.0.5",
    "lodash.assign": "^4.2.0",
    "moment": "^2.24.0",
    "moment-mini": "^2.22.1",
    "ng-recaptcha": "^5.0.0",
    "ng5-slider": "^1.2.4",
    "ngx-bootstrap": "^5.2.0",
    "ngx-cookie": "^4.1.2",
    "ngx-device-detector": "^1.3.11",
    "ngx-drag-scroll": "^8.0.0-beta.2",
    "ngx-flag-icon-css": "^1.0.1",
    "ngx-image-zoom": "^0.4.1",
    "ngx-slick-carousel": "^0.4.6",
    "ramda": "^0.26.1",
    "rxjs": "^6.5.1",
    "rxjs-compat": "^6.5.3",
    "rxjs-tslint": "^0.1.7",
    "sass-mediaqueries": "^1.6.1",
    "slick-carousel": "^1.8.1",
    "true-case-path": "^2.2.1",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.800.0",
    "@angular/cli": "^8.0.0",
    "@angular/compiler-cli": "^8.0.0",
    "@angular/language-service": "^8.2.11",
    "@angular/platform-server": "^8.2.11",
    "@ngrx/schematics": "^8.4.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "^2.0.4",
    "@types/node": "~8.9.4",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "lodash": "^4.16.2",
    "protractor": "~5.4.0",
    "ts-loader": "^4.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3",
    "webpack-cli": "^3.1.0"
  },
```

**Comment by alan-agius4** [comment]
Can you please share a reproduction?  Or at the very least the `server,ts` file and the command you are trying to run?

Also, kindly try to update `@angular-devkit/build-angular` to the latest stable version.

Thanks.

**Comment by darshitmaniar** [comment]
@alan-agius4  here is the Server.ts file and build command
```
// These are important and needed before anything else
import 'zone.js/dist/zone-node';
import 'reflect-metadata';

import * as express from 'express';
import { join } from 'path';


// Express server
const app = express();

const PORT = process.env.PORT || 4000;
const DIST_FOLDER = join(process.cwd(), 'dist');

// * NOTE :: leave this as require() since this file is built Dynamically from webpack
const { AppServerModuleNgFactory, LAZY_MODULE_MAP, ngExpressEngine, provideModuleMap } = require('./dist/server/main');


app.engine('html', ngExpressEngine({
  bootstrap: AppServerModuleNgFactory,
  providers: [
    provideModuleMap(LAZY_MODULE_MAP)
  ]
}));

app.set('view engine', 'html');
app.set('views', join(DIST_FOLDER, 'browser'));

// TODO: implement data requests securely
app.get('/api/*', (req, res) => {
  res.status(404).send('data requests are not supported');
});

// Server static files from /browser
app.get('*.*', express.static(DIST_FOLDER,{
  maxAge: '1y'
}));

// All regular routes use the Universal engine
app.get('*', (req, res) => {
  res.render('index', { req });
});

// Start up the Node server
app.listen(PORT, () => {
  console.log(`Node server listening on http://localhost:${PORT}`);
});

```
First I runt the build:ssr command then serve:ssr build
    "build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server",
    "serve:ssr": "node dist/server.js",
    "build:client-and-server-bundles": "ng build --prod && ng run showroom-ui:server",
    "webpack:server": "webpack --config webpack.server.config.js --progress --colors"

**Comment by darshitmaniar** [comment]
The issue is resolved to updating service method call with Observable<any>instead of toPromise()
