### ISSUE TITLE
Error: Runtime compiler is not loaded

### ISSUE THREAD

**Issue by darshitmaniar** [angular/universal#1324]
# Bug Report

#### What is the expected behavior?
Load the page using SSR.

#### What is the current behavior?
The web page is loaded without SSR and getting runtime error:
```
ERROR { Error: Uncaught (in promise): Error: Runtime compiler is not loaded
Error: Runtime compiler is not loaded
    at Compiler._throwError (D:\Darshit\showroom\node_modules\@angular\core\bundles\core.umd.js:25904:15)
    at MergeMapSubscriber.project (D:\Darshit\showroom\node_modules\@angular\router\bundles\router.umd.js:3799:57)
    at MergeMapSubscriber._tryNext (D:\Darshit\showroom\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (D:\Darshit\showroom\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (D:\Darshit\showroom\node_modules\rxjs\internal\Subscriber.js:66:18)
    at D:\Darshit\showroom\node_modules\rxjs\internal\util\subscribeToPromise.js:7:24
    at ZoneDelegate.invoke (D:\Darshit\showroom\dist\server.js:526:26)
    at Object.onInvoke (D:\Darshit\showroom\node_modules\@angular\core\bundles\core.umd.js:26371:37)
    at ZoneDelegate.invoke (D:\Darshit\showroom\dist\server.js:525:52)
    at Zone.run (D:\Darshit\showroom\dist\server.js:285:43)
    at resolvePromise (D:\Darshit\showroom\dist\server.js:987:31)
    at resolvePromise (D:\Darshit\showroom\dist\server.js:944:17)
    at D:\Darshit\showroom\dist\server.js:1048:17
    at ZoneDelegate.invokeTask (D:\Darshit\showroom\dist\server.js:558:31)
    at Object.onInvokeTask (D:\Darshit\showroom\node_modules\@angular\core\bundles\core.umd.js:26362:37)
    at ZoneDelegate.invokeTask (D:\Darshit\showroom\dist\server.js:557:60)
    at Zone.runTask (D:\Darshit\showroom\dist\server.js:330:47)
    at drainMicroTaskQueue (D:\Darshit\showroom\dist\server.js:736:35)
    at ZoneTask.invokeTask (D:\Darshit\showroom\dist\server.js:637:21)
    at ZoneTask.invoke (D:\Darshit\showroom\dist\server.js:622:48)
  rejection:
   Error: Runtime compiler is not loaded
       at Compiler._throwError (D:\Darshit\showroom\node_modules\@angular\core\bundles\core.umd.js:25904:15)
       at MergeMapSubscriber.project (D:\Darshit\showroom\node_modules\@angular\router\bundles\router.umd.js:3799:57)
       at MergeMapSubscriber._tryNext (D:\Darshit\showroom\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
       at MergeMapSubscriber._next (D:\Darshit\showroom\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
       at MergeMapSubscriber.Subscriber.next (D:\Darshit\showroom\node_modules\rxjs\internal\Subscriber.js:66:18)
       at D:\Darshit\showroom\node_modules\rxjs\internal\util\subscribeToPromise.js:7:24
       at ZoneDelegate.invoke (D:\Darshit\showroom\dist\server.js:526:26)
       at Object.onInvoke (D:\Darshit\showroom\node_modules\@angular\core\bundles\core.umd.js:26371:37)
       at ZoneDelegate.invoke (D:\Darshit\showroom\dist\server.js:525:52)
       at Zone.run (D:\Darshit\showroom\dist\server.js:285:43),
  promise:
   ZoneAwarePromise [Promise] {
     __zone_symbol__state: 0,
     __zone_symbol__value:
      Error: Runtime compiler is not loaded
          at Compiler._throwError (D:\Darshit\showroom\node_modules\@angular\core\bundles\core.umd.js:25904:15)
          at MergeMapSubscriber.project (D:\Darshit\showroom\node_modules\@angular\router\bundles\router.umd.js:3799:57)
          at MergeMapSubscriber._tryNext (D:\Darshit\showroom\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
          at MergeMapSubscriber._next (D:\Darshit\showroom\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
          at MergeMapSubscriber.Subscriber.next (D:\Darshit\showroom\node_modules\rxjs\internal\Subscriber.js:66:18)
          at D:\Darshit\showroom\node_modules\rxjs\internal\util\subscribeToPromise.js:7:24
          at ZoneDelegate.invoke (D:\Darshit\showroom\dist\server.js:526:26)
          at Object.onInvoke (D:\Darshit\showroom\node_modules\@angular\core\bundles\core.umd.js:26371:37)
          at ZoneDelegate.invoke (D:\Darshit\showroom\dist\server.js:525:52)
          at Zone.run (D:\Darshit\showroom\dist\server.js:285:43) },
  zone:
   Zone {
     _parent:
      Zone {
        _parent: null,
        _name: '<root>',
        _properties: {},
        _zoneDelegate: [ZoneDelegate] },
     _name: 'angular',
     _properties: { isAngularZone: true },
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [ZoneDelegate],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Zone],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Zone],
        _invokeZS: [Object],
        _invokeDlgt: [ZoneDelegate],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [ZoneDelegate],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [ZoneDelegate],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [ZoneDelegate],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [ZoneDelegate],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [ZoneDelegate],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _parent: [Zone],
        _name: 'angular',
        _properties: [Object],
        _zoneDelegate: [ZoneDelegate] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data:
      ZoneAwarePromise [Promise] {
        __zone_symbol__state: 0,
        __zone_symbol__value:
         Error: Runtime compiler is not loaded
             at Compiler._throwError (D:\Darshit\showroom\node_modules\@angular\core\bundles\core.umd.js:25904:15)
             at MergeMapSubscriber.project (D:\Darshit\showroom\node_modules\@angular\router\bundles\router.umd.js:3799:57)
             at MergeMapSubscriber._tryNext (D:\Darshit\showroom\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
             at MergeMapSubscriber._next (D:\Darshit\showroom\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
             at MergeMapSubscriber.Subscriber.next (D:\Darshit\showroom\node_modules\rxjs\internal\Subscriber.js:66:18)
             at D:\Darshit\showroom\node_modules\rxjs\internal\util\subscribeToPromise.js:7:24
             at ZoneDelegate.invoke (D:\Darshit\showroom\dist\server.js:526:26)
             at Object.onInvoke (D:\Darshit\showroom\node_modules\@angular\core\bundles\core.umd.js:26371:37)
             at ZoneDelegate.invoke (D:\Darshit\showroom\dist\server.js:525:52)
             at Zone.run (D:\Darshit\showroom\dist\server.js:285:43) },
     scheduleFn: undefined,
     cancelFn: undefined,
     callback: [Function],
     invoke: [Function] } } 
```

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ X] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
Here is my updated Angular.json
```
"server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/server",
            "main": "src/main.server.ts",
            "tsConfig": "tsconfig.server.json",
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        }
```

#### What is the use-case or motivation for changing an existing behavior?
nothing to change it.

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - express-engine:
  - hapi-engine:
  - module-map-ngfactory-loader:
```
<!--
Angular CLI: 8.3.17
Node: 10.16.3
OS: win32 x64
Angular: 8.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, upgrade

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.17
@angular-devkit/build-angular              0.800.6
@angular-devkit/build-optimizer            0.800.6
@angular-devkit/build-webpack              0.800.6
@angular-devkit/core                       8.3.17
@angular-devkit/schematics                 8.3.17
@angular/cdk                               8.2.3
@angular/cli                               8.3.17
@angular/flex-layout                       8.0.0-beta.27
@angular/http                              7.2.15
@angular/material                          8.2.3
@ngtools/webpack                           8.0.6
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.3.17
@schematics/update                         0.803.17
rxjs                                       6.5.3
typescript                                 3.4.5
webpack                                    4.30.0


-->
```

#### Is there anything else we should know?

**Comment by alan-agius4** [comment]
Hi, can you please share a reproduction? Thanks.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
