### ISSUE TITLE
Need to minify/uglify 'server.js' file

### ISSUE THREAD

**Issue by waseem-isaac-BBN** [angular/universal#1377]
My `server.js` file is > 10MB , it opens slowly So I tried to Minify/Uglify it 

```
gulp.task("default", function () {
    return gulp.src("big-server.js")
        .pipe(rename("server.js"))
        .pipe(minify()) // Or .pipe(uglify()) 
        .pipe(gulp.dest("."));
});
```
But it crashs after running this task , The bellow error appears :
```
TypeError: Right-hand side of 'instanceof' is not an object
    at _t (D:\zvendo\cloned-electroo\dist\server.js:1:1471780)
    at yt (D:\zvendo\cloned-electroo\dist\server.js:1:1471655)
    at or (D:\zvendo\cloned-electroo\dist\server.js:1:1494450)
    at Ge.insertToken (D:\zvendo\cloned-electroo\dist\server.js:1:1471041)
    at D:\zvendo\cloned-electroo\dist\server.js:1:1474343
    at It (D:\zvendo\cloned-electroo\dist\server.js:1:1474358)
    at Ke (D:\zvendo\cloned-electroo\dist\server.js:1:1469303)
    at Object.parse (D:\zvendo\cloned-electroo\dist\server.js:1:1468269)
    at Object.t.createDocument (D:\zvendo\cloned-electroo\dist\server.js:1:1205968)
    at Object.t.createWindow (D:\zvendo\cloned-electroo\dist\server.js:1:1206347)
```

**Comment by alan-agius4** [comment]
In version 9 you can minify the server bundle by using `ng run app:server:production`

**Comment by waseem-isaac-BBN** [comment]
@alan-agius4 
Is there's any way to fix this issue with angular < 9 .. before v 9 is released .So that I don't 've to wait?

**Comment by alan-agius4** [comment]
You can try to use the above command with "--bundleDependencies=all", if
you are using Angular CLI 8.2+

**Comment by waseem-isaac-BBN** [comment]
@alan-agius4 
Can't I use it with angular-cli 7.3 ?
It crashs while  JitCompiler _loadModules )):

**Comment by alan-agius4** [comment]
@waseem-isaac-BBN, in version 8 there were a lot of fixes related to server bundling. And I won't be surprised that the issue you are seeing now it's fixed.

**Comment by waseem-isaac-BBN** [comment]
@alan-agius4 
Yes I seen , but `server/main.js` became too large . now it has the size of angular 7 server.js  :)))
we require `server/main.js` in `server.ts` so what the point ?
the app still wait some seconds for the resources to be loaded .
I'm looking for some ways to fix that without refactoring my main code .
