### ISSUE TITLE
Error updating from 8(.1.1) to 9(.0.0-next.13)

### ISSUE THREAD

**Issue by chrstphrrbn** [angular/universal#1417]
I'm just assuming this should work, feel free to correct me. :)

When running `ng update @nguniversal/common --next` I get an error after the packages are installed:

> Packages installed successfully.
> An unhandled exception occurred: Cannot find module '@schematics/angular/utility/workspace'
> See "***/angular-errors.log" for further details.

**Comment by chrstphrrbn** [comment]
Log file content:
[error] Error: Cannot find module '@schematics/angular/utility/workspace'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /***/node_modules/@nguniversal/common/schematics/migrations/update-9/index.js:30:25
    at /***/node_modules/@nguniversal/common/schematics/migrations/update-9/index.js:19:17
    at Object.<anonymous> (/***/node_modules/@nguniversal/common/schematics/migrations/update-9/index.js:25:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /***/node_modules/@nguniversal/express-engine/schematics/migrations/update-9/index.js:30:24
    at /***/node_modules/@nguniversal/express-engine/schematics/migrations/update-9/index.js:19:17
    at Object.<anonymous> (/***/node_modules/@nguniversal/express-engine/schematics/migrations/update-9/index.js:25:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)

**Comment by alan-agius4** [comment]
Kindly follow the steps in the update guide to update:

https://update.angular.io/#8.0:9.0

**Comment by alan-agius4** [comment]
Closing as per above.
