### ISSUE TITLE
npm run dev:ssr generating dist-server before dist folder

### ISSUE THREAD

**Issue by MDzyga** [angular/universal#1526]
# 🐞 Bug report
### Description
I have to set global value for window & document in server.ts but dist folder is generating later than dist-server and because of it my application doesn't start.
## 🔬 Minimal Reproduction
My server.ts
```
import { APP_BASE_HREF } from '@angular/common';
import { NgxRequest, NgxResponse } from '@gorniv/ngx-universal';
import { ngExpressEngine } from '@nguniversal/express-engine';
import { REQUEST, RESPONSE } from '@nguniversal/express-engine/tokens';
import * as cookieparser from 'cookie-parser';
import * as express from 'express';
import { existsSync } from 'fs';
import { join } from 'path';
import 'zone.js/dist/zone-node';

import { AppServerModule } from './src/main.server';

const domino = require('domino');
const fs = require('fs');
const path = require('path');
const template = fs.readFileSync(path.join(__dirname, '.', 'dist', 'index.html')).toString();
const win = domino.createWindow(template);

global['window'] = win;
Object.defineProperty(win.document.body.style, 'transform', {
  value: () => {
    return {
      enumerable: true,
      configurable: true,
    };
  },
});
global['document'] = win.document;
global['CSS'] = null;
// global['XMLHttpRequest'] = require('xmlhttprequest').XMLHttpRequest;
global['Prism'] = null;

// below is generated code by Angular
```
## 🔥 Exception or Error
<pre><code>
Error: ENOENT: no such file or directory, open 'K:\Projekty\Traceabilit frontend\universal\dist-server\dist\index.html'
    at Object.openSync (fs.js:447:3)
    at Object.readFileSync (fs.js:349:35)
</code></pre>

## 🌍 Your Environment
* Angular 9
* Angular Universal 9

**Comment by alan-agius4** [comment]
Hi, from the error message I think that the following line
```ts
const template = fs.readFileSync(path.join(__dirname, '.', 'dist', 'index.html')).toString();
```

be changed to the below;
```ts
const template = fs.readFileSync(path.join(__dirname, '../dist', 'index.html')).toString();
```

If the problem persists please share the `build` section of your `angular.json`.

**Comment by MDzyga** [comment]
Hi,
The problem persists, my `build` section looks like:
```
"build": {
  "builder": "@angular-devkit/build-angular:browser",
   "options": {
      "outputPath": "dist",
      "index": "src/index.html",
      "main": "src/main.browser.ts",
      "polyfills": "src/polyfills.ts",
      "tsConfig": "tsconfig.app.json",
      "aot": true,
      "assets": [
         "src/assets",
         "src/favicon.png",
         "src/robots.txt",
         "src/manifest.json"
      ],
      "styles": [],
      "scripts": []
  },
  "configurations": {
    "dev": {
       "optimization": true,
       "outputHashing": "all",
       "sourceMap": false,
       "extractCss": true,
       "namedChunks": false,
       "extractLicenses": true,
       "vendorChunk": false,
       "buildOptimizer": true,
       "aot": true,
       "serviceWorker": true,
        "fileReplacements": [
           {
             "replace": "src/environments/environment.ts",
              "with": "src/environments/browser/environment.dev.ts"
            }
        ]
     }
  }
}
```

**Comment by MDzyga** [comment]
@alan-agius4 do you have some idea why it's generated faster than dist?

**Comment by MDzyga** [comment]
@alan-agius4 do you have some idea?

**Comment by alan-agius4** [comment]
@MDzyga, please see: https://github.com/angular/universal/issues/1518#issuecomment-589003835

**Comment by MDzyga** [comment]
thanks
