### ISSUE TITLE
I cannot deploy correctly new Angular Universal bundle in AWS Lambda

### ISSUE THREAD

**Issue by pako8x** [angular/universal#1563]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [X] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description

In the previous versions I used to install serverless and aws-serverless-express and launch build and deploy. Now I can still deploy the build, but I get an "internal server error" from the server, I do not have any information about it. What has changed since the v8?

**Comment by alan-agius4** [comment]
Unfortunately without any server logs we'll be unable to get to the bottom of this.

**Comment by pako8x** [comment]
this is my lambda.js file:
```
const awsServerlessExpress = require("aws-serverless-express");
const server = require("./dist/server");
const awsServerlessExpressMiddleware = require("aws-serverless-express/middleware");
const binaryMimeTypes = [
  "application/javascript",
  "application/json",
  "application/octet-stream",
  "application/xml",
  "image/jpeg",
  "image/png",
  "image/gif",
  "text/comma-separated-values",
  "text/css",
  "text/html",
  "text/javascript",
  "text/plain",
  "text/text",
  "text/xml",
  "image/x-icon",
  "image/svg+xml",
  "application/x-font-ttf",
  "font/ttf",
  "font/otf"
];
server.app.use(awsServerlessExpressMiddleware.eventContext());
const serverProxy = awsServerlessExpress.createServer(
  server.app,
  null,
  binaryMimeTypes
);
module.exports.handler = (event, context) =>
  awsServerlessExpress.proxy(serverProxy, event, context);
```
And this is the CloudWatch log:

```
2020-03-20T12:15:22.575Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "TypeError",
    "errorMessage": "server.app.use is not a function",
    "stack": [
        "TypeError: server.app.use is not a function",
        "    at Object.<anonymous> (/var/task/lambda.js:25:12)",
        "    at Module._compile (internal/modules/cjs/loader.js:955:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)",
        "    at Module.load (internal/modules/cjs/loader.js:811:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:723:14)",
        "    at Module.require (internal/modules/cjs/loader.js:848:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at _tryRequire (/var/runtime/UserFunction.js:75:12)",
        "    at _loadUserApp (/var/runtime/UserFunction.js:95:12)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)"
    ]
}
```
Obviously It could not work because I do not have the `server.js` file in my `./dist` folder anymore, bui i do not know how I could change my code to make it work in v9

**Comment by alan-agius4** [comment]
Instead of the `server.js` you now have a `main.js` under `dist/project/server` folder.

**Comment by pako8x** [comment]
Of course, I tried to use `const server = require("./dist/{my-project}/server/main")` instead `const server = require("./dist/server");` but it still does not work. The server log returns the same error.

**Comment by alan-agius4** [comment]
`server.app` Is a function but it’s not being invoked in the above example.

**Comment by pako8x** [comment]
Like this?
```
const awsServerlessExpress = require("aws-serverless-express");
const server = require("./dist/server/main");
const awsServerlessExpressMiddleware = require("aws-serverless-express/middleware");
const binaryMimeTypes = [
    "application/javascript",
    "application/json",
    "application/octet-stream",
    "application/xml",
    "image/jpeg",
    "image/png",
    "image/gif",
    "text/comma-separated-values",
    "text/css",
    "text/html",
    "text/javascript",
    "text/plain",
    "text/text",
    "text/xml",
    "image/x-icon",
    "image/svg+xml",
    "application/x-font-ttf",
    "font/ttf",
    "font/otf"
];
const app = server.app();
app.use(awsServerlessExpressMiddleware.eventContext());
const serverProxy = awsServerlessExpress.createServer(app, null, binaryMimeTypes);
module.exports.handler = (event, context) => awsServerlessExpress.proxy(serverProxy, event, context);
```
If so the server returns another error log:
```
2020-03-20T22:59:24.421Z	4dd4deed-1218-4dd9-ad02-ed956760ebaf	ERROR	Error: Failed to lookup view "index" in views directory "/var/task/dist/kaya-public/browser"
    at Function.render (/var/task/dist/server/main.js:1:1181072)
    at ServerResponse.render (/var/task/dist/server/main.js:1:1566165)
    at /var/task/dist/server/main.js:1:2762134
    at Layer.handle [as handle_request] (/var/task/dist/server/main.js:1:1203586)
    at next (/var/task/dist/server/main.js:1:1190024)
    at Route.dispatch (/var/task/dist/server/main.js:1:1190053)
    at Layer.handle [as handle_request] (/var/task/dist/server/main.js:1:1203586)
    at /var/task/dist/server/main.js:1:2978539
    at param (/var/task/dist/server/main.js:1:2980048)
    at param (/var/task/dist/server/main.js:1:2980455)
```

**Comment by alan-agius4** [comment]
The error is rather self explanatory `ERROR	Error: Failed to lookup view "index" in views directory "/var/task/dist/kaya-public/browser"`

This means that you are trying to load view from an incorrect directory. Please update the views path in your server.ts

**Comment by pako8x** [comment]
You're right, I lost myself in a glass of water!! ;P thank you for your time!!!
