### ISSUE TITLE
Infinite loading on new angular projects with routing + universal

### ISSUE THREAD

**Issue by joserobjr** [angular/universal#1630]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

 I don't know, I'm new to Angular.

### Description

 When you setup a new angular project with routing then add universal, run it and attempt to open an invalid page, an exception is thrown in the console and the browser keeps loading forever.

## 🔬 Minimal Reproduction

1. `ng new portal-router --routing` (selected Stylus)
2. `cd portal-router`
3. `ng serve --open`
4. Notice that the page opened successfully
5. Add `/anything/any-name` to the end of the URL and hit enter
6. Notice that you get redirected to the home page and that this happens to all undefined paths that you try to enter.
7. Ctrl+C to Kill the process
8. `ng add @nguniversal/express-engine`
9. `npm run dev:ssr`
10. Open the home page link
11. Ctrl + Shift + R to refresh the page completely without caches
12. Notice that the page works
13. Right Click -> View source and notice that the SSR is active
14. Add `/anything/any-name` to the end of the URL and hit enter
15. An error happens in the console and the browser will be stuck on loading until it gives up without response.

## 🔥 Exception or Error
<pre><code>

C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router>npm run dev:ssr

> portal-router@0.0.0 dev:ssr C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router
> ng run portal-router:serve-ssr

****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************

chunk {main} main.js, main.js.map (main) 59.6 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 141 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.css, styles.css.map (styles) 161 bytes [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 2.67 MB [initial] [rendered]
Date: 2020-04-21T01:28:11.318Z - Hash: c4d0d823f1d2a9b63b0b - Time: 12505ms
Hash: 373de26e7c051848797e
Time: 21834ms
Built at: 2020-04-20 22:28:14
      Asset      Size  Chunks                          Chunk Names
    main.js  6.42 MiB    main  [emitted]        [big]  main
main.js.map  6.96 MiB    main  [emitted] [dev]         main
Entrypoint main [big] = main.js main.js.map
chunk {main} main.js, main.js.map (main) 6.06 MiB [entry] [rendered]

Compiled successfully.
** Angular Universal Live Development Server is listening on http://localhost:4200, open your browser on http://localhost:4200 **
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'anything/any-name'
Error: Cannot match any routes. URL Segment: 'anything/any-name'
    at ApplyRedirects.noMatchError (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:102317:16)
    at CatchSubscriber.selector (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:102281:28)
    at CatchSubscriber.error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:155683:31)
    at MapSubscriber._error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152943:26)
    at MapSubscriber.error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152923:18)
    at MapSubscriber._error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152943:26)
    at MapSubscriber.error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152923:18)
    at MapSubscriber._error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152943:26)
    at MapSubscriber.error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152923:18)
    at ThrowIfEmptySubscriber._error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152943:26)
    at resolvePromise (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:168647:39)
    at resolvePromise (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:168599:21)
    at C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:168709:21
    at ZoneDelegate../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invokeTask (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:168236:35)
    at Object.onInvokeTask (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:85707:33)
    at ZoneDelegate../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invokeTask (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:168235:40)
    at Zone../node_modules/zone.js/dist/zone-node.js.Zone.runTask (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:168003:51)
    at drainMicroTaskQueue (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:168416:39)
    at ./node_modules/zone.js/dist/zone-node.js.ZoneTask.invokeTask (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:168322:25)
    at Server.ZoneTask.invoke (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:168307:52) {
  rejection: Error: Cannot match any routes. URL Segment: 'anything/any-name'
      at ApplyRedirects.noMatchError (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:102317:16)
      at CatchSubscriber.selector (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:102281:28)
      at CatchSubscriber.error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:155683:31)
      at MapSubscriber._error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152943:26)
      at MapSubscriber.error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152923:18)
      at MapSubscriber._error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152943:26)
      at MapSubscriber.error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152923:18)
      at MapSubscriber._error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152943:26)
      at MapSubscriber.error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152923:18)
      at ThrowIfEmptySubscriber._error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152943:26),
  promise: ZoneAwarePromise [Promise] {
    __zone_symbol__state: 0,
    __zone_symbol__value: Error: Cannot match any routes. URL Segment: 'anything/any-name'
        at ApplyRedirects.noMatchError (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:102317:16)
        at CatchSubscriber.selector (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:102281:28)
        at CatchSubscriber.error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:155683:31)
        at MapSubscriber._error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152943:26)
        at MapSubscriber.error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152923:18)
        at MapSubscriber._error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152943:26)
        at MapSubscriber.error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152923:18)
        at MapSubscriber._error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152943:26)
        at MapSubscriber.error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152923:18)
        at ThrowIfEmptySubscriber._error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152943:26)
  },
  zone: Zone {
    _parent: Zone {
      _parent: null,
      _name: '<root>',
      _properties: {},
      _zoneDelegate: [ZoneDelegate]
    },
    _name: 'angular',
    _properties: { isAngularZone: true, maybeDelayChangeDetection: false },
    _zoneDelegate: ZoneDelegate {
      _taskCounts: [Object],
      zone: [Circular],
      _parentDelegate: [ZoneDelegate],
      _forkZS: null,
      _forkDlgt: null,
      _forkCurrZone: null,
      _interceptZS: null,
      _interceptDlgt: null,
      _interceptCurrZone: null,
      _invokeZS: [Object],
      _invokeDlgt: [ZoneDelegate],
      _invokeCurrZone: [Circular],
      _handleErrorZS: [Object],
      _handleErrorDlgt: [ZoneDelegate],
      _handleErrorCurrZone: [Circular],
      _scheduleTaskZS: [Object],
      _scheduleTaskDlgt: [ZoneDelegate],
      _scheduleTaskCurrZone: [Circular],
      _invokeTaskZS: [Object],
      _invokeTaskDlgt: [ZoneDelegate],
      _invokeTaskCurrZone: [Circular],
      _cancelTaskZS: [Object],
      _cancelTaskDlgt: [ZoneDelegate],
      _cancelTaskCurrZone: [Circular],
      _hasTaskZS: [Object],
      _hasTaskDlgt: [ZoneDelegate],
      _hasTaskDlgtOwner: [Circular],
      _hasTaskCurrZone: [Circular]
    }
  },
  task: ZoneTask {
    _zone: Zone {
      _parent: [Zone],
      _name: 'angular',
      _properties: [Object],
      _zoneDelegate: [ZoneDelegate]
    },
    runCount: 0,
    _zoneDelegates: null,
    _state: 'notScheduled',
    type: 'microTask',
    source: 'Promise.then',
    data: ZoneAwarePromise [Promise] {
      __zone_symbol__state: 0,
      __zone_symbol__value: Error: Cannot match any routes. URL Segment: 'anything/any-name'
          at ApplyRedirects.noMatchError (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:102317:16)
          at CatchSubscriber.selector (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:102281:28)
          at CatchSubscriber.error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:155683:31)
          at MapSubscriber._error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152943:26)
          at MapSubscriber.error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152923:18)
          at MapSubscriber._error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152943:26)
          at MapSubscriber.error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152923:18)
          at MapSubscriber._error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152943:26)
          at MapSubscriber.error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152923:18)
          at ThrowIfEmptySubscriber._error (C:\Users\user.name.removed\Path\To\The\Project\Removed\portal-router\dist\portal-router\server\main.js:152943:26)
    },
    scheduleFn: undefined,
    cancelFn: undefined,
    callback: [Function],
    invoke: [Function]
  }
}
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.1.1
Node: 12.16.2
OS: win32 x64

Angular: 9.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/cli                      9.1.1
@ngtools/webpack                  9.1.1
@nguniversal/builders             9.1.0
@nguniversal/common               9.1.0
@nguniversal/express-engine       9.1.0
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by joserobjr** [comment]
I had copied the wrong command in the example. I've updated it.

**Comment by CaerusKaru** [comment]
@p3x-robot Yes, that is one solution. The other solution is to wrap the render step in a try-catch. This should allow you to catch the router issues and respond accordingly. This is not necessarily a Universal issue, it's more of a server configuration issue.
