### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by div-wynk** [angular/universal#1712]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] common
- [ ] express-engine

### Is this a regression?

Yes, the previous version in which this bug was not present was: when I used angular 6.

### Description
When I am upgrading universal to the latest versions. i am getting error while trying to run SSR.
I tried for all the methods on the net. this issue maybe because i am using hammerjs.
<pre><code>
  const domino = require("domino");
  const fs = require("fs");
  const path = require("path");
  const template = fs.readFileSync(path.join(process.cwd(), "dist", "browser", "index.html")).toString();
  // Express server
  const app = express();

  const PORT = process.env.PORT || 9000;
  const DIST_FOLDER = join(process.cwd(), "dist");

  // * NOTE :: leave this as require() since this file is built Dynamically from webpack
  const {
    AppServerModuleNgFactory,
    LAZY_MODULE_MAP
  } = require("./dist/server/main");

  app.use(express.static(join(DIST_FOLDER, "browser"), { maxAge: "1y" }));

  app.engine("html", (_, options, callback) => {
    const win = domino.createWindow(template);
      global["window"] = win;`
</code></pre>

The bug is 

ReferenceError: window is not defined

## 🔥 Exception or Error
<pre><code>
`!function(e,t){ true?module.exports=t():undefined}(window,(function(){return function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}return n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,function(t){return e[t]}.bind(null,o));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwn

ReferenceError: window is not defined
    at Object../node_modules/@otplib/preset-browser/index.js (/Users/b0212234/Desktop/wynk-music-desktop/dist/server.js:308575:52)
    at __webpack_require__ (/Users/b0212234/Desktop/wynk-music-desktop/dist/server.js:174338:30)
    at Object../src/app/shared/services/tfa.service.ts (/Users/b0212234/Desktop/wynk-music-desktop/dist/server.js:382315:26)
    at __webpack_require__ (/Users/b0212234/Desktop/wynk-music-desktop/dist/server.js:174338:30)
    at Object../src/app/shared/services/common.service.ts (/Users/b0212234/Desktop/wynk-music-desktop/dist/server.js:379869:23)
    at __webpack_require__ (/Users/b0212234/Desktop/wynk-music-desktop/dist/server.js:174338:30)
    at Object../src/app/app.component.ts (/Users/b0212234/Desktop/wynk-music-desktop/dist/server.js:354388:26)
    at __webpack_require__ (/Users/b0212234/Desktop/wynk-music-desktop/dist/server.js:174338:30)
    at Object../src/app/app.module.ts (/Users/b0212234/Desktop/wynk-music-desktop/dist/server.js:354473:25)
    at __webpack_require__ (/Users/b0212234/Desktop/wynk-music-desktop/dist/server.js:174338:30)`

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Comment by alan-agius4** [comment]
Hi, seeing the error and the module in question `@otplib/preset-browser‘ it doesn’t seem that it’s a bug. But rather the module is not meant to be used on the server.
