### ISSUE TITLE
Prerender - window is not defined

### ISSUE THREAD

**Issue by diogen737** [angular/universal#1742]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

No

### Description

I have SSR set up in my project. Now I want to prerender some of my pages.
I also have references to the `window` in my code. Rather than check the platform every time I've just put the stub in my `server.ts`:

<pre><code>
import { createWindow } from 'domino';
// ...
const template = readFileSync(join(distFolder, 'index.html')).toString();
const win = createWindow(template);
(global.window as any) = win;
global.document = win.document;
// ...
</pre></code>

And for regular dynamic server rendering this works just fine but when I try to prerender some pages an error occurs.
Am I doing something wrong?

## 🔬 Minimal Reproduction
https://github.com/diogen737/angular-prerender

<pre><code># This works
npm run build:ssr
npm run serve:ssr

# This does not
npm run prerender
npm run serve:ssr
</code></pre>

## 🔥 Exception or Error
<pre><code>
Prerendering 1 route(s) to /home/diogen/dev/web/angular-prerender/dist/angular-prerender/browser
ERROR ReferenceError: window is not defined
    at new AppComponent (/home/diogen/dev/web/angular-prerender/dist/angular-prerender/server/main.js:1:1723379)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (/home/diogen/dev/web/angular-prerender/dist/angular-prerender/server/main.js:1:1723496)
    at getNodeInjectable (/home/diogen/dev/web/angular-prerender/dist/angular-prerender/server/main.js:1:1034856)
    at instantiateRootComponent (/home/diogen/dev/web/angular-prerender/dist/angular-prerender/server/main.js:1:1199673)
    at createRootComponent (/home/diogen/dev/web/angular-prerender/dist/angular-prerender/server/main.js:1:1199864)
    at ComponentFactory$1.create (/home/diogen/dev/web/angular-prerender/dist/angular-prerender/server/main.js:1:1270314)
    at core_ApplicationRef.bootstrap (/home/diogen/dev/web/angular-prerender/dist/angular-prerender/server/main.js:1:1362811)
    at moduleRef._bootstrapComponents.forEach.f (/home/diogen/dev/web/angular-prerender/dist/angular-prerender/server/main.js:1:1359644)
    at Array.forEach (<anonymous>)
    at PlatformRef._moduleDoBootstrap (/home/diogen/dev/web/angular-prerender/dist/angular-prerender/server/main.js:1:1359626)
</code></pre>

## 🌍 Your Environment
<pre><code>
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.9
@angular-devkit/build-angular     0.901.9
@angular-devkit/build-optimizer   0.901.9
@angular-devkit/build-webpack     0.901.9
@angular-devkit/core              9.1.9
@angular-devkit/schematics        9.1.9
@angular/cli                      9.1.9
@ngtools/webpack                  9.1.9
@nguniversal/builders             9.1.1
@nguniversal/common               9.1.1
@nguniversal/express-engine       9.1.1
@schematics/angular               9.1.9
@schematics/update                0.901.9
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by alan-agius4** [comment]
Hi @diogen737, that is because you are mocking the window only for the SSR'd page. That's because the `app` method is not called during prerendering.

https://github.com/diogen737/angular-prerender/blob/0634458122ce310e1faa2d46a99b5322d8bb9b2d/server.ts#L20-L22

You'd need to patch the Window object prior to that, or opt in using dependency injection instead of access the Window global directly.

**Comment by diogen737** [comment]
@alan-agius4 makes sense, thanks a lot
