### ISSUE TITLE
ERROR ReferenceError: atob is not defined

### ISSUE THREAD

**Issue by jdforsythe** [angular/universal#1787]
<--
Please follow the below issue template. Issues not following the issue template will be closed.
Please provide _as much detail as possible_ in as minimal a reproduction as possible. This means no/only one third-party
libraries, no application-specific code, etc. Essentially, we're looking for an `ng new` project with maybe one
additional file/change. If this is not possible, please look deeper into your issue or post it to StackOverflow 
for support. This is a bug/feature tracker, meaning that something is actively _missing or broken_ in Angular Universal.
Anything else does not belong on this forum.

For very common issues when using Angular Universal, please see [this doc](docs/gotchas.md). This includes
issues for `window is not defined` and other hiccups when adopting Angular Universal for the first time.
-->

# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Unknown

### Description

 A clear and concise description of the problem...
I'm trying to use the pre-render feature as a sort of static site generator for articles in Markdown format. I have the list of articles pre-rendering properly. Due to troubles I had trying to get the pre-renderer to make calls to import .json and .md files, I am generating a TypeScript file with the article metadata using a CLI script ahead of time that gets imported into the application.

The article list pre-renders correctly, with the imported metadata ending up in the final HTML file as expected. In order to inject the markdown content into the metadata file, I base64-encoded it. In the article component, I was attempting to decode it with atob, which works in the browser but throws the `ReferenceError: atob is not defined` error during pre-rendering.

## 🔬 Minimal Reproduction

Markdown article sample:

```md
# This is a test
```

Metadata import sample:

```ts
export const articles = [{"name": "hello-world","ts":"2020-08-03 11:39:00-04","title":"Hello World","thumb":"/assets/blog/hello.jpg","markdown":"IyBUaGlzIGlzIGEgdGVzdA=="}];
```

Component (matches route param to article `name` property:

```ts
  ngOnInit() {
    this.route.params.pipe(
      // get the full article from the route param
      map((params) => this.articleService.getArticleByName(params.id)),
      take(1),
      ).subscribe((article: Article) => {
        // replace the base64-encoded markdown with decoded markdown and parse
        this.rendered = marked(atob(article.markdown));
    });
  }
```

Markup:

```html
<div [innerHTML]="rendered"></div>
```

## 🔥 Exception or Error
<pre><code>

CREATE /Users/username/testapp/dist/app/browser/news/article/thread/index.html (2907 bytes)
ERROR ReferenceError: atob is not defined
    at SafeSubscriber.route.params.pipe.subscribe.article [as _next] (/Users/username/testapp/dist/app/server/main.js:1:3295208)
    at SafeSubscriber.__tryOrUnsub (/Users/username/testapp/dist/app/server/main.js:1:1078100)
    at SafeSubscriber.next (/Users/username/testapp/dist/app/server/main.js:1:1076799)
    at Subscriber._next (/Users/username/testapp/dist/app/server/main.js:1:1075458)
    at Subscriber.next (/Users/username/testapp/dist/app/server/main.js:1:1075220)
    at TakeSubscriber._next (/Users/username/testapp/dist/app/server/main.js:1:1309268)
    at TakeSubscriber.next (/Users/username/testapp/dist/app/server/main.js:1:1075220)
    at MapSubscriber._next (/Users/username/testapp/dist/app/server/main.js:1:2800907)
    at MapSubscriber.next (/Users/username/testapp/dist/app/server/main.js:1:1075220)
    at SwitchMapSubscriber.notifyNext (/Users/username/testapp/dist/app/server/main.js:1:1884561)
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.1.12
Node: 10.15.3
OS: darwin x64

Angular: 9.1.12
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/animations               10.0.7
@ngtools/webpack                  9.1.12
@nguniversal/builders             9.1.1
@nguniversal/common               9.1.1
@nguniversal/express-engine       9.1.1
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Comment by jdforsythe** [comment]
I realize now this is part of the `window` missing globals issue. BTW the link to "this doc" in the issue template is broken. It points to /issues/docs instead of /docs
