### ISSUE TITLE
Ability to debug prerender

### ISSUE THREAD

**Issue by initplatform** [angular/universal#1844]
# 🚀 Feature request

First off, I absolutely love the ability to prerender. It is one of the most valuable features of Angular, especially for larger projects. You get the power of the Angular framework but the ability to deliver a fast, compact initial page load throughout the entire web app. 

My biggest issue, though, is that it's like black magic trying to debug any issues with the rendering.. I render out almost 100 routes, and occasionally I see errors like this...

```
ERROR NetworkError
    at XMLHttpRequest.send (/Users/sam/Projects/SB/website-angular/dist/website-angular/server/main.js:1:5437164)
    at Observable_Observable._subscribe (/Users/sam/Projects/SB/website-angular/dist/website-angular/server/main.js:1:4770726)
    at Observable_Observable._trySubscribe (/Users/sam/Projects/SB/website-angular/dist/website-angular/server/main.js:1:4697970)
    at Observable_Observable.subscribe (/Users/sam/Projects/SB/website-angular/dist/website-angular/server/main.js:1:4697752)
    at CatchOperator.call (/Users/sam/Projects/SB/website-angular/dist/website-angular/server/main.js:1:4794209)
    at Observable_Observable.subscribe (/Users/sam/Projects/SB/website-angular/dist/website-angular/server/main.js:1:4697606)
    at /Users/sam/Projects/SB/website-angular/dist/website-angular/server/main.js:1:10134803
    at Observable_Observable._subscribe (/Users/sam/Projects/SB/website-angular/dist/website-angular/server/main.js:1:10135148)
    at Observable_Observable._trySubscribe (/Users/sam/Projects/SB/website-angular/dist/website-angular/server/main.js:1:4697970)
    at Observable_Observable.subscribe (/Users/sam/Projects/SB/website-angular/dist/website-angular/server/main.js:1:4697752)
```

There are 2 major problems with this error.

1) I don't know what route caused it. It's being thrown asynchronously, so I can't determine the route based on the position in the log.

2) I'm building the app and server with sourceMaps, but errors don't appear to be able to leverage those. Since it's telling me the error occurred at `main.js:1:5437164`

Being able to catch these errors and wrap them somehow in an error message that tells me which route they came from would help with issue 1. 

For issue, 2, seeing the actual stack traces would be great.

It would also be great if I could run this in the debugger and step through the code. 

I've tried running the server on my own with something like

```
ts-node -P ./tsconfig.server.json -r tsconfig-paths/register -r dotenv/config server.ts
```

I'm fairly expert at TypeScript, but even I had to call it quits trying to get that to work.

I did search through the issues and googled many times for answers to these questions, so I apologize if I missed something that answers it already. 

All the best!

#### What modules are relevant for this feature request?

- [ ] aspnetcore-engine
- [] builders
- [x] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description
 A clear and concise description of the problem or missing capability...

Ability to debug prerendering runs (Detailed above)

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

I am able to prerender my site, but it took a lot of black box programming which is slow and painful.

- add some console.logs()
- recompile everything
- run the prerender
- pull my hair out
- make some guesses
- repeat

Now that I have everything set, when I have issues I just assume it was the last feature I added and go from there.

**Comment by alan-agius4** [comment]
Hi, 

Thanks for the feedback.

To debug I suggest you use https://github.com/GoogleChromeLabs/ndb which offers better DX for async debugging or at the very minimum node inspector.

Unlike browsers Sourcemaps will not be loaded automatically in Node.Js, you can use: https://www.npmjs.com/package/source-map-support to load them. (Probably we can load them internally though using this same
API).

Re the error message I do agree that we should print out the route that was being rendered when the error occurred.
