### ISSUE TITLE
stylePreprocessorOptions doesn't work in SSR serve mode.

### ISSUE THREAD

**Issue by maximelafarie** [angular/universal#2035]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [X] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine

### Is this a regression?

Idk.

### Description

While serving my project with `ng serve` there is no error.

While serving my project with `npm run dev:ssr`, there is errors related to `stylePreprocessorOptions`.

## 🔬 Minimal Reproduction

1. Create a project 
2. Add the Angular Universal schematic
3. Add a folder containing `.scss` files in the `src` folder (e.g.: `helper.scss`)
4. Add this in `angular.json` config file:
```json
"stylePreprocessorOptions": {
  "includePaths": [
    "src/scss"
  ]
},
```
5. Try to import `helpers.scss` directly with `@import 'helpers';` and not `@import 'src/styles/helpers'`
6. Launch the project with `ng serve` (it should work)
7. Launch the project with `npm run dev:ssr` (it should crash)

## 🔥 Exception or Error
Result with `ng serve`:
```
✔ Browser application bundle generation complete.

Initial Chunk Files | Names         |      Size
vendor.js           | vendor        |   3.33 MB
polyfills.js        | polyfills     | 128.75 kB
main.js             | main          | 113.59 kB
styles.css          | styles        |  13.35 kB
runtime.js          | runtime       |   6.15 kB

                    | Initial Total |   3.58 MB

Build at: 2021-03-26T15:09:36.253Z - Hash: d304d52f008b1093136c - Time: 8801ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


✔ Compiled successfully.
```

Result with `npm run dev:ssr`
```
> ng-site@0.0.0 dev:ssr
> ng run ng-site:serve-ssr

****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/core : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @nguniversal/express-engine/tokens : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @fortawesome/angular-fontawesome : es2015 as esm2015
Compiling @angular/platform-server : es2015 as esm2015
Compiling @nguniversal/common/engine : es2015 as esm2015
Compiling @nguniversal/express-engine : es2015 as esm2015
✔ Browser application bundle generation complete.
✔ Index html generation complete.

Initial Chunk Files | Names         |      Size
vendor.js           | vendor        |   2.99 MB
polyfills.js        | polyfills     | 128.75 kB
main.js             | main          | 112.46 kB
styles.css          | styles        |  13.35 kB
runtime.js          | runtime       |   6.15 kB

                    | Initial Total |   3.25 MB

Build at: 2021-03-26T15:09:15.167Z - Hash: 97b5e9defb256e81aa23 - Time: 14683ms
✔ Server application bundle generation complete.

Initial Chunk Files | Names         |    Size
main.js             | main          | 7.29 MB

                    | Initial Total | 7.29 MB

Build at: 2021-03-26T15:09:16.540Z - Hash: bd30caf4a139dda11f07 - Time: 38906ms

Error: ./src/app/home/home.component.scss
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @import "_helpers";
  │         ^^^^^^^^^^
  ╵
  src/app/home/home.component.scss 1:9  root stylesheet
SassError: SassError: Can't find stylesheet to import.
  ╷
1 │ @import "_helpers";
  │         ^^^^^^^^^^
  ╵
  src/app/home/home.component.scss 1:9  root stylesheet
    at /blahblah/ng-site/node_modules/sass-loader/dist/index.js:62:16
    at Function.call$2 (/blahblah/ng-site/node_modules/sass/sass.dart.js:91135:16)
    at _render_closure1.call$2 (/blahblah/ng-site/node_modules/sass/sass.dart.js:80011:12)
    at _RootZone.runBinary$3$3 (/blahblah/ng-site/node_modules/sass/sass.dart.js:27197:18)
    at _FutureListener.handleError$1 (/blahblah/ng-site/node_modules/sass/sass.dart.js:25725:19)
    at _Future__propagateToListeners_handleError.call$0 (/blahblah/ng-site/node_modules/sass/sass.dart.js:26022:49)
    at Object._Future__propagateToListeners (/blahblah/ng-site/node_modules/sass/sass.dart.js:4543:77)
    at _Future._completeError$2 (/blahblah/ng-site/node_modules/sass/sass.dart.js:25855:9)
    at _AsyncAwaitCompleter.completeError$2 (/blahblah/ng-site/node_modules/sass/sass.dart.js:25198:12)
    at Object._asyncRethrow (/blahblah/ng-site/node_modules/sass/sass.dart.js:4292:17)
    at /blahblah/ng-site/node_modules/sass/sass.dart.js:13200:20
    at _wrapJsFunctionForAsync_closure.$protected (/blahblah/ng-site/node_modules/sass/sass.dart.js:4317:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/blahblah/ng-site/node_modules/sass/sass.dart.js:25219:12)
    at _awaitOnObject_closure0.call$2 (/blahblah/ng-site/node_modules/sass/sass.dart.js:25211:25)
    at _RootZone.runBinary$3$3 (/blahblah/ng-site/node_modules/sass/sass.dart.js:27197:18)
    at _FutureListener.handleError$1 (/blahblah/ng-site/node_modules/sass/sass.dart.js:25725:19)


this.debug is not a function
```

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.2.6
Node: 14.12.0
OS: darwin x64

Angular: 11.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.6
@angular-devkit/build-angular   0.1102.6
@angular-devkit/core            11.2.6
@angular-devkit/schematics      11.2.6
@angular/cli                    11.2.6
@nguniversal/builders           11.2.1
@nguniversal/express-engine     11.2.1
@schematics/angular             11.2.6
@schematics/update              0.1102.6
rxjs                            6.6.6
typescript                      4.1.5
</code></pre>

**Comment by alan-agius4** [comment]
Are you adding `stylePreprocessorOptions` to both browser and server builders?

**Comment by maximelafarie** [comment]
This is it! I didn't put it into server builder. It would be nice to add this somewhere in the docs btw.
Thanks you @alan-agius4 🖖
