### ISSUE TITLE
Error: Can't set headers after they are sent

### ISSUE THREAD

**Issue by GlauberF** [angular/universal#2065]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

### Description

After making the build, when uploading the server and making the first call in the browser, the issue title error appears on the console.

## 🔥 Exception or Error
```
index:  /var/www/html/pwa_vimbo/dist/browser/index.html
Node Express server listening on http://localhost:4000
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/var/www/html/pwa_vimbo/dist/server/main.js:1937:1299625)
    at SendStream.send (/var/www/html/pwa_vimbo/dist/server/main.js:1937:1302716)
    at onstat (/var/www/html/pwa_vimbo/dist/server/main.js:1937:1304416)
    at ZoneDelegate.invokeTask (/var/www/html/pwa_vimbo/dist/server/main.js:1881:994280)
    at Zone.runTask (/var/www/html/pwa_vimbo/dist/server/main.js:1881:986845)
    at ZoneTask.invokeTask (/var/www/html/pwa_vimbo/dist/server/main.js:1881:995865)
    at ZoneTask.options.useG.invoke (/var/www/html/pwa_vimbo/dist/server/main.js:1881:995694)
    at data.args.<computed> (/var/www/html/pwa_vimbo/dist/server/main.js:1881:1004989)
    at FSReqCallback.oncomplete (fs.js:184:5)

```

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.2.9
Node: 14.16.1
OS: linux x64

Angular: 11.2.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1102.9
@angular-devkit/build-angular      0.1102.9
@angular-devkit/build-optimizer    0.1101.4
@angular-devkit/core               11.2.9
@angular-devkit/schematics         11.2.9
@angular/cdk                       11.2.9
@angular/cli                       11.2.9
@angular/flex-layout               11.0.0-beta.33
@angular/material                  11.2.9
@angular/material-moment-adapter   11.2.9
@nguniversal/builders              11.2.1
@nguniversal/express-engine        11.2.1
@schematics/angular                11.2.9
@schematics/update                 0.1102.9
rxjs                               6.6.7
typescript                         4.1.5
</code></pre>

**Comment by CaerusKaru** [comment]
We don't set headers in the Universal framework. The issue must lie in your own implementation somewhere, or another third-party library.
