### ISSUE TITLE
An unhandled exception occurred: Could not find the main bundle

### ISSUE THREAD

**Issue by kuncevic** [angular/universal#2159]
# 🐞 Bug report

#### What modules are related to this issue?

- [x ] builders
- [x ] express-engine

### Is this a regression?

nope

### Description

Just upgraded from v11 to v12. `ng serve` works however prerendering does not.

## 🔬 Minimal Reproduction

After I did run the update command `ng update @angular/cdk @angular/cli @angular/core @angular/material @nguniversal/express-engine @angular/flex-layout  --force` that are my dependencies:

```
"dependencies": {
    "@angular/animations": "~12.0.3",
    "@angular/cdk": "~12.0.3",
    "@angular/common": "~12.0.3",
    "@angular/compiler": "~12.0.3",
    "@angular/core": "~12.0.3",
    "@angular/flex-layout": "12.0.0-beta.34",
    "@angular/forms": "~12.0.3",
    "@angular/material": "~12.0.3",
    "@angular/platform-browser": "~12.0.3",
    "@angular/platform-browser-dynamic": "~12.0.3",
    "@angular/platform-server": "~12.0.3",
    "@angular/router": "~12.0.3",
    "@ng-toolkit/universal": "^8.1.0",
    "@nguniversal/express-engine": "^12.0.1",
    "@types/stripe-v3": "^3.1.23",
    "express": "^4.17.1",
    "ng-recaptcha": "^7.0.1",
    "ngx-cookie": "^5.0.0",
    "ngx-cookie-backend": "^5.0.0",
    "perfect-scrollbar": "^1.5.0",
    "rx-service": "^0.1.0",
    "rxjs": "~6.6.6",
    "tslib": "^2.1.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.0.3",
    "@angular-devkit/build-ng-packagr": "~0.1002.0",
    "@angular/cli": "~12.0.3",
    "@angular/compiler-cli": "~12.0.3",
    "@nguniversal/builders": "^12.0.1",
    "@types/express": "4.17.11",
    "@types/jasmine": "~3.6.4",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "14.14.31",
    "codelyzer": "^6.0.1",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~6.0.0",
    "karma": "~6.3.3",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.1",
    "karma-jasmine-html-reporter": "^1.5.0",
    "ng-packagr": "^12.0.3",
    "protractor": "~7.0.0",
    "ts-node": "~9.1.1",
    "tslint": "~6.1.3",
    "typescript": "~4.2.4"
  }
```
server config(didn't change anything here) :
```
{
  "extends": "./tsconfig.app.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/server",
    "target": "es2016",
    "types": [
      "node",
      "stripe-v3"
    ]
  },
  "files": [
    "../shared-library/src/index.ts",
    "src/main.server.ts",
    "server.ts"
  ],
  "angularCompilerOptions": {
    "entryModule": "./src/app/app.server.module#AppServerModule"
  }
}
```

After the failure I did remove `node_modules` and `yarn.lock` and run prerendering again, but it does not help

## 🔥 Exception or Error
```
[error] Error: Could not find the main bundle: /Volumes/Work/Work/Projects/angular-monorepo_/dist/personal/server/main.js
    at /Volumes/Work/Work/Projects/angular-monorepo_/node_modules/@nguniversal/builders/src/prerender/index.js:102:27
    at Generator.next (<anonymous>)
    at fulfilled (/Volumes/Work/Work/Projects/angular-monorepo_/node_modules/@nguniversal/builders/src/prerender/index.js:11:58)

```

## 🌍 Your Environment

```
Angular CLI: 12.0.3
Node: 14.17.0
Package Manager: yarn 1.22.10
OS: darwin x64

Angular: 12.0.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1200.3
@angular-devkit/build-angular      12.0.3
@angular-devkit/build-ng-packagr   0.1002.0
@angular-devkit/core               12.0.3
@angular-devkit/schematics         8.3.29
@angular/flex-layout               12.0.0-beta.34
@nguniversal/builders              12.0.1
@nguniversal/express-engine        12.0.1
@schematics/angular                8.3.29
ng-packagr                         12.0.3
rxjs                               6.6.6
typescript                         4.2.4
```

**Comment by alan-agius4** [comment]
@kuncevic, Is there a way to provide a reproduction? `Could not find the main bundle` typically means that something went terribly wrong during the server build.

**Comment by alan-agius4** [comment]
Stored this out on slack.
