### ISSUE TITLE
Error: You must pass in a NgModule or NgModuleFactory to be bootstrapped

### ISSUE THREAD

**Issue by shaklin-box8** [angular/universal#2172]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Version 8

### Description

 A clear and concise description of the problem...
The local build and server build works ie. compiles fine, but when i run node dist/server.js i get the following error

```
Error: You must pass in a NgModule or NgModuleFactory to be bootstrapped
    at View.engine (/Users/shaklin/Documents/<project>/dist/server.js:79769:23)
    at View.render (/Users/shaklin/Documents/<project>/dist/server.js:17442:8)
    at tryRender (/Users/shaklin/Documents/<project>/dist/server.js:13478:10)
    at Function.render (/Users/shaklin/Documents/<project>/dist/server.js:13430:3)
    at /Users/shaklin/Documents/<project>/dist/server.js:200397:35
    at new ZoneAwarePromise (/Users/shaklin/Documents/<project>/dist/server.js:1394:29)
    at AppController.<anonymous> (/Users/shaklin/Documents/<project>/dist/server.js:200396:39)
    at step (/Users/shaklin/Documents/<project>/dist/server.js:200129:23)
    at Object.next (/Users/shaklin/Documents/<project>/dist/server.js:200110:53)
    at /Users/shaklin/Documents/<project>/dist/server.js:200104:71
```

So initially i browsed for a few post and figured that i need to replace ```AppServerModuleNgFactory``` with ```AppServerModule```

and then i started getting the following error.

```
Error: No NgModule metadata found for 'AppServerModule'.
    at NgModuleResolver.resolve (/Users/shaklin/Documents/<project>/dist/server.js:114898:23)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/shaklin/Documents/<project>/dist/server.js:114008:45)
    at JitCompiler._loadModules (/Users/shaklin/Documents/<project>/dist/server.js:119838:53)
    at JitCompiler._compileModuleAndComponents (/Users/shaklin/Documents/<project>/dist/server.js:119821:36)
    at JitCompiler.compileModuleAsync (/Users/shaklin/Documents/<project>/dist/server.js:119781:37)
    at CompilerImpl.compileModuleAsync (/Users/shaklin/Documents/<project>/dist/server.js:180482:31)
    at CommonEngine.<anonymous> (/Users/shaklin/Documents/<project>/dist/server.js:90346:58)
    at Generator.next (<anonymous>)
    at /Users/shaklin/Documents/<project>/dist/server.js:137474:71
    at new ZoneAwarePromise (/Users/shaklin/Documents/<project>/dist/server.js:1394:29)
```

I had updated from version 8 to 12. I also tried running ```ng update @nguniversal/express-engine``` but that didn't yield any output. 

any clues on how to fix would be great.

## 🔬 Minimal Reproduction

Unable to reproduce

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.0.2
Node: 14.17.0
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 12.0.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.1200.2
@angular-devkit/build-angular              12.0.2
@angular-devkit/core                       12.0.4
@angular-devkit/schematics                 12.0.2
@angular/fire                              6.1.5
@nguniversal/express-engine                12.0.1
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        12.0.2
rxjs                                       6.6.7
typescript                                 4.2.4
webpack                                    5.36.2

</code></pre>

**Comment by alan-agius4** [comment]
Can you run the following;

```
ng update @nguniversal/express-engine@10
ng update @nguniversal/express-engine@latest
```

Typically it's not recommended to update multiply major versions at once.

**Comment by shaklin-box8** [comment]
@alan-agius4 I had updated one version at a time, and tried running both commands didn't yield any changes

**Comment by alan-agius4** [comment]
In that case please share your `server.ts`?

**Comment by shaklin-box8** [comment]
@alan-agius4 i would love to share but the whole `server.ts` is broken into multiple files across multiple controllers, can you let me know what exactly is that you are looking for so that i could share the specifics.

**Comment by shaklin-box8** [comment]
> Can you run the following;
> 
> ```
> ng update @nguniversal/express-engine@10
> ng update @nguniversal/express-engine@latest
> ```
> 
> Typically it's not recommended to update multiply major versions at once.

Also was curious to know what is that we were expecting from this update commands

**Comment by shaklin-box8** [comment]
```ng add @nguniversal/express-engine --project=project_name``` Fixed the issue.
