### ISSUE TITLE
The target entry-point "@nguniversal/express-engine" has missing dependencies:  - @nguniversal/common/engine

### ISSUE THREAD

**Issue by semla** [angular/universal#2240]
I am trying to update @angular packages from 12.1.0 to 12.2.1 for cdk, cli, core, maps, material. Updating gives no error, but cant build after updating:

> @nguniversal/express-engine" has missing dependencies: - u/nguniversal/common/engine

Been trying with releases since 12.1.1

The more elaborate message:

```
[error] Error: The target entry-point "@nguniversal/express-engine" has missing dependencies:
 - @nguniversal/common/engine

    at TargetedEntryPointFinder.findEntryPoints (/home/user/project/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/targeted_entry_point_finder.js:40:23)
    at /home/user/project/node_modules/@angular/compiler-cli/ngcc/src/execution/analyze_entry_points.js:29:41
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (/home/user/project/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:28:29)
    at /home/user/project/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:57:59
    at SyncLocker.lock (/home/user/project/node_modules/@angular/compiler-cli/ngcc/src/locking/sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (/home/user/project/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:57:27)
    at Object.mainNgcc (/home/user/project/node_modules/@angular/compiler-cli/ngcc/src/main.js:74:25)
    at Object.process (/home/user/project/node_modules/@angular/compiler-cli/ngcc/index.js:29:23)
    at NgccProcessor.processModule (/home/user/project/node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ngcc_processor.js:175:16)
    at /home/user/project/node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/host.js:146:18
    at /home/user/project/node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/host.js:76:24
    at Array.map (<anonymous>)
    at Object.host.resolveModuleNames (/home/user/project/node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/host.js:74:32)
    at actualResolveModuleNamesWorker (/home/user/project/node_modules/typescript/lib/typescript.js:106560:133)
    at resolveModuleNamesWorker (/home/user/project/node_modules/typescript/lib/typescript.js:106810:26)
    at resolveModuleNamesReusingOldState (/home/user/project/node_modules/typescript/lib/typescript.js:106907:24)

```

package.json:

```  "private": true,
  "dependencies": {
    "@angular/animations": "^12.2.1",
    "@angular/cdk": "^12.2.1",
    "@angular/common": "^12.2.1",
    "@angular/compiler": "^12.2.1",
    "@angular/core": "^12.2.1",
    "@angular/forms": "^12.2.1",
    "@angular/google-maps": "^12.2.1",
    "@angular/localize": "^12.2.1",
    "@angular/material": "^12.2.1",
    "@angular/platform-browser": "^12.2.1",
    "@angular/platform-browser-dynamic": "^12.2.1",
    "@angular/platform-server": "^12.2.1",
    "@angular/router": "^12.2.1",
    "@angular/service-worker": "^12.2.1",
    "@nguniversal/express-engine": "^12.1.0",
    "@types/googlemaps": "^3.43.3",
    "@types/request": "^2.48.5",
    "@types/string-similarity": "^3.0.0",
    "core-js": "^3.6.5",
    "geojson": "^0.5.0",
    "geojson-extent": "^0.3.2",
    "rxjs": "^6.6.7",
    "string-similarity": "^4.0.2",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^12.2.1",
    "@angular/cli": "^12.2.1",
    "@angular/compiler-cli": "^12.2.1",
    "@compodoc/compodoc": "^1.1.11",
    "@cypress/schematic": "^1.5.0",
    "@nguniversal/builders": "^12.1.0",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^13.13.10",
    "codelyzer": "^6.0.0",
    "eslint": "^7.10.0",
    "fs": "0.0.1-security",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-cli": "~2.0.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "ng-packagr": "^12.0.2",
    "protractor": "~7.0.0",
    "run-middleware": "^0.9.10",
    "source-map-explorer": "^2.4.2",
    "ts-node": "^8.10.2",
    "typescript": "4.2.4",
    "webpack": "^4.43.0",
    "webpack-bundle-analyzer": "^3.8.0",
    "cypress": "8.1.0"
  }
```

**Comment by semla** [comment]
`npm install @nguniversal/common --save`
Was sure I tried it before, but now working
