### ISSUE TITLE
Hello, any more information about clover engine?

### ISSUE THREAD

**Issue by hiepxanh** [angular/universal#2547]
Sorry for not following the issue template, I just wonder when clover is official release? why it not coming officially? 
I dont see any example, documentation, and roadmap for this. is it going to use or is despricated?

**Comment by hiepxanh** [comment]
![image](https://user-images.githubusercontent.com/16970990/155995913-60a1c02b-89b9-441c-b161-fcb98a9f2b77.png)
clover engine error

**Comment by hiepxanh** [comment]
it seem understandable why clover not expose. it basicly unable to use on realistic. I'm having websocket and few bundle and it is imposible to build. 

begin with: 

```

Build at: 2022-02-28T14:09:48.936Z - Hash: b0d5fb188d4ae08f - Time: 107827ms

./node_modules/.pnpm/ws@8.4.0/node_modules/ws/lib/buffer-util.js:103:21-42 - Warning: Module not found: Error: Can't resolve 'bufferutil' in 'G:\small-cosmos\awread\node_modules\.pnpm\ws@8.4.0\node_modules\ws\lib'

./node_modules/.pnpm/ws@8.4.0/node_modules/ws/lib/validation.js:109:22-47 - Warning: Module not found: Error: Can't resolve 'utf-8-validate' in 'G:\small-cosmos\awread\node_modules\.pnpm\ws@8.4.0\node_modules\ws\lib'



./node_modules/.pnpm/jsdom@19.0.0/node_modules/jsdom/lib/jsdom/utils.js:154:2-27 - Error: Module not found: Error: Can't resolve 'canvas' in 'G:\small-cosmos\awread\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom'


```

trying to solve problem with adding exteralDependencies in angular.json > server > options
```
"externalDependencies": ["utf-8-validate", "bufferutil", "canvas", "data-urls", "whatwg-url"]
```
and still got error, no matter I debug. It just unable to skip this error
![image](https://user-images.githubusercontent.com/16970990/156004697-027c9ca2-7348-4fc8-99c0-552be7317676.png)
```
Build at: 2022-02-28T14:54:10.971Z - Hash: d4d65b15c2d65fc1 - Time: 104081ms
✔ Browser application bundle generation complete.
✔ Index html generation complete.

78 unchanged chunks

Build at: 2022-02-28T14:54:15.224Z - Hash: d4d65b15c2d65fc1 - Time: 7869ms
✔ Server application bundle generation complete.

Initial Chunk Files | Names         |  Raw Size
main.js             | main          |  23.22 MB | 

                    | Initial Total |  23.22 MB

Lazy Chunk Files    | Names         |  Raw Size
484.js              | quill         | 434.04 kB | 

const AsyncIteratorPrototype = Object.getPrototypeOf(Object.getPrototypeOf( /*#__PURE__*/_wrapAsyncGenerator(function* () {})).prototype);
                                      ^

TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at Object.10079 (G:\small-cosmos\awread\dist\apps\reader\server\main.js:307982:39)
    at __webpack_require__ (G:\small-cosmos\awread\dist\apps\reader\server\main.js:606459:42)
    at Object.36994 (G:\small-cosmos\awread\dist\apps\reader\server\main.js:235581:18)
    at __webpack_require__ (G:\small-cosmos\awread\dist\apps\reader\server\main.js:606459:42)
    at Module.31663 (G:\small-cosmos\awread\dist\apps\reader\server\main.js:559647:63)
    at __webpack_require__ (G:\small-cosmos\awread\dist\apps\reader\server\main.js:606459:42)
    at Object.34742 (G:\small-cosmos\awread\dist\apps\reader\server\main.js:16:18)
    at __webpack_require__ (G:\small-cosmos\awread\dist\apps\reader\server\main.js:606459:42)
    at G:\small-cosmos\awread\dist\apps\reader\server\main.js:606634:37

A server error has occurred.
node exited with 1 code.
connect ECONNREFUSED 127.0.0.1:64321
 ERROR  Command failed with exit code 1.
 ```
 
 I belive it will be good in the future. basicly it have a lot of potential. Just need alitte update. Angular Express Engine used to have this error before but already resolve it as I remember since 2019

**Comment by hiepxanh** [comment]
p/s: update change it to:

```

  server.get('*', (req, res, next) => {
    ssr
      .render({
        publicPath: distFolder,
        url:  `${req.protocol}://${req.get('host')}${req.originalUrl}`,
        headers: req.headers,
      })
      .then((html) => res.send(html))
      .catch((err) => next(err));
  });

```

and `angular.json` ```  "externalDependencies": ["jsdom", "canvas"] ```
solved the problem

**Comment by jitterbox** [comment]
After updating our project to Angular 14 to utilize Clover SSR in our project (with .NET back end), and following the Clover readme, we get errors seemingly from **jsdom**: `SyntaxError: Invalid or unexpected token`. It seems like maybe a UTF-8 decoding issue when it attempts to load vendor.js(?). We've followed the guidance around **externalDependencies** and **server.ts** edits. Any ideas on how to solve this?

```
Iconv-lite warning: decode()-ing strings is deprecated. Refer to https://github.com/ashtuchkin/iconv-lite/wiki/Use-Buffers-when-decoding

Error: Uncaught [SyntaxError: Invalid or unexpected token]
    at reportException (D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:66:24)
    at processJavaScript (D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:243:7)
    at HTMLScriptElementImpl._innerEval (D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:176:5)
    at onLoadExternalScript (D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:98:12)
    at onLoadWrapped (D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\node_modules\jsdom\lib\jsdom\browser\resources\per-document-resource-loader.js:53:33)
    at Object.check (D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:76:23)
    at D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:119:14
    at _ZoneDelegate.invoke (D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\dist\ClientApp\server\main.js:109363:158)
    at Zone.run (D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\dist\ClientApp\server\main.js:109104:35)
    at D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\dist\ClientApp\server\main.js:110371:28 http://localhost:61072/vendor.js:39324
  **"CZK": [undefined, "K
                     ^^**
```
