### ISSUE TITLE
[Clover] build then run work fine, but dev:ssr get encoding error on angular currency

### ISSUE THREAD

**Issue by hiepxanh** [angular/universal#2639]
# 🐞 Bug report

#### What modules are related to this issue?
- [x] common

### Is this a regression?
no
### Description

fresh angular, if you add currency pipe 

```

<p>A: {{a | currency}}</p>

<!--output 'CA$0.26'-->
<p>A: {{a | currency:'CAD'}}</p>

<!--output 'CAD0.26'-->
<p>A: {{a | currency:'CAD':'code'}}</p>

<!--output 'CA$0,001.35'-->
<p>B: {{b | currency:'CAD':'symbol':'4.2-2'}}</p>

<!--output '$0,001.35'-->
<p>B: {{b | currency:'CAD':'symbol-narrow':'4.2-2'}}</p>

<!--output 'CLP1' because CLP has no cents-->
<p>B: {{b | currency:'CLP'}}</p>

<p>B: {{b | currency:'CZK'}}</p>

```

it start getting this error on clover.

I track it down, look like some problem cause from angular encoding file make jsdom cannot parse it.

![image](https://user-images.githubusercontent.com/16970990/167111166-d7b3185f-5eec-4f18-b77b-bc15a8283787.png)

open vendor file it look like utf-8 not parse correctly, I dont know from jsdom or angular. tried to tweak all jsdom setting but still the same error. I really need your help. 
I already dig for 8 hours on this issue. still no clue 

![image](https://user-images.githubusercontent.com/16970990/167111320-501dac68-caaa-4779-8fc1-f8904085fcd1.png)

already check this issue from jsdom
https://github.com/jsdom/jsdom/issues/2766
not related.

tried to add utf-8 on here. still nothing. I got repo below
![image](https://user-images.githubusercontent.com/16970990/167111662-4d56bd8e-8426-4a50-9125-24e313c0c476.png)

## 🔬 Minimal Reproduction

``` pnpm start-error ``` or ``` npm run start-error ``` because I included dist folder. if you prefer rebuild: 
![image](https://user-images.githubusercontent.com/16970990/167111815-7a3a2a15-1cfb-420a-a628-fa29b8ede6ed.png)

https://github.com/hiepxanh/clover-error

## 🔥 Exception or Error

<pre><code>
 "CZK": [undefined, "K
                     ^^

SyntaxError: Invalid or unexpected token
    at new Script (node:vm:100:7)
    at createScript (node:vm:257:10)
    at Object.runInContext (node:vm:288:10)
    at processJavaScript (G:\test\test3\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:242:10)
    at HTMLScriptElementImpl._innerEval (G:\test\test3\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:176:5)
    at onLoadExternalScript (G:\test\test3\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:98:12)
    at onLoadWrapped (G:\test\test3\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom\browser\resources\per-document-resource-loader.js:53:33)
    at Object.check (G:\test\test3\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:76:23)
    at G:\test\test3\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:119:14
Error: Uncaught [SyntaxError: Invalid or unexpected token]
    at reportException (G:\test\test3\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:68:24)
    at processJavaScript (G:\test\test3\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:244:7)
    at HTMLScriptElementImpl._innerEval (G:\test\test3\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:176:5)
    at onLoadExternalScript (G:\test\test3\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:98:12)
    at onLoadWrapped (G:\test\test3\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom\browser\resources\per-document-resource-loader.js:53:33)
    at Object.check (G:\test\test3\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:76:23)
    at G:\test\test3\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:119:14 http://localhost:8080/vendor.js:4490
  "CZK": [undefined, "K
                     ^^

SyntaxError: Invalid or unexpected token
    at new Script (node:vm:100:7)
    at createScript (node:vm:257:10)
    at Object.runInContext (node:vm:288:10)
    at processJavaScript (G:\test\test3\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:242:10)
    at HTMLScriptElementImpl._innerEval (G:\test\test3\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:176:5)
    at onLoadExternalScript (G:\test\test3\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:98:12)
    at onLoadWrapped (G:\test\test3\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom\browser\resources\per-document-resource-loader.js:53:33)
    at Object.check (G:\test\test3\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:76:23)
    at G:\test\test3\node_modules\.pnpm\jsdom@19.0.0\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:119:14
G:\test\test3\dist\server\main.js:44903
          throw new Error('Angular application failed to stablize after in time.');
          ^

Error: Angular application failed to stablize after in time.
    at Timeout._onTimeout (G:\test\test3\dist\server\main.js:44903:17)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.3.5
Node: 16.13.1
Package Manager: pnpm 7.0.0
OS: win32 x64

Angular: 13.3.6
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.6
@angular-devkit/build-angular   13.3.5
@angular-devkit/core            13.2.6
@angular-devkit/schematics      13.2.6
@angular/cli                    13.3.5
@nguniversal/common             13.1.1
@schematics/angular             13.2.6
rxjs                            7.5.5
typescript                      4.5.5
webpack                         5.72.0

</code></pre>

**Comment by hiepxanh** [comment]
update: the same code, upgrade to standalone component with angular 14 work correctly lol, I dont know the root of problem but  we can close this issue if you like @alan-agius4  😄
