### ISSUE TITLE
Angular 12 SSR Build Serve eror -- ERROR ReferenceError: document is not defined

### ISSUE THREAD

**Issue by ergaibiYasin** [angular/universal#2692]
# 🐞 Bug report
- [ x ] express-engine

### Description

I have followed the guide on [](https://angular.io/guide/universal) in order to render my Angular application on the server, but when I run npm run dev:ssr I get this error

<pre><code>
C:\Users\Yasin\WebstormProjects\project\dist\project\server\main.js:266288
      document.webL10n = function (window, document, undefined) {
      ^

ReferenceError: document is not defined
    at Object.<anonymous> (C:\Users\Yasin\WebstormProjects\project\dist\project\server\main.js:262849:27)
    at Object.<anonymous> (C:\Users\Yasin\WebstormProjects\project\dist\project\server\main.js:266074:7)
    at __w_pdfjs_require__ (C:\Users\Yasin\WebstormProjects\project\dist\project\server\main.js:262849:27)
    at Object.<anonymous> (C:\Users\Yasin\WebstormProjects\project\dist\project\server\main.js:263164:26)
    at __w_pdfjs_require__ (C:\Users\Yasin\WebstormProjects\project\dist\project\server\main.js:262849:27)
    at C:\Users\Yasin\WebstormProjects\project\dist\project\server\main.js:263041:14        
    at C:\Users\Yasin\WebstormProjects\project\dist\project\server\main.js:263047:5
    at webpackUniversalModuleDefinition (C:\Users\Yasin\WebstormProjects\project\dist\project\server\main.js:262793:30)
    at Object.80063 (C:\Users\Yasin\WebstormProjects\project\dist\project\server\main.js:262794:3)

</code></pre>

After search, I found a solution that consist on defining document globaly, but it didn't work for me, for that I tried to put this code in my server.ts file:

<pre><code>
import { join } from 'path';
import { existsSync, readFileSync } from 'fs';

const domino = require('domino');

const distFolder = join(process.cwd(), 'dist/back-office-angular/browser');
const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';
const template = readFileSync(join(distFolder, indexHtml)).toString();
const window = domino.createWindow(template);

global['window'] = window;
global['document'] = window.document;
global['self'] = window;
global['IDBIndex'] = window.IDBIndex;
global['navigator'] = window.navigator;
global['getComputedStyle'] = window.getComputedStyle;

</code></pre>

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-ssr`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
