### ISSUE TITLE
Unable to run universal app.

### ISSUE THREAD

**Issue by lakhvir1994** [angular/universal#2710]
# 🐞 Bug report

#### What modules are related to this issue?
- [ ] builders
- [ ] common
- [ ] express-engine

### Is this a regression?

I am integrating universal for the first time.

### Description

When I am trying to run the universal app using "ng run Frontend:serve-SSR" than getting an error each time I load localhost:4200 on the browser.

## 🔬 Minimal Reproduction

1) Use the finished example of universal https://angular.io/guide/universal (https://angular.io/generated/zips/universal/universal.zip)

## 🔥 Exception or Error

<pre><code>
TypeError [ERR_INVALID_URL]: Invalid URL: null
    at new NodeError (internal/errors.js:322:7)
    at onParseError (internal/url.js:270:9)
    at new URL (internal/url.js:346:5)
    at new InitServ (/home/pc5/Documents/Restucture/frontend-universal/dist/Frontend/server/main.js:51443:17)
    at Object.InitServ_Factory [as factory] (/home/pc5/Documents/Restucture/frontend-universal/dist/Frontend/server/main.js:52031:10)
    at R3Injector.hydrate (/home/pc5/Documents/BRestucture/frontend-universal/dist/Frontend/server/main.js:241212:35)
    at R3Injector.get (/home/pc5/Documents/Restucture/frontend-universal/dist/Frontend/server/main.js:241031:33)
    at injectInjectorOnly (/home/pc5/Documents/Restucture/frontend-universal/dist/Frontend/server/main.js:234492:33)
    at ɵɵinject (/home/pc5/Documents/Restucture/frontend-universal/dist/Frontend/server/main.js:234496:61)
    at injectArgs (/home/pc5/Documents/Restucture/frontend-universal/dist/Frontend/server/main.js:234576:23)</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.3.8
Node: 14.19.3
Package Manager: npm 6.14.17
OS: linux x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.8
@angular-devkit/build-angular   13.3.8
@angular-devkit/core            13.3.8
@angular-devkit/schematics      13.3.8
@angular/cdk                    13.3.9
@angular/cli                    13.3.8
@angular/material               13.3.9
@nguniversal/builders           13.1.1
@nguniversal/express-engine     13.1.1
@schematics/angular             13.3.8
rxjs                            7.4.0
typescript                      4.6.4

</code></pre>

**Comment by hiepxanh** [comment]
I just clone the new version yesterday and it should work because your downloaded version is 13.3 but the version I just download is 14 https://angular.io/generated/zips/universal/universal.zip
![image](https://user-images.githubusercontent.com/16970990/175441209-1091e062-c3cc-4412-9d6b-fcae2df8ee51.png)

**Comment by lakhvir1994** [comment]
@hiepxanh, If I tried in Angular 8 also, this works fine but for my application, it gives an error.
My application is completely dependent on the API response, there are multiple API calls at the time of appload in "app.module.ts" under providers.
Something like this

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-universal`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
