### ISSUE TITLE
Angular Server-side rendering (SSR) - issue

### ISSUE THREAD

**Issue by dineshmaths1** [angular/universal#2741]
while npm run dev:serve-ssr

Am getting this error.
how to fix?

Compiled successfully.
C:\Users\Nirali\Documents\marketsmojo\technical-repo-gui\mojotechnicals\dist\mojotechnicals\server\main.js:56687
b=b?b._modules:{};g(b,"Series/HollowCandlestick/HollowCandlestickPoint.js",[b["Core/Series/SeriesRegistry.js"]],function(b){var c=this&&this.__extends||function(){var b=function(a,e){b=Object.setPrototypeOf||{proto:[]}instanceof Array&&function(b,a){b.proto=a}||function(b,a){for(var e in a)a.hasOwnProperty(e)&&(b[e]=a[e])};return b(a,e)};return function(a,e){function c(){this.constructor=a}b(a,e);a.prototype=null===e?Object.create(e):(c.prototype=e.prototype,new c)}}();return function(b){function a(){var a=
^

TypeError: Cannot read properties of undefined (reading 'Core/Series/SeriesRegistry.js')
at C:\Users\Nirali\Documents\marketsmojo\technical-repo-gui\mojotechnicals\dist\mojotechnicals\server\main.js:56687:78
at Module.5758 (C:\Users\Nirali\Documents\marketsmojo\technical-repo-gui\mojotechnicals\dist\mojotechnicals\server\main.js:6175:76)
at webpack_require (C:\Users\Nirali\Documents\marketsmojo\technical-repo-gui\mojotechnicals\dist\mojotechnicals\server\main.js:247176:42)
at Module.90158 (C:\Users\Nirali\Documents\marketsmojo\technical-repo-gui\mojotechnicals\dist\mojotechnicals\server\main.js:1610:80)
at webpack_require (C:\Users\Nirali\Documents\marketsmojo\technical-repo-gui\mojotechnicals\dist\mojotechnicals\server\main.js:247176:42)
at Module.36747 (C:\Users\Nirali\Documents\marketsmojo\technical-repo-gui\mojotechnicals\dist\mojotechnicals\server\main.js:1731:77)
at webpack_require (C:\Users\Nirali\Documents\marketsmojo\technical-repo-gui\mojotechnicals\dist\mojotechnicals\server\main.js:247176:42)
at Module.28061 (C:\Users\Nirali\Documents\marketsmojo\technical-repo-gui\mojotechnicals\dist\mojotechnicals\server\main.js:1868:69)
at webpack_require (C:\Users\Nirali\Documents\marketsmojo\techn

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
