### ISSUE TITLE
Meta.getTag from Meta service causing error when platform server

### ISSUE THREAD

**Issue by atlmtw** [angular/universal#2771]
# 🐞 Bug report

#### What modules are related to this issue?
- [ ] builders
- [ ] common
- [x] express-engine

### Is this a regression?

Unsure. I just started using universal recently.

### Description
When using the getTag function from the Meta service from @angular/platform-browser, it causes an error when being used in server. In browser it works fine.

## 🔬 Minimal Reproduction
1. Inject the Meta service into an arbitrary service (SeoService)
2. Use the Meta service get tag function to retrieve a tag

Here's a snippet of what we're using it for inside the SeoService we created
<pre><code>
  addOrUpdateTags(tags: any[]): void {
    tags.forEach(tag => {
      let foundTag = null;
      if (tag.property) {
        foundTag = this.meta.getTag('property = "' + tag.property + '"');
      } else {
        foundTag = this.meta.getTag('name = "' + tag.name + '"');
      }

      if (foundTag) {
        this.meta.updateTag(tag);
      } else {
        this.meta.addTag(tag);
      }
    });
  }
</code></pre>

## 🔥 Exception or Error

<pre><code>
ERROR TypeError: op is not a function
    at Array.<anonymous> (/Users/masonwong/Desktop/workspace/mycube/dist/bcl-starter/server/main.js:65673:14)
    at /Users/masonwong/Desktop/workspace/mycube/dist/bcl-starter/server/main.js:66183:19
    at Array.<anonymous> (/Users/masonwong/Desktop/workspace/mycube/dist/bcl-starter/server/main.js:65978:14)
    at /Users/masonwong/Desktop/workspace/mycube/dist/bcl-starter/server/main.js:66193:23
    at find (/Users/masonwong/Desktop/workspace/mycube/dist/bcl-starter/server/main.js:66267:9)
    at exports (/Users/masonwong/Desktop/workspace/mycube/dist/bcl-starter/server/main.js:66321:10)
    at Document.value (/Users/masonwong/Desktop/workspace/mycube/dist/bcl-starter/server/main.js:40985:14)
    at Meta.getTag (/Users/masonwong/Desktop/workspace/mycube/dist/bcl-starter/server/main.js:231618:22)
    at /Users/masonwong/Desktop/workspace/mycube/dist/bcl-starter/server/main.js:14839:38
    at Array.forEach (<anonymous>)

</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 14.1.1
Node: 16.15.1
Package Manager: npm 8.11.0 
OS: darwin arm64

Angular: 14.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.1
@angular-devkit/build-angular   14.1.1
@angular-devkit/core            14.1.1
@angular-devkit/schematics      14.1.1
@nguniversal/builders           14.0.3
@nguniversal/express-engine     14.0.3
@schematics/angular             14.1.1
rxjs                            6.6.7
typescript                      4.6.4
</code></pre>

**Comment by atlmtw** [comment]
Okay I found out that .getTag is failing in the server when getTag can't find a meta tag that matches the attrSelector argument. In the browser it would return null but in the server its just causing an error.
