### ISSUE TITLE
Cannot use 'in' operator to search for 'scrollBehavior' in undefined

### ISSUE THREAD

**Issue by AlirezaEbrahimkhani** [angular/universal#2804]
When i serve an angular universal app i got this error
```
    if ('scrollBehavior' in document.documentElement.style) {
                         ^

TypeError: Cannot use 'in' operator to search for 'scrollBehavior' in undefined
    at supportsScrollBehavior (/home/alireza/Projects/Angular/Oranustech/alpha/dist/doctors-landing/server/main.js:152477:26)
    at Module.54244 (/home/alireza/Projects/Angular/Oranustech/alpha/dist/doctors-landing/server/main.js:148267:110)
    at __webpack_require__ (/home/alireza/Projects/Angular/Oranustech/alpha/dist/doctors-landing/server/main.js:329543:42)
    at Module.53758 (/home/alireza/Projects/Angular/Oranustech/alpha/dist/doctors-landing/server/main.js:258839:78)
    at __webpack_require__ (/home/alireza/Projects/Angular/Oranustech/alpha/dist/doctors-landing/server/main.js:329543:42)
    at Module.32920 (/home/alireza/Projects/Angular/Oranustech/alpha/dist/doctors-landing/server/main.js:307568:84)
    at __webpack_require__ (/home/alireza/Projects/Angular/Oranustech/alpha/dist/doctors-landing/server/main.js:329543:42)
    at Module.49671 (/home/alireza/Projects/Angular/Oranustech/alpha/dist/doctors-landing/server/main.js:269788:80)
    at __webpack_require__ (/home/alireza/Projects/Angular/Oranustech/alpha/dist/doctors-landing/server/main.js:329543:42)
    at Module.20648 (/home/alireza/Projects/Angular/Oranustech/alpha/dist/doctors-landing/server/main.js:8462:77)

A server error has occurred.
node exited with 1 code.
connect ECONNREFUSED 127.0.0.1:38897
```
Does anyone know how can I solve this problem?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by AlirezaEbrahimkhani** [comment]
I understand where the problem is 
Angular Universal renders the page on the server side. But there is no document there.
Here is the official documentation explaining the situation and how to solve it: https://github.com/angular/universal/blob/main/docs/gotchas.md#window-is-not-defined
