### ISSUE TITLE
Http is broken

### ISSUE THREAD

**Issue by manekinekko** [angular/universal#292]
@joaogarin has reported this issue. See https://github.com/angular/universal-starter/issues/38#issuecomment-189893480

**Comment by manekinekko** [comment]
zone is throwing this:

```
-----async gap-----
Error
    at createNgZone (/Users/wchegham/Sandbox/dev/oss/universal/node_modules/angular2/src/core/application_ref.js:52:12)
    at PlatformRef_.application (/Users/wchegham/Sandbox/dev/oss/universal/node_modules/angular2/src/core/application_ref.js:153:33)
    at Object.bootstrap (/Users/wchegham/Sandbox/dev/oss/universal/node_modules/angular2-universal-preview/dist/server/src/platform/node.js:87:10)
    at renderToString (/Users/wchegham/Sandbox/dev/oss/universal/node_modules/angular2-universal-preview/dist/server/src/render.js:75:19)
    at renderToStringWithPreboot (/Users/wchegham/Sandbox/dev/oss/universal/node_modules/angular2-universal-preview/dist/server/src/render.js:86:12)
    at /Users/wchegham/Sandbox/dev/oss/universal/node_modules/angular2-universal-preview/node_modules/angular2-express-engine/dist/src/engine.js:51:27
ORIGINAL EXCEPTION: Error
ERROR CONTEXT:
_Context {
  element:
   { type: 'tag',
     name: 'app',
     namespace: 'http://www.w3.org/1999/xhtml',
     attribs: {},
     'x-attribsNamespace': {},
     'x-attribsPrefix': {},
     children: [],
     parent:
      { type: 'tag',
        name: 'body',
        namespace: 'http://www.w3.org/1999/xhtml',
        attribs: {},
        'x-attribsNamespace': {},
        'x-attribsPrefix': {},
        children: [Object],
        parent: [Object],
        prev: [Object],
        next: null },
     prev: null,
     next: null },
  componentElement: null,
  injector:
   Injector {
     _isHostBoundary: true,
     _depProvider:
      AppElement {
        proto: [Object],
        parentView: [Object],
        parent: null,
        nativeElement: [Object],
        embeddedViewFactory: null,
        nestedViews: null,
        componentView: null,
        ref: [Object],
        _queryStrategy: _EmptyQueryStrategy {},
        _injector: [Circular],
        _strategy: [Object] },
     _debugContext: [Function],
     _constructionCounter: 3,
     _proto: ProtoInjector { numberOfProviders: 3, _strategy: [Object] },
     _parent:
      Injector {
        _isHostBoundary: false,
        _depProvider: null,
        _debugContext: null,
        _constructionCounter: 1,
        _proto: [Object],
        _parent: [Object],
        _strategy: [Object] },
     _strategy:
      InjectorInlineStrategy {
        injector: [Circular],
        protoStrategy: [Object],
        obj0: {},
        obj1: [Object],
        obj2: [Object],
        obj3: {},
        obj4: {},
        obj5: {},
        obj6: {},
        obj7: {},
        obj8: {},
        obj9: {} } } }
EXCEPTION: TypeError: Cannot read property 'location' of undefined
STACKTRACE:
TypeError: Cannot read property 'location' of undefined
    at /Users/wchegham/Sandbox/dev/oss/universal/node_modules/angular2/src/core/application_ref.js:35:62
    at Zone.run (/Users/wchegham/Sandbox/dev/oss/universal/node_modules/zone.js/dist/zone-microtask.js:1217:24)
    at Zone.run (/Users/wchegham/Sandbox/dev/oss/universal/node_modules/angular2/src/core/zone/ng_zone.js:344:42)
    at zoneBoundFn (/Users/wchegham/Sandbox/dev/oss/universal/node_modules/zone.js/dist/zone-microtask.js:1194:26)
    at lib$es6$promise$$internal$$tryCatch (/Users/wchegham/Sandbox/dev/oss/universal/node_modules/zone.js/dist/zone-microtask.js:442:17)
    at lib$es6$promise$$internal$$invokeCallback (/Users/wchegham/Sandbox/dev/oss/universal/node_modules/zone.js/dist/zone-microtask.js:454:18)
    at lib$es6$promise$$internal$$publish (/Users/wchegham/Sandbox/dev/oss/universal/node_modules/zone.js/dist/zone-microtask.js:425:12)
    at /Users/wchegham/Sandbox/dev/oss/universal/node_modules/zone.js/dist/zone-microtask.js:97:10
    at microtask (/Users/wchegham/Sandbox/dev/oss/universal/node_modules/angular2/src/core/zone/ng_zone.js:384:29)
    at Zone.run (/Users/wchegham/Sandbox/dev/oss/universal/node_modules/zone.js/dist/zone-microtask.js:1217:24)
```

**Comment by gdi2290** [comment]
including these providers and ensuring the url for all request are full urls will work
```es6
[
  provide(APP_BASE_HREF, {useValue: '/' }),
  provide(REQUEST_URL, {useValue: '/' }),
  NODE_HTTP_PROVIDERS
]
```
for tracking each http request before rendering that's for the precache issue. closing for now

**Comment by joaogarin** [comment]
Great it works. I now have an issue where its not actually rendering on the template altough I am getting the items in the service call.

I will create a separate issue as the http request is working nicely.

Thank you!
