### ISSUE TITLE
Window is not defined after upgrading to angular 16

### ISSUE THREAD

**Issue by ahmadallw** [angular/universal#3161]
After upgrading our angular universal app from angular 15 to angular 16 the following issue start to appears while trying to build the app 

Error: 
```
Prerendering 1 route(s) to C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\browser...Unhandled Promise rejection: window is not defined ; Zone: <root> ; Task: Promise.then ; Value: ReferenceError: window is not defined
    at 46465 (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:4663650)
    at __webpack_require__ (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:12338594)
    at 43171 (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:9684220)
    at __webpack_require__ (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:12338594)
    at 82821 (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:981154)
    at __webpack_require__ (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:12338594)
    at 65200 (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:1547596)
    at __webpack_require__ (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:12338594)
    at 22824 (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:1855211)
    at __webpack_require__ (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:12338594) ReferenceError: window is not defined
    at 46465 (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:4663650)
    at __webpack_require__ (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:12338594)
    at 43171 (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:9684220)
    at __webpack_require__ (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:12338594)
    at 82821 (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:981154)
    at __webpack_require__ (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:12338594)
    at 65200 (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:1547596)
    at __webpack_require__ (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:12338594)
    at 22824 (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:1855211)
    at __webpack_require__ (C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\server\main.js:1:12338594)
✖ Prerendering routes to C:\Users\user\Desktop\Repos\ta-web-app\dist\ta-web-app\browser failed.
window is not defined
```

Its working normally when running it locally

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by ahmadallw** [comment]
@alan-agius4 I will share the server.ts file, hope this will help
`/* eslint-disable no-console */
import 'zone.js/dist/zone-node';

import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';
import { join } from 'path';
import * as compression from 'compression';
import * as cookieParser from 'cookie-parser';

import { AppServerModule } from './src/main.server';
import { APP_BASE_HREF } from '@angular/common';
import { existsSync } from 'fs';
import { appConfig } from './src/environments/environment';
import { enableProdMode } from '@angular/core';
import { createWindow } from 'domino';

/* This is the location of the website files. */
console.log('appConfig.environment: ', appConfig.environment);
// const distFolder = join(
//     process.cwd(),
//     appConfig.environment === 'LOCAL' ? 'dist/ta-web-app/browser' : 'browser'
// );
const distFolder = join(process.cwd(), 'dist/ta-web-app/browser');
const indexHtml = existsSync(join(distFolder, 'index.original.html'))
    ? 'index.original.html'
    : 'index';

// SSRFIX: window, document, and other not defined error
patchWindow(indexHtml);
// Faster server renders w/ Prod mode (dev mode never needed)
enableProdMode();
// The Express app is exported so that it can be used by serverless Functions.
export function app(): express.Express {
    const server = express();

    // Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
    server.engine(
        'html',
        ngExpressEngine({
            bootstrap: AppServerModule,
        })
    );

    server.set('view engine', 'html');
    server.set('views', distFolder);
    // server.set('Cache-Control', 'public, max-age=600, s-maxage=1200');
    // **🚀 Perf Tip:**
    // Serve gzip for faster load
    server.use(compression());

    server.use(cookieParser());
    // Example Express Rest API endpoints
    // server.get('/api/**', (req, res) => { });
    // Serve static files from /browser
    server.get(
        '*.*',
        express.static(distFolder, {
            maxAge: '1y',
        })
    );

    // All regular routes use the Universal engine
    server.get('*', (req, res) => {
        // return rendered HTML including Angular generated DOM
        console.log('SSR for route', req.url);
        res.render(indexHtml, {
            req,
            providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }],
        });
    });

    return server;
}

function run(): void {
    const port = process.env['PORT'] ?? 4200;

    // Start up the Node server
    const server = app();
    server.listen(port, () => {
        // eslint-disable-next-line no-console
        console.log(
            `Node Express server listening on http://localhost:${port}`
        );
    });
}

function patchWindow(_template: string): void {
    // Polyfills

    const win = createWindow(_template);
    (win as any).Object = Object;
    (win as any).Math = Math;

    (win as any).localStorage = {
        getItem: (): undefined => undefined,
        setItem: () => void 0,
    };

    (global as any).window = win;
    (global as any).document = win.document;
    (global as any).branch = null;
    (global as any).object = (win as any).object;

    (global as any).navigator = win.navigator;

    (global as any)['Node'] = (win as any).Node;
    (global as any)['Event'] = (win as any).Event;
    (global as any)['KeyboardEvent'] = (win as any).Event;
    (global as any)['MouseEvent'] = (win as any).Event;
    (global as any)['Event']['prototype'] = (win as any).Event.prototype;
    (global as any)['CSS'] = null;
    // (global as any)['XMLHttpRequest'] =
    //     require('xmlhttprequest').XMLHttpRequest;
    (global as any)['Prism'] = null;
}

// Webpack will replace 'require' with '__webpack_require__'
// '__non_webpack_require__' is a proxy to Node 'require'
// The below code is to ensure that the server is run only when not requiring the bundle.
declare const __non_webpack_require__: NodeRequire;
const mainModule = __non_webpack_require__.main;
const moduleFilename = mainModule?.filename ?? '';
if (moduleFilename === __filename || moduleFilename.includes('iisnode')) {
    run();
}

export * from './src/main.server';
`

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
