### ISSUE TITLE
Universal-previous error : Cannot read property 'length' of null - coming from bootloader.js

### ISSUE THREAD

**Issue by MarkPieszak** [angular/universal#340]
* **I'm submitting a ...**
- [X] bug report

Pulled down from copy of universal-starter, OS X. On running `npm start` once the localhost:3000 is opened, it's throwing a webpage not found & node logs error on what looks to be bootloader?

Seems to related to angular-universal-previous.

Node 5.9.1

```
universal-starter/node_modules/parse5/lib/tokenization/preprocessor.js:50
    this.lastCharPos = this.html.length - 1;
                                ^

TypeError: Cannot read property 'length' of null
    at Preprocessor.write (/Users/rachelpieszak/GitHub/universal-starter/node_modules/parse5/lib/tokenization/preprocessor.js:50:33)
    at new module.exports (/Users/rachelpieszak/GitHub/universal-starter/node_modules/parse5/lib/tokenization/preprocessor.js:29:10)
    at new module.exports (/Users/rachelpieszak/GitHub/universal-starter/node_modules/parse5/lib/tokenization/tokenizer.js:148:25)
    at Parser._reset (/Users/rachelpieszak/GitHub/universal-starter/node_modules/parse5/lib/tree_construction/parser.js:399:22)
    at Parser.parse (/Users/rachelpieszak/GitHub/universal-starter/node_modules/parse5/lib/tree_construction/parser.js:361:10)
    at Object.parseDocument (/Users/rachelpieszak/GitHub/universal-starter/node_modules/angular2-universal-preview/dist/node/platform/document.js:17:22)
    at Function.Bootloader.parseDocument (/Users/rachelpieszak/GitHub/universal-starter/node_modules/angular2-universal-preview/dist/node/bootloader.js:32:72)
    at Bootloader.document (/Users/rachelpieszak/GitHub/universal-starter/node_modules/angular2-universal-preview/dist/node/bootloader.js:38:31)
    at Bootloader.application (/Users/rachelpieszak/GitHub/universal-starter/node_modules/angular2-universal-preview/dist/node/bootloader.js:47:24)
    at new Bootloader (/Users/rachelpieszak/GitHub/universal-starter/node_modules/angular2-universal-preview/dist/node/bootloader.js:14:28)
[nodemon] app crashed - waiting for file changes before starting...

```

- Angular version: 2.0.0-beta.X
- Browser: [all ]
- Language: [all | TypeScript 1.9 ]
- OS:  [all | Mac OS X 10.11.4 ]

**Comment by gdi2290** [comment]
can you change the universal version to `"angular2-universal-preview": "~0.84.1",`

**Comment by MarkPieszak** [comment]
Genius. @gdi2290 

That did the trick :)
Sorry for the delay!

**Comment by gdi2290** [comment]
thanks for the rely the module lives here https://github.com/angular/universal/tree/master/modules/universal
