### ISSUE TITLE
fix(broccoli-prerender): causes build error on subsequent builds

### ISSUE THREAD

**Issue by jeffbcross** [angular/universal#406]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
- [x] bug report

* **What modules are related to this pull-request**
- [x] broccoli-prerender

* **What is the current behavior?**

The plugin works correctly on the first build, but fails on subsequent builds on this line: 
`var bootloader = Bootloader.create(options);`

Stack trace:

```
Error: There can be only one platform. Destroy the previous one to create a new one.
    at new BaseException (node_modules/@angular/core/src/facade/exceptions.js:17:23)
    at Object.createPlatform (node_modules/@angular/core/src/application_ref.js:36:15)
    at Bootloader.platform (node_modules/angular2-universal/dist/node/bootloader.js:48:23)
    at new Bootloader (node_modules/angular2-universal/dist/node/bootloader.js:16:33)
    at Function.Bootloader.create (node_modules/angular2-universal/dist/node/bootloader.js:23:16)
    at AppShellPlugin.build (node_modules/angular2-broccoli-prerender/dist/prerender.js:26:58)
    at node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)

The broccoli plugin was instantiated at:
    at AppShellPlugin.Plugin (node_modules/broccoli-plugin/index.js:10:31)
    at AppShellPlugin.CachingWriter [as constructor] (node_modules/broccoli-caching-writer/index.js:21:10)
    at new AppShellPlugin (node_modules/angular2-broccoli-prerender/dist/prerender.js:15:16)
    at Angular2App._buildTree (node_modules/angular-cli/lib/broccoli/angular2-app.js:151:48)
    at new Angular2App (node_modules/angular-cli/lib/broccoli/angular2-app.js:51:23)
    at module.exports (angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (node_modules/rsvp/dist/rsvp.js:1048:17)
    at node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:452:9)
```

Since the plugin currently only supports compilation on the first pass, it should not try to re-compile on subsequent runs, and should log a message about it. Eventually the plugin should support re-compiling.

**Comment by jeffbcross** [comment]
Fixed by https://github.com/angular/universal/commit/92cf60b2e24f0facaa2f8753b5006b516d650ad9
