### ISSUE TITLE
npm install takes more than 20 minutes 

### ISSUE THREAD

**Issue by sap9433** [angular/universal#428]
I'm here in New Delhi , the Capital of India and just a simple npm install takes 20 minutes with a connection of 16.2 mbps. And that kills all the enthusiasm to use this repo :). And I aborted the npm install , after 20 long taxing minutes , I see total npm modules are >850 ... Wow . 

 **Please make this repo usable**

**Comment by MarkPieszak** [comment]
Are you just trying to start using Universal? Using one of the starters if you just want to get going, and will be much faster.
[NodeJS Starter](https://github.com/angular/universal-starter)
[.NET Starter](https://github.com/aspnet/JavaScriptServices/tree/master/templates/Angular2Spa)

This repo itself is more for developing & working on Universal/Preboot itself. Although there will be some clean-up soon, it still might always take a while. 

An `npm install` actually runs (`install:all`), which runs through a large loop of installing multiple large modules all needed for Universal (in a specific order), building them, running TS compiler, then even sets up & installs the examples folder which is mainly for testing Universal/preboot/etc changes.

On a fast connection it will take ~10 minutes. What is your connection speed?

**Comment by sap9433** [comment]
my speed is 16.2 mbps..

**Comment by MarkPieszak** [comment]
I wonder if it's getting hung up somewhere for you, I output things into the console from time to time like:

`Installing Preboot ...` etc 
`Done installing Preboot...` 
`Building polyfills...` etc

Can you try it again and just let it run all the way through and time how long it takes?

Also, how does Universal-starter work for you?

**Comment by gajdot** [comment]
I'm trying this on a Linux VM, it took less then 10 minutes, but tons of errors are thrown, without killing the build process. In the end it finishes, but the examples won't run if you try to access localhost:3000, you'll get this error: 

```console
WARNING: ngDoCheck must return a boolean value of either true or false

preboot Error: TypeError: Cannot read property 'disableCodeCache' of undefined
    at Object.getBrowserCode (/home/gajdot/programming/universal/examples/node_modules/preboot/dist/src/node/browser_code_generator.js:76:14)
    at Object.createPrebootCode (/home/gajdot/programming/universal/examples/node_modules/angular2-universal/dist/node/ng_preboot.js:36:28)
    at Bootloader._preboot (/home/gajdot/programming/universal/examples/node_modules/angular2-universal/dist/node/bootloader.js:262:40)
    at /home/gajdot/programming/universal/examples/node_modules/angular2-universal/dist/node/bootloader.js:121:37
    at ZoneDelegate.invoke (/home/gajdot/programming/universal/examples/node_modules/zone.js/dist/zone-node.js:281:29)
    at Zone.run (/home/gajdot/programming/universal/examples/node_modules/zone.js/dist/zone-node.js:174:44)
    at /home/gajdot/programming/universal/examples/node_modules/zone.js/dist/zone-node.js:529:58
    at ZoneDelegate.invokeTask (/home/gajdot/programming/universal/examples/node_modules/zone.js/dist/zone-node.js:314:38)
    at Zone.runTask (/home/gajdot/programming/universal/examples/node_modules/zone.js/dist/zone-node.js:214:48)
    at drainMicroTaskQueue (/home/gajdot/programming/universal/examples/node_modules/zone.js/dist/zone-node.js:432:36)
Rendering Document Error: TypeError: Cannot read property '0' of undefined
    at /home/gajdot/programming/universal/examples/node_modules/angular2-universal/dist/node/bootloader.js:132:38
    at ZoneDelegate.invoke (/home/gajdot/programming/universal/examples/node_modules/zone.js/dist/zone-node.js:281:29)
    at Zone.run (/home/gajdot/programming/universal/examples/node_modules/zone.js/dist/zone-node.js:174:44)
    at /home/gajdot/programming/universal/examples/node_modules/zone.js/dist/zone-node.js:529:58
    at ZoneDelegate.invokeTask (/home/gajdot/programming/universal/examples/node_modules/zone.js/dist/zone-node.js:314:38)
    at Zone.runTask (/home/gajdot/programming/universal/examples/node_modules/zone.js/dist/zone-node.js:214:48)
    at drainMicroTaskQueue (/home/gajdot/programming/universal/examples/node_modules/zone.js/dist/zone-node.js:432:36)
    at Timeout.ZoneTask.invoke [as _onTimeout] (/home/gajdot/programming/universal/examples/node_modules/zone.js/dist/zone-node.js:384:22)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
DONE
```
If you try to access any other link you get the proper not found message:
```json
{
  "url": "/wtf",
  "route": "Sorry this page does not exist!"
}
```

**Comment by gdi2290** [comment]
this will be fixed via https://github.com/angular/universal/issues/463 you can track that issue. I'll be closing this one
