### ISSUE TITLE
track runtime styleUrls

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#432]
track runtime styleUrls. for webpack use `angular2-template-loader`

**Comment by b091** [comment]
nice to have? So right now angular universal is only for angular using webpack?

**Comment by ardiadrianadri** [comment]
Hello:

 How is this issue? I don't know if it is related but, when I add a url style I get the next error in the browser:
```
browser_adapter.js:84EXCEPTION: TypeError: s.replace is not a functionBrowserDomAdapter.logError @ browser_adapter.js:84
browser_adapter.js:84STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:84
browser_adapter.js:84TypeError: s.replace is not a function
    at Function.StringWrapper.replaceAllMapped (http://localhost:3000/dist/app.bundle.js:34796:19)
    at Object.extractStyleUrls (http://localhost:3000/dist/app.bundle.js:40490:49)
    at http://localhost:3000/dist/app.bundle.js:48485:58
    at Array.map (native)
    at DirectiveNormalizer.normalizeStylesheet (http://localhost:3000/dist/app.bundle.js:48484:44)
    at DirectiveNormalizer.normalizeLoadedTemplate (http://localhost:3000/dist/app.bundle.js:48424:44)
    at DirectiveNormalizer.normalizeTemplateSync (http://localhost:3000/dist/app.bundle.js:48410:22)
    at DirectiveNormalizer.normalizeDirective (http://localhost:3000/dist/app.bundle.js:48386:44)
    at RuntimeCompiler._getCompiledTemplate (http://localhost:3000/dist/app.bundle.js:47319:189)
    at RuntimeCompiler._getTransitiveCompiledTemplates (http://localhost:3000/dist/app.bundle.js:47327:81)BrowserDomAdapter.logError @ browser_adapter.js:84
zone.js:260Uncaught TypeError: s.replace is not a function
```
This is the code of my component:
````
import { Component, OnInit} from '@angular/core';
import {ROUTER_DIRECTIVES} from '@angular/router';

import {Menu} from './menu';
import {MenuService} from './menu.service';

@Component({
    selector:'my-menu',
    templateUrl:'../templates/menu.html',
    styleUrls: ['../templates/menu.css'],
    directives: [ROUTER_DIRECTIVES]  
})
export class MyMenu implements OnInit{
    public menuConfig: Menu;

    constructor(private menuService:MenuService){}

    private _getConfig(){
        this.menuService.getConfig().then(data => {
            console.log(JSON.stringify(data));
            this.menuConfig = data
        })
        .catch(error => {throw new Error(error)});
    }

    ngOnInit(){
        this._getConfig();
    }
}
```

And this is the css code of menu.css:
``` 
nav {
    background-color: red;
}
```

**Comment by jeffwhelpley** [comment]
@gdi2290 what is the status here?

**Comment by gdi2290** [comment]
use webpack and angular2-template-loader

**Comment by dancancro** [comment]
Removing `keepUrl=true` from `angular2-template-loader?keepUrl=true` in generator-jhipster generated code solved this problem for me that started after I refactored my app and moved things around. Maybe something else would have fixed it but the angular2-template-loader instructions say to use this option with `file-loader` which I'm not doing with template or style files. I'll update this if I find another way.
