### ISSUE TITLE
Can't install typings

### ISSUE THREAD

**Issue by vapits** [angular/universal#437]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
- [x] bug report

* **What is the current behavior?**

I'm following Get Started procedure and when'm trying to install typings by:
`typings install node express body-parser serve-static express-serve-static-core mime --global` _(because --ambient is deprecated)_ 
I'm getting error messages that is unable to find for example body-parser in npm registry. 
But every time is a different package, from the defaults...
So I cannot compile the app...

I get this when I try to run it:
```
[nodemon] starting `node dist/server.js`
Listening on: http://localhost:3000
EXCEPTION: TypeError: Cannot read property 'annotations' of undefined
STACKTRACE:
TypeError: Cannot read property 'annotations' of undefined
    at ReflectionCapabilities.annotations (/Projects/Jexia/WebApp/node_modules/@angular/core/src/reflection/reflection_capabilities.js:142:40)
    at Reflector.annotations (/Projects/Jexia/WebApp/node_modules/@angular/core/src/reflection/reflector.js:96:48)
    at DirectiveResolver.resolve (/Projects/Jexia/WebApp/node_modules/@angular/compiler/src/directive_resolver.js:23:44)
    at CompileMetadataResolver.getDirectiveMetadata (/Projects/Jexia/WebApp/node_modules/@angular/compiler/src/metadata_resolver.js:55:51)
    at RuntimeCompiler.resolveComponent (/Projects/Jexia/WebApp/node_modules/@angular/compiler/src/runtime_compiler.js:34:47)
    at /Projects/Jexia/WebApp/node_modules/@angular/core/src/application_ref.js:99:37
    at /Projects/Jexia/WebApp/node_modules/@angular/core/src/application_ref.js:292:26
    at ZoneDelegate.invoke (/Projects/Jexia/WebApp/node_modules/zone.js/dist/zone-node.js:281:29)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (/Projects/Jexia/WebApp/node_modules/@angular/core/src/zone/ng_zone_impl.js:45:41)
    at ZoneDelegate.invoke (/Projects/Jexia/WebApp/node_modules/zone.js/dist/zone-node.js:280:35)
/Projects/Jexia/WebApp/node_modules/@angular/core/src/application_ref.js:302
                throw e;
                ^
```
* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.1
- Language: [all | TypeScript 1.8.10 ]
- OS:  [all ]
- Platform: [NodeJs]

**Comment by MarkPieszak** [comment]
#434 I'm in the process of updating the project to use `typings 1.*` naming conventions, I'll let you know when it's merged in so you can try again! Also are you using `angular rc1` or `beta1`? (beta1 is very old, I believe we only really work on rc1 at the moment.

**Comment by vapits** [comment]
@MarkPieszak sorry my bad, about the angular version, I use rc1. I'll edit my issue, and thanks for your infos.

**Comment by MarkPieszak** [comment]
#434 Should fix this, can probably be closed out. Can you double check @vapits ?

**Comment by vapits** [comment]
Yes @MarkPieszak 
It works for me now.

I'll close it for you.
