### ISSUE TITLE
setElementProperty can't accept `null`

### ISSUE THREAD

**Issue by visikov** [angular/universal#496]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
- [x] bug report

* **What modules are related to this pull-request**
- [x] universal

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
setElementProperty can't accept `null` for propertyValue, this throws an error down the stack in `@angular/platform-server/node_modules/parse5/lib/tokenization/preprocessor.js:50:33`

* **What is the expected behavior?**
Fail gracefully

It can easily be fixed with `if (propertyValue === null) return;` But I am unsure of any potential side-effects from this.

**Comment by MarkPieszak** [comment]
What property of what element are you trying to set to Null?

https://github.com/angular/universal/blob/4319b2a0425e1bdff1c80f614a50943bc712dd6c/modules/universal/src/node/platform/dom/node_dom_renderer.ts#L224

There's a lot of scenarios, we can add it just me know what it is.

**Comment by visikov** [comment]
@MarkPieszak I believe it's innerHTML. I believe it happens when the prop value hasn't loaded yet from an observable, haven't had a chance to test it out yet, have to run to the airport in 15 minutes.

**Comment by visikov** [comment]
@MarkPieszak I was able to get the issue fixed on my end by restructuring some of the data and making use of the question mark notation in the template `model.name` vs `model?.name`. This fixed the issue for me, however it'd probably be a good idea to test for null prop values and fail gracefully instead of crash and burning.

Feel free to close this issue if you want.

**Comment by MarkPieszak** [comment]
The error being thrown was it

> Rendering Document Error: TypeError: undefined is not a function or Rendering Document Error: TypeError: str.replace is not a function

This might be related to #483 somewhat. I'm going to dive into the NodeRenderer today & this weekend to try and see what's missing there for these certain scenarios.

**Comment by visikov** [comment]
There was a str.replace is not a function error being thrown yes. But there was one right before that coming from parse5:

`TypeError: Cannot read property 'length' of null
    at Preprocessor.write (/home/vitaliy/projects/inrhythm/cnd/app/node_modules/@angular/platform-server/node_modules/parse5/lib/tokenization/preprocessor.js:50:33)
    at new module.exports (/home/vitaliy/projects/inrhythm/cnd/app/node_modules/@angular/platform-server/node_modules/parse5/lib/tokenization/preprocessor.js:29:10)
    at new module.exports (/home/vitaliy/projects/inrhythm/cnd/app/node_modules/@angular/platform-server/node_modules/parse5/lib/tokenization/tokenizer.js:145:25)
    at Parser._reset (/home/vitaliy/projects/inrhythm/cnd/app/node_modules/@angular/platform-server/node_modules/parse5/lib/tree_construction/parser.js:387:22)
    at Parser.parseFragment (/home/vitaliy/projects/inrhythm/cnd/app/node_modules/@angular/platform-server/node_modules/parse5/lib/tree_construction/parser.js:366:10)
    at Parse5DomAdapter.setInnerHTML (/home/vitaliy/projects/inrhythm/cnd/app/node_modules/@angular/platform-server/src/parse5_adapter.js:261:30)
    at Parse5DomAdapter.setProperty (/home/vitaliy/projects/inrhythm/cnd/app/node_modules/@angular/platform-server/src/parse5_adapter.js:56:18)
    at NodeDomRenderer.DomRenderer.setElementProperty (/home/vitaliy/projects/inrhythm/cnd/app/node_modules/@angular/platform-browser/src/dom/dom_renderer.js:167:32)
    at NodeDomRenderer.setElementProperty (/home/vitaliy/projects/inrhythm/cnd/app/node_modules/angular2-universal/dist/node/platform/dom/node_dom_renderer.js:228:59)
    at AppView._View_Component0.detectChangesInternal (Component.template.js:550:19)
`

**Comment by MarkPieszak** [comment]
Yeah that means there are no Components it's getting (but that's most likely because it's because due to this property error). I'll figure it out and try and get a patch in there soon!

**Comment by MarkPieszak** [comment]
#500 Should fix this one for you @visikov
