### ISSUE TITLE
typeof Number in Props breaking in NodeDomRenderer on Number passed into non-aliased Name of @Input()

### ISSUE THREAD

**Issue by MarkPieszak** [angular/universal#499]
Splitting up a bug mentioned in a comment elsewhere.

Having your own `@Input('content') contentId` pass a type Number (ie: `someNumber = 12345`) breaks
`[something]="someNumber"`.

#### If referenced incorrectly in the template as [contentId] instead of by it's `alias` `[content]`, the error appears, but it's difficult to tell if it's a Core issue or not.

-----

* **What is the current behavior?**
From @Zeetah (https://github.com/angular/universal/issues/483#issuecomment-236146500)

> Quote:
> 
> We have a similar issue with "numbers" inside string where we have for example element like this:
> <cms-authentication [contentId]="123456"></cms-authentication>
> 
> It gives us stacktrace:
> 
>      Rendering Document Error: [TypeError: str.replace is not a function]
> ```
> TypeError: str.replace is not a function
>     at escapeString (/path/to/app/node_modules/parse5/lib/serialization/serializer.js:27:10)
>     at Serializer._serializeAttributes (/path/to/app/node_modules/parse5/lib/serialization/serializer.js:124:55)
>     at Serializer._serializeElement (/path/to/app/node_modules/parse5/lib/serialization/serializer.js:91:10)
>     at Serializer._serializeChildNodes (/path/to/app/node_modules/parse5/lib/serialization/serializer.js:72:22)
>     at Serializer._serializeElement (/path/to/app/node_modules/parse5/lib/serialization/serializer.js:114:14)
>     at Serializer._serializeChildNodes (/path/to/app/node_modules/parse5/lib/serialization/serializer.js:72:22)
>     at Serializer._serializeElement (/path/to/app/node_modules/parse5/lib/serialization/serializer.js:114:14)
>     at Serializer._serializeChildNodes (/path/to/app/node_modules/parse5/lib/serialization/serializer.js:72:22)
>     at Serializer._serializeElement (/path/to/app/node_modules/parse5/lib/serialization/serializer.js:114:14)
>     at Serializer._serializeChildNodes (/path/to/app/node_modules/parse5/lib/serialization/serializer.js:72:22)
> ```

**Comment by MarkPieszak** [comment]
@Zeetah It turns out it can handle numbers fine, but you have to reference the @Input correctly by it's name.

Are you doing some sort of `alias` for your @Input? If so you need to reference that different name there in your attributes.

For example:

     @Input('content') contentId : number;

Needs to be in the template as:

       <cms [content]="12345" />

When doing the non-alias'd name i was able to reproduce it though (only with a number). Then again this won't work, and doesn't end up **passing** the value to the child Component.

       <cms [contentId]="12345" />
