### ISSUE TITLE
Polyfills Break Mongoose

### ISSUE THREAD

**Issue by bdunn44** [angular/universal#592]
* **I'm submitting a ...**
- [x] bug report

* **What modules are related to this Issue?**
- [x] universal

* **What is the current behavior?**
Importing `angular2-universal-polyfills` breaks MongoDB connection via Mongoose. Stack trace:

```
C:\Angular Projects\universal-starter\node_modules\zone.js\dist\zone-node.js:140
                        throw error;
                        ^

TypeError: Cannot read property 'filter' of undefined
    at zoneAwareEventListeners (C:\Angular Projects\universal-starter\node_modules\zone.js\dist\zone-node.js:772:13)
    at Db.listeners (eval at createNamedFn (C:\Angular Projects\universal-starter\node_modules\zone.js\dist\zone-node.js:785:17), <anonymous>:3:36)
    at Server.listener (C:\Angular Projects\universal-starter\node_modules\mongodb\lib\db.js:1790:15)
    at Server.g (events.js:291:16)
    at ZoneDelegate.invokeTask (C:\Angular Projects\universal-starter\node_modules\zone.js\dist\zone-node.js:236:37)
    at Zone.runTask (C:\Angular Projects\universal-starter\node_modules\zone.js\dist\zone-node.js:136:47)
    at Server.ZoneTask.invoke (C:\Angular Projects\universal-starter\node_modules\zone.js\dist\zone-node.js:304:33)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at Server.connectHandler (C:\Angular Projects\universal-starter\node_modules\mongodb\lib\server.js:329:10)
    at Server.g (events.js:291:16)
    at ZoneDelegate.invokeTask (C:\Angular Projects\universal-starter\node_modules\zone.js\dist\zone-node.js:236:37)
    at Zone.runTask (C:\Angular Projects\universal-starter\node_modules\zone.js\dist\zone-node.js:136:47)
    at Server.ZoneTask.invoke (C:\Angular Projects\universal-starter\node_modules\zone.js\dist\zone-node.js:304:33)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem by creating a github repo.**

Cloned the universal starter to demo this bug. [https://github.com/bdunn44/universal-starter/commit/f5b948447bfde7a9cdc8eaeb9fbd31bd9e6aba02](https://github.com/bdunn44/universal-starter/commit/f5b948447bfde7a9cdc8eaeb9fbd31bd9e6aba02)
```
git clone https://github.com/bdunn44/universal-starter.git
cd universal-starter
npm install
npm start
```

* **Please tell us about your environment:**

- Angular version: 2.0.0
- Browser: N/A
- Language: TypeScript 2.0
- OS:  Windows
- Platform: NodeJS

**Comment by gdi2290** [comment]
hi, thanks for creating an issue. Can you change the zone.js version to zone.js 0.6.21 and track this Issue/PR in the zone.js repo
https://github.com/angular/zone.js/issues/448

**Comment by bdunn44** [comment]
Can't believe I missed that. Will do, thanks.
