### ISSUE TITLE
Gulpfile to create a node.js app for azure works, but get a Error: Failed to lookup view "index" in views directory "src"

### ISSUE THREAD

**Issue by hakonamatata** [angular/universal#661]
Hi 

So I have developed a simple gulp script to create a nice node.js app to run angular universal on Azure, but it doesn't quite work. 

My folder structure after running gulp looks like this: 

```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       30.01.2017     16.07                assets
d-----       30.01.2017     16.07                temp
-a----       30.01.2017     16.07        1661616 app.js
-a----       30.01.2017     16.07        6460065 app.js.map
-a----       31.01.2017     10.19            656 index.html
-a----       31.01.2017     10.19         616568 main.bundle.js
-a----       31.01.2017     10.19        4688762 main.bundle.js.map
-a----       31.01.2017     12.57            820 morgan.log
-a----       31.01.2017     10.19           4174 package.json

```

It runs nicely, but when I connect to the page I get a 

**Error: Failed to lookup view "index" in views directory "src"**

More details at the end of the post.

Here is my gulp file: 

```
"use strict";
var gulp = require("gulp");
var del = require("del");
var sourcemaps = require('gulp-sourcemaps');
var rename = require('gulp-rename');
var clean = require('gulp-clean');

/**
 * Remove build directory.
 */
gulp.task('clean', function (cb) {
    return del(["build"], cb);
});

/**
 * Copy all resources that are not TypeScript files into build directory.
 */
gulp.task("resources", ["server", "app", "assets", "client", "rename1", "rename2"], function () {
    console.log("Building resources...");
});
/* copy the app core files to the build folder */
gulp.task("app", ['index'], function(){
    return gulp.src(["app/**", "!app/**/*.ts"])
        .pipe(gulp.dest("build/app"));
});
/* get the index file to the root of the build */
// TODO: Add web.config
gulp.task("index", function(){
    return gulp.src(["src/index.html", "package.json"])
        .pipe(gulp.dest("build"));
});
/* copy node server to build folder */
gulp.task("server", function () {
    return gulp.src(["index.js", "package.json"], { cwd: "server/**" })
        .pipe(gulp.dest("build"));
});

/* styles and other assets */
gulp.task("assets", function(){
    return gulp.src(["src/assets/**"])
        .pipe(gulp.dest("build/assets"));
});

/* client folder */
gulp.task("client", function(){
    return gulp.src(["dist/client/main.bundle.js", "dist/client/main.bundle.js.map"])
        .pipe(gulp.dest("build"));
});

/* rename /server/index.js to app.js and move to build */
gulp.task('rename1', function() {
    return gulp.src(["dist/server/index.js"])
        .pipe(gulp.dest("build/temp"))
        .pipe(rename('app.js'))
        .pipe(gulp.dest(".."));
});

gulp.task('rename2', function() {
    return gulp.src(["dist/server/index.js.map"])
        .pipe(gulp.dest("build/temp"))
        .pipe(rename('app.js.map'))
        .pipe(gulp.dest(".."));
});

/*
gulp.task('temp', function() {
    return gulp.src(["build/temp"])
        .pipe(clean({force: true}))
});
*/

/**
 * Copy all required libraries into build directory.
 *
gulp.task("libs", function () {
    return gulp.src([
        'core-js/client/shim.min.js',
        'zone.js/dist/zone.js',
        'systemjs/dist/system.src.js',
        'systemjs.config.js',
        // 'es6-shim/es6-shim.min.js',
        'systemjs/dist/system-polyfills.js',
        'angular2/bundles/angular2-polyfills.js',
        'angular2/es6/dev/src/testing/shims_for_IE.js',
        'systemjs/dist/system.src.js',
        'rxjs/bundles/Rx.js',
        'angular2/bundles/angular2.dev.js',
        'angular2/bundles/router.dev.js'
    ], { cwd: "node_modules/**" }) /* Glob required here.
        .pipe(gulp.dest("build/node_modules"));
});
/**
 * Build the project.
 */
gulp.task("default", ['resources'], function () {
    console.log("Building the project ...");
});

```

* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [X] support request 

* **What modules are related to this Issue?**
- [X] universal

```
Listening on: http://localhost:3000
Error: Failed to lookup view "index" in views directory "src"
    at EventEmitter.render (C:\front-end\universal\node_modules\express\lib\application.js:579:17)
    at ServerResponse.render (C:\front-end\universal\node_modules\express\lib\response.js:960:7)
    at C:\front-end\universal\build\app.js:52:12237
    at ZoneDelegate.invoke (C:\front-end\universal\node_modules\zone.js\dist\zone-node.js:232:26)
    at Zone.run (C:\front-end\universal\node_modules\zone.js\dist\zone-node.js:114:43)
    at ngApp (C:\front-end\universal\build\app.js:52:12218)
    at Layer.handle [as handle_request] (C:\front-end\universal\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\front-end\universal\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\front-end\universal\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\front-end\universal\node_modules\express\lib\router\layer.js:95:5)
```

**Comment by MarkPieszak** [comment]
What version of Node is running in this Azure app service?

**Comment by hakonamatata** [comment]
I have the same problem locally
node **v6.9.4**

Azure:
```
The package.json file does not specify node.js engine version constraints.
The node.js application will run with the default node.js version 6.9.1.
Selected npm version 3.10.8
```

**Comment by MarkPieszak** [comment]
Is it because of this gulp line:

```
gulp.task("index", function(){
    return gulp.src(["src/index.html", "package.json"])
        .pipe(gulp.dest("build"));
```

It's looking for index in the `src/` folder but it looks like it's in your Root directory.

Just closing out the issue as it's not Universal-related.
