### ISSUE TITLE
Cannot find primary outlet to load

### ISSUE THREAD

**Issue by Scoup** [angular/universal#728]
* **I'm submitting a ...**
```
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [X] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**

Report a possible bug.

* **What is the current behavior?**

When rendering pages on the server renderer if using "resolve" to get the data the primary outlet is undefined.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
```
const routes: Routes = [
  { path: 'host/:id', 
    component: HostProfileIndexComponent, 
    resolve: {
      list: ListResolve
    }
  }
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule],
  providers: [ListResolve]
})

@Injectable()
export class ListResolve implements Resolve<List> {

  constructor(private listService: ListService) {}
  
  resolve(route: ActivatedRouteSnapshot) {
    console.log("list resolve");
    // route.outlet
    return this.listService.request(route.params['id']).then(list => {
      console.log("list found");
      console.log(list.id);
      return list;
    });
  }

}
```
This problem is only happing in AOT. If the `ListResolve.resolve` just return a resolved promise, like "Promise.resolve()", everything works fine. But when I do the full request for the api server (not the same server) I got the message: `ERROR { Error: Uncaught (in promise): Error: Cannot find primary outlet to load 'IndexComponent'`.

The ListService.request is just a simple http.get. 
I checked the router.getOutlet in console and I get `{ primary: undefined }` just before the error. But if I do not make the request and just return a resolved promise, the primary is ok.

* **What is the expected behavior?**

I expect the same behavior of returning a simple Promise or a complex one and not having the outlet missing. Or at least some tip of how can I try to investigate more about this behavior.

* **What is the motivation / use case for changing the behavior?**

I need to the server to render with data of an api.

* **Please tell us about your environment:**

- Angular version: 4.X
- Browser: [none]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [Mac OS X]
- Platform: [NodeJs]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

```
outletMap._outlets: { primary: undefined }
Error in SSR, serving for direct CSR
ERROR { Error: Uncaught (in promise): Error: Cannot find primary outlet to load 'IndexComponent'
Error: Cannot find primary outlet to load 'IndexComponent'
    at getOutlet (/path_of_project/node_modules/@angular/router/bundles/router.umd.js:4639:19)
    at ActivateRoutes.activateRoutes (/path_of_project/node_modules/@angular/router/bundles/router.umd.js:4495:47)
    at /path_of_project/node_modules/@angular/router/bundles/router.umd.js:4440:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (/path_of_project/node_modules/@angular/router/bundles/router.umd.js:4440:29)
    at ActivateRoutes.activate (/path_of_project/node_modules/@angular/router/bundles/router.umd.js:4414:14)
    at /path_of_project/node_modules/@angular/router/bundles/router.umd.js:4031:22
    at SafeSubscriber._next (/path_of_project/node_modules/rxjs/Observable.js:96:25)
    at SafeSubscriber.__tryOrUnsub (/path_of_project/node_modules/rxjs/Subscriber.js:238:16)
    at SafeSubscriber.next (/path_of_project/node_modules/rxjs/Subscriber.js:185:22)
    at resolvePromise (/path_of_project/node_modules/zone.js/dist/zone-node.js:757:31)
    at resolvePromise (/path_of_project/node_modules/zone.js/dist/zone-node.js:728:17)
    at /path_of_project/node_modules/zone.js/dist/zone-node.js:805:17
    at ZoneDelegate.invokeTask (/path_of_project/node_modules/zone.js/dist/zone-node.js:414:31)
    at Object.onInvokeTask (/path_of_project/node_modules/@angular/core/bundles/core.umd.js:4126:37)
    at ZoneDelegate.invokeTask (/path_of_project/node_modules/zone.js/dist/zone-node.js:413:36)
    at Zone.runTask (/path_of_project/node_modules/zone.js/dist/zone-node.js:181:47)
    at drainMicroTaskQueue (/path_of_project/node_modules/zone.js/dist/zone-node.js:574:35)
    at ZoneTask.invoke (/path_of_project/node_modules/zone.js/dist/zone-node.js:480:25)
    at data.args.(anonymous function) (/path_of_project/node_modules/zone.js/dist/zone-node.js:1392:25)
  rejection:
```

**Comment by Scoup** [comment]
After some investigation, the problem doesn't see related with the universal. The problem is related if you have any bug in your "resolve" you have no feedback about it.
Anyone know if this no feedback in "resolve" will be solved?
