### ISSUE TITLE
universal with ngx-translate

### ISSUE THREAD

**Issue by premiumwd** [angular/universal#748]
* **I'm submitting a ...**
```
- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x ] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**
I need some help with angular universal and ng2-translate. I separate the logic for client side vs. server side and needed some help. I used the code exactly in documents and provided by author.

**server.ts**
```
import 'reflect-metadata';
import 'zone.js/dist/zone-node';
import { platformServer, renderModuleFactory } from '@angular/platform-server'
import { enableProdMode } from '@angular/core'
import { AppServerModuleNgFactory } from '../dist/ngfactory/src/app/app.server.module.ngfactory'
import * as express from 'express';
import { readFileSync } from 'fs';
import { join } from 'path';

const PORT = 4000;

enableProdMode();

const app = express();

let template = readFileSync(join(__dirname, '..', 'dist', 'index.html')).toString();

app.engine('html', (_, options, callback) => {
  const opts = { document: template, url: options.req.url };

  renderModuleFactory(AppServerModuleNgFactory, opts)
    .then(html => callback(null, html));
});

app.set('view engine', 'html');
app.set('views', 'src')

app.get('*.*', express.static(join(__dirname, '..', 'dist')));

app.get('*', (req, res) => {
  res.render('index', { req });
});

app.listen(PORT, () => {
  console.log(`listening on http://localhost:${PORT}!`);
});
```

**app.server.module.ts**
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { Http } from '@angular/http';
import { ServerModule } from '@angular/platform-server';

import { AppModule } from './app.module';
import { AppComponent } from './app.component';

import { TranslateHttpLoader } from '@ngx-translate/http-loader';
import { TranslateModule, TranslateLoader } from '@ngx-translate/core';
import { TranslateUniversalLoader } from './core/services/translate.service';


@NgModule({
imports: [
    ServerModule,
    AppModule,
    TranslateModule.forRoot({
        loader: {
            provide: TranslateLoader,
            useClass: TranslateUniversalLoader
        }
    }),
],
bootstrap: [AppComponent]
})
export class AppServerModule { }
```

**translate.service.ts**
```
import {TranslateLoader} from "@ngx-translate/core";
import {Observable} from "rxjs/Observable";
var fs = require('fs');

export class TranslateUniversalLoader implements TranslateLoader {
    /**
     * Gets the translations from the server
     * @param lang
     * @returns {any}
     */
    public getTranslation(lang: string): Observable<any> {
        return Observable.create(observer => {
            observer.next(JSON.parse(fs.readFileSync(`i18n/${lang}.json`, 'utf8')));
            observer.complete();
        });
    }
}
```

**app.module.ts**
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule, Http, RequestOptions } from '@angular/http';

// TRANSLATE
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
import {TranslateModule, TranslateLoader} from '@ngx-translate/core';
// AOT Export
export function HttpLoaderFactory(http: Http) {
  return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}

@NgModule(
  {
  imports: [
    HttpModule,
    AppRoutingModule,

    // UNIVERSAL
    BrowserModule.withServerTransition({appId: 'd'}),

    // TRANSLATE
    TranslateModule.forRoot({
        loader: {
            provide: TranslateLoader,
            useFactory: HttpLoaderFactory,
            deps: [Http]
        }
    }),

  ],
  declarations: [AppComponent],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

I get the following error:

 ```
> d@0.0.0 build H:\d
> ts-node src/server.ts

H:\d\node_modules\@ngx-translate\core\index.js:1
(function (exports, require, module, __filename, __dirname) { import { NgModule
} from "@angular/core";
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (H:\d\dist\ngfactory\src\app\app.server.module.ngfacto
ry.ts:18:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! d@0.0.0 build: `ts-node src/server.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the d@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.
```

- Angular version: 4
- Browser: [Chrome]
- Language: [TypeScript 2]
- OS:  [Windows ]
- Platform: [NodeJs]

**Comment by jackzzj** [comment]
@premiumwd How did you fix this ? I'm having the same issue.

**Comment by premiumwd** [comment]
@jackzzj no I didnt resolve.

**Comment by SergiusSidorov** [comment]
The same issue.

- Angular 4.2.6
- ngx-translate 7.0.0
- OS Linux

**Comment by marshallcool** [comment]
open issue

**Comment by Juliozen** [comment]
I have the same issue.... 


node_modules/@angular/core/core"' has no exported member 
            'OpaqueToken'. 

       L1:  import { EventEmitter, OpaqueToken } from "@angular/core";
       L2:  import { Observable } from "rxjs/Observable";

Error: The Angular AoT build failed. See the issues above
node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:232:55
    at step (/Users/julioZM/Documents/wemob-chat-app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/Users/julioZM/Documents/wemob-chat-app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/Users/julioZM/Documents/wemob-chat-app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
    at <anonymous>

**Comment by qlaffont** [comment]
@premiumwd you solve your problem actually ?

**Comment by frontr-uk** [comment]
why is this closed if there is still issue

**Comment by elgreatly** [comment]
i have the same issue in Angular 5

**Comment by Gorniv** [comment]
this is https://github.com/angular/angular-cli/issues/7200
ngx-translate is good work: https://github.com/Angular-RU/angular-universal-starter

**Comment by elgreatly** [comment]
i have the same issue, is there any solution?
