### ISSUE TITLE
bug(express-engine): server fails with new StaticInjector

### ISSUE THREAD

**Issue by CaerusKaru** [angular/universal#774]
* **I'm submitting a ...**
```
- [x] bug report
- [ ] feature request
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x] express-engine
- [ ] hapi-engine
```

* **What is the current behavior?**

express-engine fails to start due to problems with the new StaticInjector in Angular v5.0.0

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

1. Create new universal project
2. Upgrade deps to Angular v5.0.0-beta.3
3. Try to run a server using express-engine

* **What is the expected behavior?**

express-engine should load dependencies using the new StaticInjector pattern introduced in Angular v5.0.0

* **What is the motivation / use case for changing the behavior?**

express-engine is unusable without these changes in the newest release of Angular

* **Please tell us about your environment:**

- Angular version: 5.0.0-beta.3
- Browser: [**all** | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [**all** | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [**all** | Mac OS X | Windows | Linux ]
- Platform: [**all** | NodeJs | Java | PHP | .NETCore | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

```
/home/debian/angular2/package/node_modules/@angular/core/bundles/core.umd.js:1598
        throw staticError('\'deps\' required', provider);
        ^

Error: StaticInjectorError[{provide:ResourceLoader, useClass:FileLoader}]: 'deps' required
    at staticError (/home/debian/angular2/package/node_modules/@angular/core/bundles/core.umd.js:1631:12)
    at computeDeps (/home/debian/angular2/package/node_modules/@angular/core/bundles/core.umd.js:1598:15)
    at resolveProvider (/home/debian/angular2/package/node_modules/@angular/core/bundles/core.umd.js:1389:33)
    at recursivelyProcessProviders (/home/debian/angular2/package/node_modules/@angular/core/bundles/core.umd.js:1446:53)
    at recursivelyProcessProviders (/home/debian/angular2/package/node_modules/@angular/core/bundles/core.umd.js:1435:17)
    at recursivelyProcessProviders (/home/debian/angular2/package/node_modules/@angular/core/bundles/core.umd.js:1435:17)
    at new StaticInjector (/home/debian/angular2/package/node_modules/@angular/core/bundles/core.umd.js:1354:9)
    at Function.Injector.create (/home/debian/angular2/package/node_modules/@angular/core/bundles/core.umd.js:1323:16)
    at JitCompilerFactory.createCompiler (/home/debian/angular2/package/node_modules/@angular/compiler/bundles/compiler.umd.js:27754:64)
    at Object.ngExpressEngine (/home/debian/angular2/package/node_modules/@nguniversal/express-engine/src/main.js:22:36)
```

**Comment by gdi2290** [comment]
can you make a PR adding `deps` here
https://github.com/angular/universal/blob/master/modules/ng-express-engine/src/main.ts#L46

**Comment by CaerusKaru** [comment]
@gdi2290 Submitted the PR, let me know if there's anything else I need to add

**Comment by CaerusKaru** [comment]
@gdi2290 Fixed some CLA issues and submitted a new PR, should be all set now

**Comment by Coichecan** [comment]
Novice, Looking for a project to get involved.

**Comment by Toxicable** [comment]
can be closed via https://github.com/angular/universal/commit/5c705cb51362bd448c0b8ac293da867a3a1913f4
