### ISSUE TITLE
ngc ReferenceError - window not defined

### ISSUE THREAD

**Issue by samarmeena** [angular/universal#784]
**Reference-error occurred in imported modules in angular 4**

I have angular 4 with angular cli. I imported ngx-swiper-wrapper in app.module.ts. and when I run ng build --prod. its successfully build and run's good.

but while running angular universal with ngc. a error comes up that window not defined.

**log of ngc**

chunk {5} inline.319a5e6a181e7a260695.bundle.js (inline) 1.47 kB [entry] [rendered]

> ts-node src/server.ts

****\node_modules\ngx-swiper-wrapper\bundles\webpack:\~\swiper\dist\js\swiper.js:5338
})();
^
ReferenceError: window is not defined
    at ****\node_modules\ngx-swiper-wrapper\bundles\webpack:\~\swiper\dist\js\swiper.js:4497:1
    at ****\node_modules\ngx-swiper-wrapper\bundles\webpack:\~\swiper\dist\js\swiper.js:4499:1
    at Object.module.exports (****\node_modules\ngx-swiper-wrapper\bundles\webpack:\~\swiper\dist\js\swiper.js:5338:1)
    at __webpack_require__ (****\node_modules\ngx-swiper-wrapper\bundles\webpack:\webpack\bootstrap d10350c57895c95602d5:19:1)
    at Object.c (****\node_modules\ngx-swiper-wrapper\bundles\webpack:\src\lib\swiper.directive.ts:14:1)
    at __webpack_require__ (****\node_modules\ngx-swiper-wrapper\bundles\webpack:\webpack\bootstrap d10350c57895c95602d5:19:1)
    at Object.<anonymous> (****\node_modules\ngx-swiper-wrapper\bundles\webpack:\src\lib\swiper.component.ts:15:1)
    at __webpack_require__ (****\node_modules\ngx-swiper-wrapper\bundles\webpack:\webpack\bootstrap d10350c57895c95602d5:19:1)
    at Object.module.exports (****\node_modules\ngx-swiper-wrapper\bundles\webpack:\src\lib\index.ts:2:1)
    at __webpack_require__ (****\node_modules\ngx-swiper-wrapper\bundles\webpack:\webpack\bootstrap d10350c57895c95602d5:19:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ****@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! debug.log

**Comment by Toxicable** [comment]
After inspecting your stack trace I notice that the error is occurring in `ngx-swiper-wrapper` indicating that this is not a Universal compliant Library.
While we will try make it easier to use libs like this in the future right now this is not an issue with Universal

**Comment by samarmeena** [comment]
Thank @Toxicable. I fixed it with repairing all the modules.

**Comment by MarkPieszak** [comment]
Repairing the modules? @samarmeena

**Comment by kartikgreen** [comment]
@ samarmeena, how did you do that?

**Comment by samarmeena** [comment]
@kartikgreen 
use **PLATFORM** from Angular. This will allow angular universal to detect server side and client side.
to run specific function on server side or client side only. 

While running the code at client side only will not return any error on angular universal build.

**Comment by kartikgreen** [comment]
I have the error on the same package, How did you resolve this?

**Comment by samarmeena** [comment]
@kartikgreen 
Using PLATFORM module from angular.

**Comment by kartikgreen** [comment]
The same issue and the error that you posted here.

**Comment by Gorniv** [comment]
Are you use `domino'?
I use `domino` in https://github.com/Angular-RU/angular-universal-starter/blob/master/server.ts may be it fix your problem?

**Comment by kartikgreen** [comment]
no ngx-swiper-wrapper

**Comment by samarmeena** [comment]
@kartikgreen 
Then you can solve using Platform module.

Otherwise @Gorniv is also right about this issue, you can also choose domino to fix it.
But using Platform from angular you can fix the issue at required place only.
