### ISSUE TITLE
SyntaxError Unexpected token import : on ngx-bootstrap

### ISSUE THREAD

**Issue by mbero** [angular/universal#813]
* **I'm submitting a ...**
```
- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x ] express-engine
- [ ] hapi-engine
```

I have given stacktrace during execution **node server.js** command (where server.js is of course file name for express engine server file) : 

\node_modules\ngx-bootstrap\dropdown\bs-dropdown-container.component.js:1
(function (exports, require, module, __filename, __dirname) { import { ChangeDetectionStrategy, ChangeDetectorRef, Component } from '@angular/core';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.z/jI (E:\ng4-portal-angular\dist-server\main.bundle.js:1:1598837)
    at n (E:\ng4-portal-angular\dist-server\main.bundle.js:1:211)	

Did anyone have similar problem with ngx-bootsrap ? It's angular4 universal thing, or lack of compability with server side rendering in this library ?  I appreciate any help or answer 

* **Please tell us about your environment:**

- Angular version: 4.4
- Language: [all]
- OS:  Windows
- Platform:  NodeJs

**Comment by MarkPieszak** [comment]
If this is using the universal-starter can you re-open the issue there?
It looks like you need to get latest updates there and make sure that server file is a TS one and webpack it. Otherwise it can't handle third party things correctly (that's another open issue) hope that helps !

**Comment by nimatullah** [comment]
@MarkPieszak , I had the issue when I start using universal-starter on my project. following is the issue.

```
/home/razmjo/workstation/jobsaf-website/node_modules/ngx-bootstrap/modal/index.js:1
(function (exports, require, module, __filename, __dirname) { export { BsModalRef } from './bs-modal-ref.service';
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
[nodemon] app crashed - waiting for file changes before starting...


```
