### ISSUE TITLE
(express-engine) StaticInjectorError - 'deps' required 

### ISSUE THREAD

**Issue by leo6104** [angular/universal#817]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
```
- [o] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [o] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
ngExpressEngine's FileLoader provider throw deps required error.

```
/Users/sangmin/WebstormProjects/mapia_ng2/node_modules/@angular/core/bundles/core.umd.js:1296
        throw staticError('\'deps\' required', provider);
        ^

Error: StaticInjectorError[{provide:ResourceLoader, useClass:FileLoader}]: 'deps' required
    at staticError (~/node_modules/@angular/core/bundles/core.umd.js:1329:12)
    at computeDeps (~/node_modules/@angular/core/bundles/core.umd.js:1296:15)
    at resolveProvider (~/node_modules/@angular/core/bundles/core.umd.js:1091:33)
    at recursivelyProcessProviders (~/node_modules/@angular/core/bundles/core.umd.js:1148:53)
    at recursivelyProcessProviders (~/node_modules/@angular/core/bundles/core.umd.js:1137:17)
    at recursivelyProcessProviders (~/node_modules/@angular/core/bundles/core.umd.js:1137:17)
    at new StaticInjector (~/node_modules/@angular/core/bundles/core.umd.js:1048:9)
    at Function.Injector.create (~/node_modules/@angular/core/bundles/core.umd.js:1020:16)
    at JitCompilerFactory.createCompiler (~/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js:436:64)
    at ngExpressEngine (~/node_modules/@nguniversal/express-engine/src/main.js:22:36)

```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

* **What is the expected behavior?**
add deps: [] to provider 

* **What is the motivation / use case for changing the behavior?**
https://github.com/angular/angular/search?utf8=%E2%9C%93&q=%7Bprovide%3A+ResourceLoader%2C&type=

There is no provider (provide, useClass) use case without deps in angular

* **Please tell us about your environment:**

- Angular version: 5.0.0-rc.1
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: NodeJs

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Toxicable** [comment]
Could you try upgrading to the latest version (5.0.0-beta.0) and see if that works for you?

**Comment by leo6104** [comment]
It works! Thanks @Toxicable
