### ISSUE TITLE
ERROR TypeError: Cannot read property 'attribs' of undefined. (When using universal-starter kit + ng-bootstrap ngbDropdown)

### ISSUE THREAD

**Issue by Pulsarcode** [angular/universal#822]
* **I'm submitting a ...**
```
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x] express-engine (may be, not sure)
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**
report a bug

* **What is the current behavior?**
using the universal-starter kit with ng-bootstrap ngbDropdown cause this error when build package for production environment:

Command:

```bash
npm run build:dynamic && npm run serve:dynamic
```

Output:

```
ERROR TypeError: Cannot read property 'attribs' of undefined
    at Parse5DomAdapter.classList (/usr/share/nginx/vhosts/parclick.com/src/Parclick/WebBundle/Resources/angular/dist/server.js:47969:50)
    at Parse5DomAdapter.removeClass (/usr/share/nginx/vhosts/parclick.com/src/Parclick/WebBundle/Resources/angular/dist/server.js:47994:47)
    at DefaultServerRenderer2.removeClass (/usr/share/nginx/vhosts/parclick.com/src/Parclick/WebBundle/Resources/angular/dist/server.js:48880:151)
    at BaseAnimationRenderer.removeClass (/usr/share/nginx/vhosts/parclick.com/src/Parclick/WebBundle/Resources/angular/dist/server.js:54157:87)
    at NgbDropdownMenu.applyPlacement (/usr/share/nginx/vhosts/parclick.com/src/Parclick/WebBundle/Resources/angular/dist/server.js:44557:24)
    at NgbDropdown.ngOnInit (/usr/share/nginx/vhosts/parclick.com/src/Parclick/WebBundle/Resources/angular/dist/server.js:44631:24)
    at checkAndUpdateDirectiveInline (/usr/share/nginx/vhosts/parclick.com/src/Parclick/WebBundle/Resources/angular/dist/server.js:11130:19)
    at checkAndUpdateNodeInline (/usr/share/nginx/vhosts/parclick.com/src/Parclick/WebBundle/Resources/angular/dist/server.js:12638:17)
    at checkAndUpdateNode (/usr/share/nginx/vhosts/parclick.com/src/Parclick/WebBundle/Resources/angular/dist/server.js:12577:16)
    at prodCheckAndUpdateNode (/usr/share/nginx/vhosts/parclick.com/src/Parclick/WebBundle/Resources/angular/dist/server.js:13274:5)
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
https://github.com/Pulsarcode/temp-1

* **What is the expected behavior?**
not show in the node express server a constant error message

* **What is the motivation / use case for changing the behavior?**
N/A

* **Please tell us about your environment:**

```
ng version:

@angular/cli: 1.4.3
node: 8.5.0
os: linux x64
@angular/animations: 4.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/platform-server: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.3
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.3.4
```

```
npm version:

{
  unicorn: '1.0.0',
  npm: '5.4.2',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.5.0',
  openssl: '1.0.2l',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.14.1',
  v8: '6.0.287.53',
  zlib: '1.2.11'
}
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
see the repo for more details https://github.com/Pulsarcode/temp-1

**Comment by Toxicable** [comment]
This is an error with ng-bootstrap they have a PR to fix it here https://github.com/ng-bootstrap/ng-bootstrap/pull/1883

**Comment by Pulsarcode** [comment]
@Toxicable thanks! :-)
