### ISSUE TITLE
Proper redirects with status codes (SEO reasons)

### ISSUE THREAD

**Issue by MrCroft** [angular/universal#827]
* **I'm submitting a ...**
```
- [x] feature request
```

* **What modules are related to this Issue?**
```
- [x] aspnetcore-engine
- [x] express-engine
- [x] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**
Request a **feature**

* **What is the current behavior?**
Currently, if we have a `redirectTo` in our route config or `router.navigate` or `router.navigateByUrl` in our code, Universal renders the appropriate component, but doesn't actually do a redirect.

* **What is the expected behavior?**
Given a `redirectTo` in our route config or `router.navigate/navigateByUrl` anywhere in our code, Universal should actually redirect to the appropriate route.

* **What is the motivation / use case for changing the behavior?**
For obvious SEO reasons (301, 404).
Ideally, the `@angular/router` should also facilitate a way to let Universal know what status code is needed (but that would be an issue for the router).

* **Please tell us about your environment:**

- Angular version: 4+
- Platform: [NodeJs]

**Comment by PsychicCat** [comment]
You should be able to do this already by importing the RESPONSE token from '@nguniversal/express-engine/tokens' then injecting that into an Angular service which subscribes to the router events. I would then filter for NavigationEnd, and then check if the urlAfterRedirects is different from the url. If so, set the response code to 302. 

The same premise can be applied to actual 404, 500, whatever status code you want to send on server render.

**Comment by MrCroft** [comment]
@PsychicCat I was just thinking that, for core functionalities, it would be very useful.
The less we have to clutter the code with providing different services/classes for server and for the browser, the better.

**Comment by patrickmichalina** [comment]
@MrCroft please check https://github.com/patrickmichalina/fusebox-angular-universal-starter/blob/master/src/client/app/app.component.ts

It listen for data.response in router-module configurations to apply cache settings to the given route. I will make this a module in the future, but can give you some ideas - similar to what @PsychicCat  is saying

**Comment by michaelbromley** [comment]
I've tried the approach hinted at in the [comment above](https://github.com/angular/universal/issues/827#issuecomment-336678824), namely having a service which does this:

```ts
import { RESPONSE } from '@nguniversal/express-engine/tokens';
import { Inject, Injectable, Optional } from '@angular/core';
import { Response } from 'express';

@Injectable({ providedIn: 'root' })
export class ServerResponseService {
    private response: Response;

    constructor(@Optional() @Inject(RESPONSE) response: any) {
        this.response = response;
    }

    setStatus(code: number, message?: string): this {
        if (this.response) {
            this.response.statusCode = code;
            if (message) this.response.statusMessage = message;
        }
        return this;
    }

    redirect(url: string): this {
        if (this.response) {
            this.response.statusCode = 301;
            this.response.header('location', url);
        }
        return this;
    }
}
```

and it _seemed_ to work ok but I was getting errors in the console of the SSR server. With updating to Angular v16, these errors now cause the server to crash, so this approach seems now unworkable.

The error is:

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (C:\Development\kbart\artsupplies-vendure\dist\apps\storefront\server\main.
js:60615:10)
    at ServerResponseService.redirect (C:\Development\kbart\artsupplies-vendure\dist\apps\storefront\ser
ver\main.js:8762:23)
    at C:\Development\kbart\artsupplies-vendure\dist\apps\storefront\server\main.js:9130:38
    at C:\Development\kbart\artsupplies-vendure\dist\apps\storefront\server\main.js:92958:31
    at OperatorSubscriber._this._next (C:\Development\kbart\artsupplies-vendure\dist\apps\storefront\ser
ver\main.js:91057:9)
    at OperatorSubscriber.Subscriber.next (C:\Development\kbart\artsupplies-vendure\dist\apps\storefront
\server\main.js:88769:12)
    at C:\Development\kbart\artsupplies-vendure\dist\apps\storefront\server\main.js:94804:27
    at OperatorSubscriber._this._next (C:\Development\kbart\artsupplies-vendure\dist\apps\storefront\ser
ver\main.js:91057:9) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

It seems that attempting to set `response.header()` will trigger this error. Just setting `response.statusCode = 301` seems to have no effect, the response is still 200 in the browser.

I suspect that the root cause is that all of the Angular app code is running inside of the express `render()` function, which means that headers have already been set.

So yes, we are really in need to a good solution to this which probably will require some work on the core rendering mechanism to allow status codes & headers to be set from app code.
