### ISSUE TITLE
Unable to create Universal application using Webpack without the CLI

### ISSUE THREAD

**Issue by mogusbi** [angular/universal#843]
* **I'm submitting a ...**
```
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
I am trying to build a universal app with Angular 5 and WebPack without the cli.

The issue I am having is that I cannot seem to get the express application to work and I am met with this error every time I hit the server

```
Error: You must pass in a NgModule or NgModuleFactory to be bootstrapped
    at View.engine (/Volumes/Data/Users/mo/Desktop/ng5-universal-webpack/node_modules/@nguniversal/express-engine/src/main.js:34:23)
    at View.render (/Volumes/Data/Users/mo/Desktop/ng5-universal-webpack/node_modules/express/lib/view.js:135:8)
    at tryRender (/Volumes/Data/Users/mo/Desktop/ng5-universal-webpack/node_modules/express/lib/application.js:640:10)
    at Function.render (/Volumes/Data/Users/mo/Desktop/ng5-universal-webpack/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Volumes/Data/Users/mo/Desktop/ng5-universal-webpack/node_modules/express/lib/response.js:1008:7)
    at /Volumes/Data/Users/mo/Desktop/ng5-universal-webpack/dist/server.js:122:47
    at Layer.handle [as handle_request] (/Volumes/Data/Users/mo/Desktop/ng5-universal-webpack/node_modules/express/lib/router/layer.js:95:5)
    at next (/Volumes/Data/Users/mo/Desktop/ng5-universal-webpack/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Volumes/Data/Users/mo/Desktop/ng5-universal-webpack/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Volumes/Data/Users/mo/Desktop/ng5-universal-webpack/node_modules/express/lib/router/layer.js:95:5)
```

I believe the issue is to do with the server application bundle that's then consumed by `server.ts` because if I console log out `AppServerModuleNgFactory` it comes up as undefined.

You can find a repo at https://github.com/mogusbi/ng5-universal-webpack. Clone that, run `npm start` and go to `localhost:4000`

* **What is the expected behavior?**
For the application to be rendered on the server

* **Please tell us about your environment:**

- Angular version: 5.0.1
- Browser: [all ]
- Language: [TypeScript 2.4.2]
- OS:  [Mac OS X ]
- Platform: [NodeJs]

**Comment by Toxicable** [comment]
>I believe the issue is to do with the server application bundle that's then consumed by server.ts because if I console log out AppServerModuleNgFactory it comes up as undefined.

This is your issue, you have an error with your Webpack config, this isn't an issue with Universal

**Comment by mogusbi** [comment]
I’ve opened up an issue over at the CLI repo but are you able to see what the issue with my config is? I’ve delved through the CLI code to try and replicate it but I’ve had no luck

**Comment by Toxicable** [comment]
I personally cannot help you with webpack configs, I don't know very little about it.

**Comment by mogusbi** [comment]
I've eventually worked out why the ModuleNgFactories weren't being generated after delving into nitty gritty of the CLI source code and it's literally just because there's an undocumented option in the `AngularCompilerPlugin` called `platform` - it needs to be set to `1` to generate the server application bundle that then gets consumed by `ngExpressEngine` in the `express` application.

Once you do that, everything works as you expect it to! 😄

**Comment by freezy** [comment]
Any way you can update your repo with the change?

**Comment by miscoo1** [comment]
+1
