### ISSUE TITLE
fixedAttrs.map is not a function

### ISSUE THREAD

**Issue by supertensor** [angular/universal#866]
Hi,
I have compiled the angular universal in window. when I upload  to linux server there is issue. When I compile code on ubuntu server then It works. What is the problems ??
========================================================
ERROR
========================================================
TypeError: fixedAttrs.map is not a function
    at Object.elementDef [as ɵeld] (/var/www/html/superclient/node_modules/@angular/core/bundles/core.umd.js:9149:46)
    at c (/var/www/html/superclient/dist/dist-server/main.bundle.js:1:268518)
    at resolveDefinition (/var/www/html/superclient/node_modules/@angular/core/bundles/core.umd.js:8789:17)
    at ComponentFactory_.create (/var/www/html/superclient/node_modules/@angular/core/bundles/core.umd.js:9902:40)
    at ComponentFactoryBoundToModule.create (/var/www/html/superclient/node_modules/@angular/core/bundles/core.umd.js:3365:29)
    at ApplicationRef_.bootstrap (/var/www/html/superclient/node_modules/@angular/core/bundles/core.umd.js:4800:57)
    at /var/www/html/superclient/node_modules/@angular/core/bundles/core.umd.js:4578:81
    at Array.forEach (<anonymous>)
    at PlatformRef_._moduleDoBootstrap (/var/www/html/superclient/node_modules/@angular/core/bundles/core.umd.js:4578:44)
    at /var/www/html/superclient/node_modules/@angular/core/bundles/core.umd.js:4540:27

**Comment by Toxicable** [comment]
Could you please provide a *minimal* reproduction of this issue

**Comment by 2upmedia** [comment]
@supertensor this is most likely caused by a difference in your angular compiler version vs angular common and the rest of the angular libraries. Have a look at your lock file and find the compiler version and see if differs from the rest of the angular libraries.
