### ISSUE TITLE
Warning while compile when using Express Request

### ISSUE THREAD

**Issue by m98** [angular/universal#870]
* **I'm submitting a ...**
```
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

_@gdi2290 You have provided an answer for this issue on this [Angular issue](https://github.com/angular/angular/issues/11580#issuecomment-327338189), but sounds there is some problems yet. Could you please take a look at this? I'm using [Angular/universal-starter](https://github.com/angular/universal-starter)_

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**
Report a bug (It's already asked on above checklist)

* **What is the current behavior?**
When using Express request, the `ng server` or `ng serve --aot` returns a warning message as:

>WARNING in ./node_modules/express/lib/view.js
81:13-25 Critical dependency: the request of a dependency is an expression
at CommonJsRequireContextDependency.getWarnings (/home/mohammad/Projects/ZZZProject/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
at Compilation.reportDependencyErrorsAndWarnings (/home/mohammad/Projects/ZZZProject/node_modules/webpack/lib/Compilation.js:703:24)
at Compilation.finish (/home/mohammad/Projects/ZZZProject/node_modules/webpack/lib/Compilation.js:561:9)
at applyPluginsParallel.err (/home/mohammad/Projects/ZZZProject/node_modules/webpack/lib/Compiler.js:502:17)
at /home/mohammad/Projects/ZZZProject/node_modules/tapable/lib/Tapable.js:289:11
at _addModuleChain (/home/mohammad/Projects/ZZZProject/node_modules/webpack/lib/Compilation.js:507:11)
at processModuleDependencies.err (/home/mohammad/Projects/ZZZProject/node_modules/webpack/lib/Compilation.js:477:14)
at _combinedTickCallback (internal/process/next_tick.js:131:7)
at process._tickCallback (internal/process/next_tick.js:180:9)
@ ./node_modules/express/lib/view.js
@ ./node_modules/express/lib/application.js
@ ./node_modules/express/lib/express.js
@ ./node_modules/express/index.js
@ ./src/app/shared/service/request.service.ts
@ ./src/app/app.module.ngfactory.js
@ ./src/main.ts
@ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

It causes the web app not work

**Here is how I used the Express Request:**
```
import {Inject, Injectable} from '@angular/core';
import {Request} from 'express';
import {REQUEST} from '@nguniversal/express-engine/tokens';
import {HelperService} from './helper.service';

@Injectable()
export class RequestService {
  constructor(@Inject(REQUEST) private request: Request, private helperService: HelperService) {
  }

  getRequest() {
    if (!this.helperService.isBrowser()) {
      return this.request;
    }
    return false;
  }
}
```

* **What is the expected behavior?**
No error behavior

* **Please tell us about your environment:**

- Angular version: 5
- Browser: Crhome
- Language: TypeScript
- OS:  Platform
- Platform: NodeJs

**Comment by m98** [comment]
Close, because it should be related to angular/universal-starter
