### ISSUE TITLE
Observable.subscribe do not work on server? `Cannot read property 'subscribe' of undefined` error on server error

### ISSUE THREAD

**Issue by abeninski** [angular/universal#905]
* **I'm submitting a ...**
```
- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [ x] express-engine
- [ ] hapi-engine
```

* **Please tell us about your environment:**

- Angular version: 5.X
- OS:  [Windows  ]
- Platform: [ NodeJs ] Server

Getting this error:
`ERROR { Error: Uncaught (in promise): TypeError: Cannot read property 'subscribe' of undefined                    
TypeError: Cannot read property 'subscribe' of undefined                                                          
    at scheduleTask (C:\dev\kiso\universal\dist\server.js:131999:31)                                              
    at Observable._subscribe (C:\dev\kiso\universal\dist\server.js:132037:13)                                     
    at Observable._trySubscribe (C:\dev\kiso\universal\dist\server.js:34273:25)                                   
    at Observable.subscribe (C:\dev\kiso\universal\dist\server.js:34261:93)                                       
    at Object.subscribeToResult (C:\dev\kiso\universal\dist\server.js:58503:27)                                   
    at MergeMapSubscriber._innerSub (C:\dev\kiso\universal\dist\server.js:63610:38)                               
    at MergeMapSubscriber._tryNext (C:\dev\kiso\universal\dist\server.js:63607:14)                                
    at MergeMapSubscriber._next (C:\dev\kiso\universal\dist\server.js:63590:18)                                   
    at MergeMapSubscriber.Subscriber.next (C:\dev\kiso\universal\dist\server.js:34502:18)                         
    at ScalarObservable._subscribe (C:\dev\kiso\universal\dist\server.js:63404:24)                                
    at resolvePromise (C:\dev\kiso\universal\dist\server.js:160299:31)                                            
    at resolvePromise (C:\dev\kiso\universal\dist\server.js:160265:17)                                            
    at C:\dev\kiso\universal\dist\server.js:160348:17                                                             
    at ZoneDelegate.invokeTask (C:\dev\kiso\universal\dist\server.js:159911:31)                                   
    at Object.onInvokeTask (C:\dev\kiso\universal\dist\server.js:9777:33)                                         
    at ZoneDelegate.invokeTask (C:\dev\kiso\universal\dist\server.js:159910:36)                                   
    at Zone.runTask (C:\dev\kiso\universal\dist\server.js:159678:47)                                              
    at drainMicroTaskQueue (C:\dev\kiso\universal\dist\server.js:160085:35)                                       
    at ZoneTask.invokeTask (C:\dev\kiso\universal\dist\server.js:159990:21)                                       
    at Server.ZoneTask.invoke (C:\dev\kiso\universal\dist\server.js:159975:48)                                    
  rejection: TypeError: Cannot read property 'subscribe' of undefined                                             
    at scheduleTask (C:\dev\kiso\universal\dist\server.js:131999:31)                                              
    at Observable._subscribe (C:\dev\kiso\universal\dist\server.js:132037:13)                                     
    at Observable._trySubscribe (C:\dev\kiso\universal\dist\server.js:34273:25)                                   
    at Observable.subscribe (C:\dev\kiso\universal\dist\server.js:34261:93)                                       
    at Object.subscribeToResult (C:\dev\kiso\universal\dist\server.js:58503:27)                                   
    at MergeMapSubscriber._innerSub (C:\dev\kiso\universal\dist\server.js:63610:38)                               
    at MergeMapSubscriber._tryNext (C:\dev\kiso\universal\dist\server.js:63607:14)                                
    at MergeMapSubscriber._next (C:\dev\kiso\universal\dist\server.js:63590:18)                                   
    at MergeMapSubscriber.Subscriber.next (C:\dev\kiso\universal\dist\server.js:34502:18)                         
    at ScalarObservable._subscribe (C:\dev\kiso\universal\dist\server.js:63404:24),                               
  promise:                                                                                                        
   ZoneAwarePromise {                                                                                             
     __zone_symbol__state: 0,                                                                                     
     __zone_symbol__value: TypeError: Cannot read property 'subscribe' of undefined                               
    at scheduleTask (C:\dev\kiso\universal\dist\server.js:131999:31)                                              
    at Observable._subscribe (C:\dev\kiso\universal\dist\server.js:132037:13)                                     
    at Observable._trySubscribe (C:\dev\kiso\universal\dist\server.js:34273:25)                                   
    at Observable.subscribe (C:\dev\kiso\universal\dist\server.js:34261:93)                                       
    at Object.subscribeToResult (C:\dev\kiso\universal\dist\server.js:58503:27)                                   
    at MergeMapSubscriber._innerSub (C:\dev\kiso\universal\dist\server.js:63610:38)                               
    at MergeMapSubscriber._tryNext (C:\dev\kiso\universal\dist\server.js:63607:14)                                
    at MergeMapSubscriber._next (C:\dev\kiso\universal\dist\server.js:63590:18)                                   
    at MergeMapSubscriber.Subscriber.next (C:\dev\kiso\universal\dist\server.js:34502:18)                         
    at ScalarObservable._subscribe (C:\dev\kiso\universal\dist\server.js:63404:24) },                             
  zone:                                                                                                           
   Zone {                                                                                                         
     _properties: { isAngularZone: true },                                                                        
     _parent:                                                                                                     
      Zone {                                                                                                      
        _properties: {},                                                                                          
        _parent: null,                                                                                            
        _name: '<root>',                                                                                          
        _zoneDelegate: [Object] },                                                                                
     _name: 'angular',                                                                                            
     _zoneDelegate:                                                                                               
      ZoneDelegate {                                                                                              
        _taskCounts: [Object],                                                                                    
        zone: [Circular],                                                                                         
        _parentDelegate: [Object],                                                                                
        _forkZS: null,                                                                                            
        _forkDlgt: null,                                                                                          
        _forkCurrZone: [Object],                                                                                  
        _interceptZS: null,                                                                                       
        _interceptDlgt: null,                                                                                     
        _interceptCurrZone: [Object],                                                                             
        _invokeZS: [Object],                                                                                      
        _invokeDlgt: [Object],                                                                                    
        _invokeCurrZone: [Circular],                                                                              
        _handleErrorZS: [Object],                                                                                 
        _handleErrorDlgt: [Object],                                                                               
        _handleErrorCurrZone: [Circular],                                                                         
        _scheduleTaskZS: [Object],                                                                                
        _scheduleTaskDlgt: [Object],                                                                              
        _scheduleTaskCurrZone: [Circular],                                                                        
        _invokeTaskZS: [Object],                                                                                  
        _invokeTaskDlgt: [Object],                                                                                
        _invokeTaskCurrZone: [Circular],                                                                          
        _cancelTaskZS: [Object],                                                                                  
        _cancelTaskDlgt: [Object],                                                                                
        _cancelTaskCurrZone: [Circular],                                                                          
        _hasTaskZS: [Object],                                                                                     
        _hasTaskDlgt: [Object],                                                                                   
        _hasTaskDlgtOwner: [Circular],                                                                            
        _hasTaskCurrZone: [Circular] } },                                                                         
  task:                                                                                                           
   ZoneTask {                                                                                                     
     _zone:                                                                                                       
      Zone {                                                                                                      
        _properties: [Object],                                                                                    
        _parent: [Object],                                                                                        
        _name: 'angular',                                                                                         
        _zoneDelegate: [Object] },                                                                                
     runCount: 0,                                                                                                 
     _zoneDelegates: null,                                                                                        
     _state: 'notScheduled',                                                                                      
     type: 'microTask',                                                                                           
     source: 'Promise.then',                                                                                      
     data: undefined,                                                                                             
     scheduleFn: undefined,                                                                                       
     cancelFn: null,                                                                                              
     callback: [Function],                                                                                        
     invoke: [Function] } } `

App works perfectly fine if I run it with `ng serve`.
When I start the server and make a request I get no response in the browser and I see this error in the console..
Any ideas how to debug which object is undefined that doesn't have `subscribe` because this minified code is awful to debug.
I start my app using: `npm run build:ssr && npm run serve:ssr`

**Comment by abeninskibede** [comment]
Please help. I'm desperate. Can't get any of Httpclient requests to work.

Console.log of `this.http.get<Post>(url)` shows that object is not undefined but code keeps on saying that it is.
`Observable {
  _isScalar: false,
  source:
   Observable {
     _isScalar: false,
     source:
      Observable {
        _isScalar: false,
        source: [ScalarObservable],
        operator: [MergeMapOperator] },
     operator: FilterOperator { predicate: [Function], thisArg: undefined } },
  operator: MapOperator { project: [Function], thisArg: undefined } }`

`ERROR TypeError: Cannot read property 'subscribe' of undefined`

**Comment by abeninski** [comment]
My bad: haven't called `return next.handle(req);` in the interceptor on the server.
