### ISSUE TITLE
server.ts bad compiled

### ISSUE THREAD

**Issue by mousavidev** [angular/universal#956]
My app is successfully compiled, but it does not work when i will running execution command.
The error is shown below
### server.js
compiled by webpack
```
/home/mousavi/Public/Projects/Web/Angular World/AngularWorld.Client/dist/server.js:159954
module.exports = !../../../node_modules/style-loader/lib/addStyles.js;
                  ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! application@0.0.1 serve:universal: `node dist/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the application@0.0.1 serve:universal script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mousavi/.npm/_logs/2018-04-07T19_22_35_165Z-debug.log
The terminal process terminated with exit code: 1
```

I think the codes are not compiled correctly by webpack.

**Comment by Toxicable** [comment]
Sorry but there's not much we can do without a minimal reproduction.

**Comment by Toxicable** [comment]
Closing as this is not actionable
